import type { Locale } from "./locale";

export const appCopy = {
  en: {
    appName: "Kaenz",
    location: "South Florida",
    tabs: {
      places: "Places",
      yachts: "Yachts",
      request: "Request",
      trip: "Your Trip",
      crew: "Crew",
    },
    placesLead: "Marinas, ports, and places to enjoy in Florida.",
    searchPlaces: "Search marinas, ports, sandbars…",
    kinds: { all: "All", marina: "Marinas", port: "Ports", place: "Places" },
    byYacht: "by yacht",
    byCar: "by car",
    setPickup: "Set pickup",
    setDropoff: "Set dropoff",
    waterOnly: "Water only",
    yachtsLead: "Yachts with a verified captain, available in your area.",
    nearby: "Near you",
    verified: "Captain verified",
    guests: "guests",
    from: "From",
    away: "away",
    requestThis: "Request this yacht",
    useLocation: "Use my location",
    requestLead: "Request a yacht for a commute, tour, or special occasion.",
    kindsTrip: {
      commute: { title: "Commute", body: "Beat the bridges. Get there faster than the car." },
      tour: { title: "Tour", body: "Sandbars, skyline, and hours on the water." },
      special: { title: "Special occasion", body: "Sunsets, celebrations, clients on deck." },
    },
    pickup: "Pickup",
    dropoff: "Destination",
    when: "When",
    time: "Time",
    who: "Guests",
    yacht: "Yacht",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    continueTrip: "Continue to Your Trip",
    choosePickup: "Choose a pickup",
    chooseDropoff: "Choose a destination",
    tripLead: "Verify your trip request and payment information.",
    noTrip: "No trip yet. Request a yacht to see your fare and pay.",
    requestCta: "Request a yacht",
    route: "Route",
    captain: "Captain",
    fare: "Fare",
    boat: "Yacht & fuel",
    ownerShare: "Owner (40%)",
    captainShare: "Captain (30%)",
    platformShare: "Kaenz (30%)",
    total: "Total",
    pay: "Payment",
    card: "Card",
    solana: "Solana",
    cardNumber: "Card number",
    expiry: "Expiry",
    cvc: "CVC",
    wallet: "Solana wallet",
    payConfirm: "Pay & confirm trip",
    paying: "Confirming…",
    confirmed: "Trip confirmed",
    statusRequested: "Request sent",
    statusConfirmed: "Captain confirmed",
    statusUnderway: "Underway",
    demoPay: "Demo checkout — Kaenz does not charge your card in this preview.",
    crewLead: "Share with interesting people in this social experience.",
    goingTo: "Going to",
    joinCrew: "Join this crew",
    joined: "You’re on this crew",
    likes: "likes",
    write: "Share a note with the crew…",
    post: "Post",
    interests: "Into",
    openMarketing: "Kaenz.com",
  },
  es: {
    appName: "Kaenz",
    location: "South Florida",
    tabs: {
      places: "Lugares",
      yachts: "Yates",
      request: "Solicitar",
      trip: "Tu Viaje",
      crew: "Tripulación",
    },
    placesLead: "Marinas, puertos y lugares para disfrutar en Florida.",
    searchPlaces: "Busca marinas, puertos, sandbars…",
    kinds: { all: "Todos", marina: "Marinas", port: "Puertos", place: "Lugares" },
    byYacht: "en yate",
    byCar: "en auto",
    setPickup: "Origen",
    setDropoff: "Destino",
    waterOnly: "Solo agua",
    yachtsLead: "Yates con capitán verificado, disponibles en tu zona.",
    nearby: "Cerca de ti",
    verified: "Capitán verificado",
    guests: "huéspedes",
    from: "Desde",
    away: "de ti",
    requestThis: "Solicitar este yate",
    useLocation: "Usar mi ubicación",
    requestLead: "Solicita un yate para commute, tour u ocasión especial.",
    kindsTrip: {
      commute: { title: "Commute", body: "Gánale a los puentes. Llega más rápido que en auto." },
      tour: { title: "Tour", body: "Sandbars, skyline y horas en el agua." },
      special: { title: "Ocasión especial", body: "Atardeceres, celebraciones, clientes a bordo." },
    },
    pickup: "Salida",
    dropoff: "Destino",
    when: "Cuándo",
    time: "Hora",
    who: "Huéspedes",
    yacht: "Yate",
    name: "Nombre completo",
    email: "Correo",
    phone: "Teléfono",
    continueTrip: "Ir a Tu Viaje",
    choosePickup: "Elige un origen",
    chooseDropoff: "Elige un destino",
    tripLead: "Verifica tu solicitud y la información de pago.",
    noTrip: "Aún no hay viaje. Solicita un yate para ver la tarifa y pagar.",
    requestCta: "Solicitar un yate",
    route: "Ruta",
    captain: "Capitán",
    fare: "Tarifa",
    boat: "Yate y combustible",
    ownerShare: "Dueño (40%)",
    captainShare: "Capitán (30%)",
    platformShare: "Kaenz (30%)",
    total: "Total",
    pay: "Pago",
    card: "Tarjeta",
    solana: "Solana",
    cardNumber: "Número de tarjeta",
    expiry: "Vence",
    cvc: "CVC",
    wallet: "Billetera Solana",
    payConfirm: "Pagar y confirmar viaje",
    paying: "Confirmando…",
    confirmed: "Viaje confirmado",
    statusRequested: "Solicitud enviada",
    statusConfirmed: "Capitán confirmó",
    statusUnderway: "En marcha",
    demoPay: "Pago demo — Kaenz no cobra tu tarjeta en esta vista previa.",
    crewLead: "Comparte con gente interesante en esta experiencia social.",
    goingTo: "Va a",
    joinCrew: "Unirme a esta crew",
    joined: "Ya estás en esta crew",
    likes: "me gusta",
    write: "Comparte una nota con la crew…",
    post: "Publicar",
    interests: "Le gusta",
    openMarketing: "Kaenz.com",
  },
} as const;

export function at(locale: Locale) {
  return appCopy[locale];
}

export type AppTab = "places" | "yachts" | "request" | "trip" | "crew";
