import type { Locale } from "./locale";

export const appCopy = {
  en: {
    appName: "Kaenz",
    location: "South Florida",
    tabs: {
      places: "Places",
      yachts: "Yachts",
      request: "Request",
      trip: "Your Trip",
      crew: "Crew",
    },
    placesLead: "Marinas, ports, and places to enjoy in Florida.",
    searchPlaces: "Search marinas, ports, sandbars…",
    kinds: { all: "All", marina: "Marinas", port: "Ports", place: "Places" },
    byYacht: "by yacht",
    byCar: "by car",
    setPickup: "Set pickup",
    setDropoff: "Set dropoff",
    waterOnly: "Water only",
    yachtsLead: "Yachts with a verified captain, available in your area.",
    nearby: "Near you",
    verified: "Captain verified",
    guests: "guests",
    from: "From",
    away: "away",
    requestThis: "Request this yacht",
    useLocation: "Use my location",
    requestLead: "Request a yacht for a commute, tour, or special occasion.",
    kindsTrip: {
      commute: { title: "Commute", body: "Beat the bridges. Get there faster than the car." },
      tour: { title: "Tour", body: "Sandbars, skyline, and hours on the water." },
      special: { title: "Special occasion", body: "Sunsets, celebrations, clients on deck." },
    },
    pickup: "Pickup",
    dropoff: "Destination",
    when: "When",
    time: "Time",
    who: "Guests",
    yacht: "Yacht",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    continueTrip: "Continue to Your Trip",
    choosePickup: "Choose a pickup",
    chooseDropoff: "Choose a destination",
    tripLead: "Verify your trip request and payment information.",
    noTrip: "No trip yet. Request a yacht to see your fare and pay.",
    requestCta: "Request a yacht",
    route: "Route",
    captain: "Captain",
    fare: "Fare",
    boat: "Yacht & fuel",
    ownerShare: "Owner (40%)",
    captainShare: "Captain (30%)",
    platformShare: "Kaenz (30%)",
    total: "Total",
    pay: "Payment",
    card: "Card",
    solana: "Solana",
    cardNumber: "Card number",
    expiry: "Expiry",
    cvc: "CVC",
    wallet: "Solana wallet",
    payConfirm: "Pay & confirm trip",
    paying: "Confirming…",
    confirmed: "Trip confirmed",
    statusRequested: "Request sent",
    statusConfirmed: "Captain confirmed",
    statusUnderway: "Underway",
    demoPay: "Demo checkout — Kaenz does not charge your card in this preview.",
    crewLead: "Share with interesting people in this social experience.",
    goingTo: "Going to",
    joinCrew: "Join this crew",
    joined: "You’re on this crew",
    likes: "likes",
    write: "Share a note with the crew…",
    post: "Post",
    interests: "Into",
    openMarketing: "Kaenz.com",
    errCard: "Check the card number.",
    errExp: "Use MM/YY.",
    errCvc: "Invalid CVC.",
    errWallet: "Solana wallet looks incomplete.",
    errConfirm: "Could not confirm. Try again.",
  },
  es: {
    appName: "Kaenz",
    location: "South Florida",
    tabs: {
      places: "Lugares",
      yachts: "Yates",
      request: "Solicitar",
      trip: "Tu Viaje",
      crew: "Tripulación",
    },
    placesLead: "Marinas, puertos y lugares para disfrutar en Florida.",
    searchPlaces: "Busca marinas, puertos, sandbars…",
    kinds: { all: "Todos", marina: "Marinas", port: "Puertos", place: "Lugares" },
    byYacht: "en yate",
    byCar: "en auto",
    setPickup: "Origen",
    setDropoff: "Destino",
    waterOnly: "Solo agua",
    yachtsLead: "Yates con capitán verificado, disponibles en tu zona.",
    nearby: "Cerca de ti",
    verified: "Capitán verificado",
    guests: "huéspedes",
    from: "Desde",
    away: "de ti",
    requestThis: "Solicitar este yate",
    useLocation: "Usar mi ubicación",
    requestLead: "Solicita un yate para commute, tour u ocasión especial.",
    kindsTrip: {
      commute: { title: "Commute", body: "Gánale a los puentes. Llega más rápido que en auto." },
      tour: { title: "Tour", body: "Sandbars, skyline y horas en el agua." },
      special: { title: "Ocasión especial", body: "Atardeceres, celebraciones, clientes a bordo." },
    },
    pickup: "Salida",
    dropoff: "Destino",
    when: "Cuándo",
    time: "Hora",
    who: "Huéspedes",
    yacht: "Yate",
    name: "Nombre completo",
    email: "Correo",
    phone: "Teléfono",
    continueTrip: "Ir a Tu Viaje",
    choosePickup: "Elige un origen",
    chooseDropoff: "Elige un destino",
    tripLead: "Verifica tu solicitud y la información de pago.",
    noTrip: "Aún no hay viaje. Solicita un yate para ver la tarifa y pagar.",
    requestCta: "Solicitar un yate",
    route: "Ruta",
    captain: "Capitán",
    fare: "Tarifa",
    boat: "Yate y combustible",
    ownerShare: "Dueño (40%)",
    captainShare: "Capitán (30%)",
    platformShare: "Kaenz (30%)",
    total: "Total",
    pay: "Pago",
    card: "Tarjeta",
    solana: "Solana",
    cardNumber: "Número de tarjeta",
    expiry: "Vence",
    cvc: "CVC",
    wallet: "Billetera Solana",
    payConfirm: "Pagar y confirmar viaje",
    paying: "Confirmando…",
    confirmed: "Viaje confirmado",
    statusRequested: "Solicitud enviada",
    statusConfirmed: "Capitán confirmó",
    statusUnderway: "En marcha",
    demoPay: "Pago demo — Kaenz no cobra tu tarjeta en esta vista previa.",
    crewLead: "Comparte con gente interesante en esta experiencia social.",
    goingTo: "Va a",
    joinCrew: "Unirme a esta crew",
    joined: "Ya estás en esta crew",
    likes: "me gusta",
    write: "Comparte una nota con la crew…",
    post: "Publicar",
    interests: "Le gusta",
    openMarketing: "Kaenz.com",
    errCard: "Revisa el número de tarjeta.",
    errExp: "Usa MM/AA.",
    errCvc: "CVC inválido.",
    errWallet: "Billetera Solana incompleta.",
    errConfirm: "No se pudo confirmar. Inténtalo de nuevo.",
  },
  fr: {
    appName: "Kaenz",
    location: "South Florida",
    tabs: {
      places: "Lieux",
      yachts: "Yachts",
      request: "Demander",
      trip: "Votre trajet",
      crew: "Équipage",
    },
    placesLead: "Marinas, ports et lieux à savourer en Floride.",
    searchPlaces: "Rechercher marinas, ports, sandbars…",
    kinds: { all: "Tous", marina: "Marinas", port: "Ports", place: "Lieux" },
    byYacht: "en yacht",
    byCar: "en voiture",
    setPickup: "Départ",
    setDropoff: "Arrivée",
    waterOnly: "Eau seulement",
    yachtsLead: "Yachts avec capitaine vérifié, disponibles près de vous.",
    nearby: "Près de vous",
    verified: "Capitaine vérifié",
    guests: "invités",
    from: "À partir de",
    away: "de vous",
    requestThis: "Demander ce yacht",
    useLocation: "Utiliser ma position",
    requestLead: "Demandez un yacht pour un trajet, une croisière ou une occasion spéciale.",
    kindsTrip: {
      commute: { title: "Trajet", body: "Gagnez sur les ponts. Arrivez plus vite qu’en voiture." },
      tour: { title: "Croisière", body: "Sandbars, skyline et des heures sur l’eau." },
      special: { title: "Occasion spéciale", body: "Couchers de soleil, célébrations, clients à bord." },
    },
    pickup: "Départ",
    dropoff: "Destination",
    when: "Quand",
    time: "Heure",
    who: "Invités",
    yacht: "Yacht",
    name: "Nom complet",
    email: "E-mail",
    phone: "Téléphone",
    continueTrip: "Aller à Votre trajet",
    choosePickup: "Choisissez un départ",
    chooseDropoff: "Choisissez une destination",
    tripLead: "Vérifiez votre demande et les informations de paiement.",
    noTrip: "Pas encore de trajet. Demandez un yacht pour voir le tarif et payer.",
    requestCta: "Demander un yacht",
    route: "Itinéraire",
    captain: "Capitaine",
    fare: "Tarif",
    boat: "Yacht et carburant",
    ownerShare: "Propriétaire (40 %)",
    captainShare: "Capitaine (30 %)",
    platformShare: "Kaenz (30 %)",
    total: "Total",
    pay: "Paiement",
    card: "Carte",
    solana: "Solana",
    cardNumber: "Numéro de carte",
    expiry: "Expiration",
    cvc: "CVC",
    wallet: "Portefeuille Solana",
    payConfirm: "Payer et confirmer le trajet",
    paying: "Confirmation…",
    confirmed: "Trajet confirmé",
    statusRequested: "Demande envoyée",
    statusConfirmed: "Capitaine confirmé",
    statusUnderway: "En route",
    demoPay: "Paiement démo — Kaenz ne débitera pas votre carte dans cet aperçu.",
    crewLead: "Partagez avec des personnes intéressantes dans cette expérience sociale.",
    goingTo: "Va vers",
    joinCrew: "Rejoindre cet équipage",
    joined: "Vous êtes dans cet équipage",
    likes: "j’aime",
    write: "Partagez une note avec l’équipage…",
    post: "Publier",
    interests: "Aime",
    openMarketing: "Kaenz.com",
    errCard: "Vérifiez le numéro de carte.",
    errExp: "Utilisez MM/AA.",
    errCvc: "CVC invalide.",
    errWallet: "Portefeuille Solana incomplet.",
    errConfirm: "Confirmation impossible. Réessayez.",
  },
  it: {
    appName: "Kaenz",
    location: "South Florida",
    tabs: {
      places: "Luoghi",
      yachts: "Yacht",
      request: "Richiedi",
      trip: "Il tuo viaggio",
      crew: "Equipaggio",
    },
    placesLead: "Marine, porti e luoghi da vivere in Florida.",
    searchPlaces: "Cerca marine, porti, sandbar…",
    kinds: { all: "Tutti", marina: "Marine", port: "Porti", place: "Luoghi" },
    byYacht: "in yacht",
    byCar: "in auto",
    setPickup: "Partenza",
    setDropoff: "Arrivo",
    waterOnly: "Solo acqua",
    yachtsLead: "Yacht con capitano verificato, disponibili nella tua zona.",
    nearby: "Vicino a te",
    verified: "Capitano verificato",
    guests: "ospiti",
    from: "Da",
    away: "da te",
    requestThis: "Richiedi questo yacht",
    useLocation: "Usa la mia posizione",
    requestLead: "Richiedi uno yacht per un tragitto, un tour o un’occasione speciale.",
    kindsTrip: {
      commute: { title: "Tragitto", body: "Batti i ponti. Arrivi più veloce che in auto." },
      tour: { title: "Tour", body: "Sandbar, skyline e ore in acqua." },
      special: { title: "Occasione speciale", body: "Tramonti, celebrazioni, clienti a bordo." },
    },
    pickup: "Partenza",
    dropoff: "Destinazione",
    when: "Quando",
    time: "Ora",
    who: "Ospiti",
    yacht: "Yacht",
    name: "Nome completo",
    email: "Email",
    phone: "Telefono",
    continueTrip: "Vai a Il tuo viaggio",
    choosePickup: "Scegli una partenza",
    chooseDropoff: "Scegli una destinazione",
    tripLead: "Verifica la richiesta e i dati di pagamento.",
    noTrip: "Nessun viaggio ancora. Richiedi uno yacht per vedere la tariffa e pagare.",
    requestCta: "Richiedi uno yacht",
    route: "Rotta",
    captain: "Capitano",
    fare: "Tariffa",
    boat: "Yacht e carburante",
    ownerShare: "Proprietario (40%)",
    captainShare: "Capitano (30%)",
    platformShare: "Kaenz (30%)",
    total: "Totale",
    pay: "Pagamento",
    card: "Carta",
    solana: "Solana",
    cardNumber: "Numero della carta",
    expiry: "Scadenza",
    cvc: "CVC",
    wallet: "Wallet Solana",
    payConfirm: "Paga e conferma il viaggio",
    paying: "Conferma in corso…",
    confirmed: "Viaggio confermato",
    statusRequested: "Richiesta inviata",
    statusConfirmed: "Capitano confermato",
    statusUnderway: "In navigazione",
    demoPay: "Pagamento demo — Kaenz non addebita la carta in questa anteprima.",
    crewLead: "Condividi con persone interessanti in questa esperienza sociale.",
    goingTo: "Va a",
    joinCrew: "Unisciti a questo equipaggio",
    joined: "Sei in questo equipaggio",
    likes: "mi piace",
    write: "Condividi una nota con l’equipaggio…",
    post: "Pubblica",
    interests: "Ama",
    openMarketing: "Kaenz.com",
    errCard: "Controlla il numero della carta.",
    errExp: "Usa MM/AA.",
    errCvc: "CVC non valido.",
    errWallet: "Wallet Solana incompleto.",
    errConfirm: "Conferma non riuscita. Riprova.",
  },
} as const;

export function at(locale: Locale) {
  return appCopy[locale];
}

export type AppTab = "places" | "yachts" | "request" | "trip" | "crew";
