import type { Locale } from "./locale";

export const appCopy = {
  en: {
    appName: "Kaenz",
    location: "Worldwide",
    tabs: {
      places: "Places",
      yachts: "Yachts",
      trip: "Your Trip",
      crew: "Crew",
      account: "Account",
    },
    placesLead:
      "Tap a marina or port on the map. Featured places are below, nearest first.",
    searchPlaces: "Search marinas, ports, sandbars…",
    kinds: { all: "All", marina: "Marinas", port: "Ports", place: "Places" },
    featuredPlaces: "Featured Places",
    featuredNearYou: "Near you",
    featuredSwipe: "Swipe sideways to see every place we created, nearest first.",
    locating: "Finding your location…",
    duration: "Duration (hours)",
    hoursUnit: "hours",
    fareHow:
      "Price from the local charter market, trip type, duration, yacht class, guests, and whether you leave now or later. Paid with Stripe.",
    stripePay: "Pay with Stripe",
    gratuityHint:
      "Optional 15–20% of the fare, paid directly to the captain. You can enter a custom percent up to 25%.",
    gratuityCustom: "Custom %",
    splitLead:
      "The fare splits: captain 30%, yacht owner 38%, pickup marina 3.5%, dropoff marina 3.5%, Kaenz 25%. Optional gratuity is extra and goes only to the captain.",
    payAfterQuote: "Pay this fare with Stripe to confirm the trip.",
    paidWithStripe: "Paid with Stripe",
    stripeCancel: "Checkout was canceled. You can pay when you are ready.",
    stripeMissing: "Stripe is not configured on this server.",
    payingStripe: "Opening Stripe…",
    captainPlusTip: "Captain + gratuity",
    featured: {
      sandbar: "Sandbars and Anchors",
      beach: "Beaches and Parks",
      dine: "Dock & Dine Restaurants",
      scenic: "Mansions, Islands, and Scenic Cruises",
    },
    byYacht: "by yacht",
    byCar: "by car",
    setPickup: "Set pickup",
    setDropoff: "Set dropoff",
    waterOnly: "Water only",
    yachtsLead:
      "Yachts with a verified captain, classified Fast, Small, or Luxurious. Capacity is listed. Price is calculated on your request.",
    nearby: "Near you",
    verified: "Captain verified",
    guests: "guests",
    maxGuests: "Max guests",
    classAll: "All",
    from: "From",
    away: "away",
    requestThis: "Request this yacht",
    useLocation: "Use my location",
    requestLead: "Request a yacht for a commute, tour, or special occasion.",
    kindsTrip: {
      commute: { title: "Commute", body: "Under 2 hours. Beat the bridges, faster than the car." },
      tour: { title: "Tour", body: "3–6 hours. Sandbars, skyline, time on the water." },
      special: { title: "Special occasion", body: "4–8 hours. Sunsets, celebrations, clients on deck." },
    },
    whenNow: "Now",
    whenSchedule: "Schedule",
    whenNowLead: "Leave as soon as a captain is ready.",
    whenScheduleLead: "Pick a date and time.",
    leavingNow: "Leaving now",
    marketBased: "Local market",
    durationRange: {
      commute: "Under 2 hours (1–1.5 h)",
      tour: "3–6 hours",
      special: "4–8 hours",
    },
    pickup: "Pickup",
    dropoff: "Destination",
    when: "When",
    time: "Time",
    who: "Guests",
    yacht: "Yacht",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    continueTrip: "Request this trip",
    choosePickup: "Choose a pickup",
    chooseDropoff: "Choose a destination",
    searchPickup: "Type a marina or place…",
    searchDropoff: "Type a destination…",
    noPlaceMatch: "No marina or place matches. Try another word.",
    suggestedNearYou: "Near you",
    tripLead: "Request a yacht and follow the trip through to rating.",
    noTrip: "No trip yet. Request a yacht to see your fare and pay.",
    requestCta: "Request a yacht",
    route: "Route",
    captain: "Captain",
    fare: "Fare",
    boat: "Yacht & fuel",
    ownerShare: "Owner (38%)",
    captainShare: "Captain (30%)",
    marinaPickupShare: "Pickup marina (3.5%)",
    marinaDropoffShare: "Dropoff marina (3.5%)",
    marinaRoundShare: "Marina round trip (7%)",
    platformShare: "Kaenz (25%)",
    gratuity: "Optional gratuity",
    gratuityNone: "No gratuity",
    total: "Total",
    pay: "Payment",
    card: "Card",
    solana: "Solana",
    cardNumber: "Card number",
    expiry: "Expiry",
    cvc: "CVC",
    wallet: "Solana wallet",
    payConfirm: "Pay & confirm trip",
    paying: "Confirming…",
    confirmed: "Trip confirmed",
    statusRequested: "Request sent",
    statusConfirmed: "Captain confirmed",
    statusUnderway: "Underway",
    tripSteps: {
      requested: "Requested",
      approved: "Captain approved",
      waiting: "Waiting at marina",
      underway: "Traveling",
      paid: "Paid",
      rated: "Rated",
    },
    tripStepLead: {
      requested: "The captain is reviewing your request.",
      approved: "The captain accepted. Go to the pickup marina.",
      waiting: "The yacht is at the dock. Board when you are ready.",
      underway: "Live track of your yacht and the crew on board.",
      paid: "Payment received. Rate your experience.",
      rated: "Thanks for sailing with Kaenz.",
    },
    onboard: "Crew on board",
    onboardYou: "You",
    rateTrip: "Rate this trip",
    ratedAs: "You rated this trip",
    stars: "stars",
    arrivedPay: "You arrived. Pay the quoted fare with Stripe if you have not already.",
    payTrip: "Pay trip",
    demoPay:
      "Stripe Checkout charges the algorithm fare plus optional captain gratuity. The fare then splits to the captain, owner, marinas, and Kaenz.",
    crewLead: "Share with interesting people in this social experience.",
    goingTo: "Going to",
    joinCrew: "Join this crew",
    joined: "You’re on this crew",
    likes: "likes",
    write: "Share a note with the crew…",
    post: "Post",
    interests: "Into",
    openMarketing: "Kaenz.com",
    errCard: "Check the card number.",
    errExp: "Use MM/YY.",
    errCvc: "Invalid CVC.",
    errWallet: "Solana wallet looks incomplete.",
    errConfirm: "Could not confirm. Try again.",
    account: {
      lead: "Save your details once. Requests and payments use them automatically.",
      personal: "Personal details",
      payments: "Payment methods",
      paymentsLead:
        "Kaenz stores the last four digits and expiry only. CVC is never saved.",
      fullName: "Full name",
      email: "Email",
      phone: "Phone number",
      creditCard: "Credit card",
      debitCard: "Debit card",
      solanaWallet: "Solana wallet",
      cardNumber: "Card number",
      expiry: "Expiry",
      replace: "Replace",
      remove: "Remove",
      keep: "Keep saved card",
      walletPlaceholder: "Your Solana address",
      save: "Save account",
      saving: "Saving…",
      savedOk: "Saved. Requests will use these details.",
      saveError: "Could not save. Try again.",
      errName: "Enter your full name.",
      errEmail: "Enter a valid email.",
      errPhone: "Enter a valid phone number.",
      errCredit: "Check the credit card number and expiry.",
      errDebit: "Check the debit card number and expiry.",
      errWallet: "Solana wallet looks incomplete.",
      logout: "Log out",
      incomplete: "Add your name and email in Account before requesting a yacht.",
      goAccount: "Go to your account",
      usingAccount: "Using your saved account details.",
      editAccount: "Edit account",
      payWith: "Pay with",
      payCredit: "Credit card",
      payDebit: "Debit card",
      paySolana: "Solana wallet",
      noPayMethod:
        "Add a credit card, debit card, or Solana wallet in your account to pay.",
      role: "Role",
      roleLead: "Choose the role that applies to you.",
      roles: {
        customer: {
          title: "Customer",
          body: "Request yachts, pay, and join the crew.",
        },
        owner: {
          title: "Owner",
          body: "List yachts and earn 38% of each fare.",
        },
        captain: {
          title: "Captain",
          body: "Run trips and receive 30% plus optional gratuity.",
        },
      },
      instagram: "Instagram",
      instagramPlaceholder: "@username",
      errInstagram: "Enter a valid Instagram username.",
      city: "City",
      cityFromGps: "Set from your GPS location.",
      locatingCity: "Finding your city…",
      cityDenied: "Allow location to set your city.",
      useGps: "Use my GPS",
      trips: "Your trips",
      tripsLead: "Calendar of your trips and photos from the experience.",
      noTrips: "No trips yet. Request a yacht and they will appear here.",
      noTripsDay: "No trips on this day.",
      addPhotos: "Add photos",
      photos: "Photos",
      photoLimit: "Up to 8 photos per trip.",
      photoError: "Could not save those photos. Try fewer or smaller images.",
      prevMonth: "Previous month",
      nextMonth: "Next month",
    },
    addMarina: {
      cta: "Add a marina or port",
      title: "Add a marina or port",
      lead: "Partners list a marina or port. You earn 3.5% of the client price each time it is used, or 7% if the yacht leaves and returns to the same place.",
      cancel: "Cancel",
      kind: "Type",
      marina: "Marina",
      port: "Port",
      name: "Marina or port name",
      lat: "Latitude",
      lng: "Longitude",
      address: "Address",
      region: "Region",
      dockmaster: "Dockmaster name",
      phone: "Phone number",
      website: "Website",
      wallet: "Solana wallet",
      shareNote: "3.5% of the client price each time your marina is used. 7% if pickup and dropoff are the same place.",
      submit: "List this marina",
      sending: "Saving…",
      needAuth: "Log in to list a marina.",
      needWallet: "Enter a valid Solana wallet.",
      needCoords: "Enter a valid latitude and longitude.",
      needUrl: "Enter a valid website.",
      error: "Could not add the marina. Try again.",
      listed: "Listed",
      partner: "Partner",
      fee: "3.5–7%",
    },
    addYacht: {
      cta: "Add a yacht",
      title: "Add a yacht",
      lead: "Owner, yacht, and captain. Documents stay private; photos appear on the listing.",
      cancel: "Cancel",
      owner: "1. Owner",
      ownerShare: "Receives 38% of the total payment.",
      ownerName: "Owner full name",
      ownerId: "Owner ID photo",
      ownerWallet: "Owner Solana wallet",
      yachtSection: "2. Yacht",
      yachtName: "Yacht name",
      photos: "Yacht photos (up to 5)",
      hin: "HIN",
      capacity: "Passenger capacity",
      traits: "Classification",
      luxurious: "Luxurious",
      fast: "Fast",
      small: "Small",
      homePort: "Home port or main marina",
      captainSection: "3. Captain",
      captainShare: "Receives 30% of the total payment + optional gratuity.",
      captainName: "Captain full name",
      captainId: "Captain ID document",
      mmc: "Merchant Mariner Credential (MMC)",
      captainPhoto: "Captain photo",
      languages: "Languages",
      langEn: "English",
      langEs: "Spanish",
      langPt: "Portuguese",
      langFr: "French",
      region: "Available region",
      captainWallet: "Captain Solana wallet",
      submit: "List this yacht",
      sending: "Saving…",
      needAuth: "Log in to list a yacht.",
      needOwnerId: "Upload an owner ID photo.",
      needPhotos: "Upload 1 to 5 yacht photos.",
      needHin: "Enter a valid HIN.",
      needTrait: "Pick at least one characteristic.",
      needCaptainId: "Upload a captain ID document.",
      needMmc: "Upload the Merchant Mariner Credential.",
      needCaptainPhoto: "Upload a captain photo.",
      needLanguage: "Pick at least one language.",
      needWallet: "Enter a valid Solana wallet.",
      error: "Could not add the yacht. Try again.",
      listed: "Listed",
    },
  },
  es: {
    appName: "Kaenz",
    location: "En el mundo",
    tabs: {
      places: "Lugares",
      yachts: "Yates",
      trip: "Tu Viaje",
      crew: "Tripulación",
      account: "Cuenta",
    },
    placesLead:
      "Toca una marina o puerto en el mapa. Los lugares destacados están abajo, los más cercanos primero.",
    searchPlaces: "Busca marinas, puertos, sandbars…",
    kinds: { all: "Todos", marina: "Marinas", port: "Puertos", place: "Lugares" },
    featuredPlaces: "Lugares destacados",
    featuredNearYou: "Cerca de ti",
    featuredSwipe: "Desliza de lado para ver todos los lugares que creamos, los más cercanos primero.",
    locating: "Buscando tu ubicación…",
    duration: "Duración (horas)",
    hoursUnit: "horas",
    fareHow:
      "El precio sale del mercado local de chárter, tipo de viaje, duración, clase de yate, pasajeros y si sales ahora o agendado. Se cobra con Stripe.",
    stripePay: "Pagar con Stripe",
    gratuityHint:
      "Opcional 15–20% de la tarifa, pagada directo al capitán. Puedes ingresar un porcentaje propio hasta 25%.",
    gratuityCustom: "% personalizado",
    splitLead:
      "La tarifa se reparte: capitán 30%, dueño del yate 38%, marina de origen 3.5%, marina de destino 3.5%, Kaenz 25%. La gratificación es extra y va solo al capitán.",
    payAfterQuote: "Paga esta tarifa con Stripe para confirmar el viaje.",
    paidWithStripe: "Pagado con Stripe",
    stripeCancel: "Cancelaste el checkout. Puedes pagar cuando quieras.",
    stripeMissing: "Stripe no está configurado en este servidor.",
    payingStripe: "Abriendo Stripe…",
    captainPlusTip: "Capitán + gratificación",
    featured: {
      sandbar: "Sandbars y anclajes",
      beach: "Playas y parques",
      dine: "Restaurantes Dock & Dine",
      scenic: "Mansiones, islas y cruceros escénicos",
    },
    byYacht: "en yate",
    byCar: "en auto",
    setPickup: "Origen",
    setDropoff: "Destino",
    waterOnly: "Solo agua",
    yachtsLead:
      "Yates con capitán verificado, clasificados Fast, Small o Luxurious. Se indica la capacidad. El precio se calcula en la solicitud.",
    nearby: "Cerca de ti",
    verified: "Capitán verificado",
    guests: "huéspedes",
    maxGuests: "Capacidad máxima",
    classAll: "Todos",
    from: "Desde",
    away: "de ti",
    requestThis: "Solicitar este yate",
    useLocation: "Usar mi ubicación",
    requestLead: "Solicita un yate para commute, tour u ocasión especial.",
    kindsTrip: {
      commute: { title: "Commute", body: "Menos de 2 horas. Gánale a los puentes, más rápido que el auto." },
      tour: { title: "Tour", body: "3–6 horas. Sandbars, skyline y tiempo en el agua." },
      special: { title: "Ocasión especial", body: "4–8 horas. Atardeceres, celebraciones, clientes a bordo." },
    },
    whenNow: "Now",
    whenSchedule: "Agendar",
    whenNowLead: "Salir en cuanto un capitán esté listo.",
    whenScheduleLead: "Elige fecha y hora.",
    leavingNow: "Saliendo ahora",
    marketBased: "Mercado local",
    durationRange: {
      commute: "Menos de 2 horas (1–1.5 h)",
      tour: "3–6 horas",
      special: "4–8 horas",
    },
    pickup: "Salida",
    dropoff: "Destino",
    when: "Cuándo",
    time: "Hora",
    who: "Huéspedes",
    yacht: "Yate",
    name: "Nombre completo",
    email: "Correo",
    phone: "Teléfono",
    continueTrip: "Solicitar este viaje",
    choosePickup: "Elige un origen",
    chooseDropoff: "Elige un destino",
    searchPickup: "Escribe una marina o lugar…",
    searchDropoff: "Escribe un destino…",
    noPlaceMatch: "No hay marina o lugar que coincida. Prueba otra palabra.",
    suggestedNearYou: "Cerca de ti",
    tripLead: "Solicita un yate y sigue el viaje hasta la evaluación.",
    noTrip: "Aún no hay viaje. Solicita un yate para ver la tarifa y pagar.",
    requestCta: "Solicitar un yate",
    route: "Ruta",
    captain: "Capitán",
    fare: "Tarifa",
    boat: "Yate y combustible",
    ownerShare: "Dueño (38%)",
    captainShare: "Capitán (30%)",
    marinaPickupShare: "Marina de origen (3.5%)",
    marinaDropoffShare: "Marina de destino (3.5%)",
    marinaRoundShare: "Marina ida y vuelta (7%)",
    platformShare: "Kaenz (25%)",
    gratuity: "Gratificación opcional",
    gratuityNone: "Sin gratificación",
    total: "Total",
    pay: "Pago",
    card: "Tarjeta",
    solana: "Solana",
    cardNumber: "Número de tarjeta",
    expiry: "Vence",
    cvc: "CVC",
    wallet: "Billetera Solana",
    payConfirm: "Pagar y confirmar viaje",
    paying: "Confirmando…",
    confirmed: "Viaje confirmado",
    statusRequested: "Solicitud enviada",
    statusConfirmed: "Capitán confirmó",
    statusUnderway: "En marcha",
    tripSteps: {
      requested: "Solicitado",
      approved: "Aprobado por el Capitán",
      waiting: "Esperando en Marina",
      underway: "Viajando",
      paid: "Pagado",
      rated: "Evaluado",
    },
    tripStepLead: {
      requested: "El capitán está revisando tu solicitud.",
      approved: "El capitán aceptó. Ve a la marina de salida.",
      waiting: "El yate está en el muelle. Aborda cuando estés listo.",
      underway: "Seguimiento en vivo del yate y la tripulación a bordo.",
      paid: "Pago recibido. Evalúa tu experiencia.",
      rated: "Gracias por navegar con Kaenz.",
    },
    onboard: "Tripulación a bordo",
    onboardYou: "Tú",
    rateTrip: "Evalúa este viaje",
    ratedAs: "Evaluaste este viaje",
    stars: "estrellas",
    arrivedPay: "Llegaste. Paga la tarifa con Stripe si aún no lo hiciste.",
    payTrip: "Pagar viaje",
    demoPay:
      "Stripe Checkout cobra la tarifa del algoritmo más la gratificación opcional al capitán. Luego se reparte entre capitán, dueño, marinas y Kaenz.",
    crewLead: "Comparte con gente interesante en esta experiencia social.",
    goingTo: "Va a",
    joinCrew: "Unirme a esta crew",
    joined: "Ya estás en esta crew",
    likes: "me gusta",
    write: "Comparte una nota con la crew…",
    post: "Publicar",
    interests: "Le gusta",
    openMarketing: "Kaenz.com",
    errCard: "Revisa el número de tarjeta.",
    errExp: "Usa MM/AA.",
    errCvc: "CVC inválido.",
    errWallet: "Billetera Solana incompleta.",
    errConfirm: "No se pudo confirmar. Inténtalo de nuevo.",
    account: {
      lead: "Guarda tus datos una vez. Las solicitudes y los pagos los usan automáticamente.",
      personal: "Datos personales",
      payments: "Métodos de pago",
      paymentsLead:
        "Kaenz guarda solo los últimos cuatro dígitos y la fecha de vencimiento. El CVC no se almacena.",
      fullName: "Nombre completo",
      email: "Correo",
      phone: "Teléfono",
      creditCard: "Tarjeta de crédito",
      debitCard: "Tarjeta de débito",
      solanaWallet: "Wallet Solana",
      cardNumber: "Número de tarjeta",
      expiry: "Vence",
      replace: "Cambiar",
      remove: "Quitar",
      keep: "Conservar tarjeta guardada",
      walletPlaceholder: "Tu dirección Solana",
      save: "Guardar cuenta",
      saving: "Guardando…",
      savedOk: "Guardado. Las solicitudes usarán estos datos.",
      saveError: "No se pudo guardar. Inténtalo de nuevo.",
      errName: "Escribe tu nombre completo.",
      errEmail: "Escribe un correo válido.",
      errPhone: "Escribe un teléfono válido.",
      errCredit: "Revisa el número y el vencimiento de la tarjeta de crédito.",
      errDebit: "Revisa el número y el vencimiento de la tarjeta de débito.",
      errWallet: "La wallet Solana se ve incompleta.",
      logout: "Cerrar sesión",
      incomplete: "Agrega tu nombre y correo en Cuenta antes de solicitar un yate.",
      goAccount: "Ir a tu cuenta",
      usingAccount: "Usando los datos de tu cuenta.",
      editAccount: "Editar cuenta",
      payWith: "Pagar con",
      payCredit: "Tarjeta de crédito",
      payDebit: "Tarjeta de débito",
      paySolana: "Wallet Solana",
      noPayMethod:
        "Agrega una tarjeta de crédito, débito o wallet Solana en tu cuenta para pagar.",
      role: "Rol",
      roleLead: "Elige el rol que te corresponde.",
      roles: {
        customer: {
          title: "Customer",
          body: "Solicita yates, paga y únete a la crew.",
        },
        owner: {
          title: "Owner",
          body: "Publica yates y gana el 38% de cada tarifa.",
        },
        captain: {
          title: "Captain",
          body: "Conduce viajes y recibe el 30% más gratificación opcional.",
        },
      },
      instagram: "Instagram",
      instagramPlaceholder: "@usuario",
      errInstagram: "Escribe un usuario de Instagram válido.",
      city: "Ciudad",
      cityFromGps: "Se determina con tu ubicación GPS.",
      locatingCity: "Buscando tu ciudad…",
      cityDenied: "Permite la ubicación para fijar tu ciudad.",
      useGps: "Usar mi GPS",
      trips: "Tus viajes",
      tripsLead: "Calendario de tus viajes y fotos de esa experiencia.",
      noTrips: "Aún no hay viajes. Solicita un yate y aparecerán aquí.",
      noTripsDay: "No hay viajes este día.",
      addPhotos: "Agregar fotos",
      photos: "Fotos",
      photoLimit: "Hasta 8 fotos por viaje.",
      photoError: "No se pudieron guardar esas fotos. Prueba con menos o más livianas.",
      prevMonth: "Mes anterior",
      nextMonth: "Mes siguiente",
    },
    addMarina: {
      cta: "Agregar marina o puerto",
      title: "Agregar marina o puerto",
      lead: "Los partners publican su marina o puerto. Ganan el 3.5% del precio del cliente cada vez que se usa, o el 7% si el yate sale y llega al mismo lugar.",
      cancel: "Cancelar",
      kind: "Tipo",
      marina: "Marina",
      port: "Puerto",
      name: "Nombre de la marina o puerto",
      lat: "Latitud",
      lng: "Longitud",
      address: "Dirección",
      region: "Región",
      dockmaster: "Nombre del dockmaster",
      phone: "Teléfono",
      website: "Sitio web",
      wallet: "Wallet Solana",
      shareNote: "3.5% del precio del cliente cada vez que se usa tu marina. 7% si origen y destino son el mismo lugar.",
      submit: "Publicar esta marina",
      sending: "Guardando…",
      needAuth: "Entra para publicar una marina.",
      needWallet: "Ingresa una wallet Solana válida.",
      needCoords: "Ingresa latitud y longitud válidas.",
      needUrl: "Ingresa un sitio web válido.",
      error: "No se pudo agregar la marina. Inténtalo de nuevo.",
      listed: "Publicada",
      partner: "Partner",
      fee: "3.5–7%",
    },
    addYacht: {
      cta: "Agregar un yate",
      title: "Agregar un yate",
      lead: "Dueño, yate y capitán. Los documentos quedan privados; las fotos salen en el listado.",
      cancel: "Cancelar",
      owner: "1. Dueño",
      ownerShare: "Recibe el 38% del pago total.",
      ownerName: "Nombre completo del dueño",
      ownerId: "Foto de ID del dueño",
      ownerWallet: "Wallet Solana del dueño",
      yachtSection: "2. Yate",
      yachtName: "Nombre del yate",
      photos: "Fotos del yate (hasta 5)",
      hin: "HIN",
      capacity: "Capacidad de pasajeros",
      traits: "Clasificación",
      luxurious: "Luxurious",
      fast: "Fast",
      small: "Small",
      homePort: "Home port o marina principal",
      captainSection: "3. Capitán",
      captainShare: "Recibe el 30% del pago total + gratificación opcional.",
      captainName: "Nombre completo del capitán",
      captainId: "Documento de ID del capitán",
      mmc: "Merchant Mariner Credential (MMC)",
      captainPhoto: "Foto del capitán",
      languages: "Idiomas",
      langEn: "Inglés",
      langEs: "Español",
      langPt: "Portugués",
      langFr: "Francés",
      region: "Región disponible",
      captainWallet: "Wallet Solana del capitán",
      submit: "Publicar este yate",
      sending: "Guardando…",
      needAuth: "Entra para agregar un yate.",
      needOwnerId: "Sube la foto de ID del dueño.",
      needPhotos: "Sube de 1 a 5 fotos del yate.",
      needHin: "Ingresa un HIN válido.",
      needTrait: "Elige al menos una característica.",
      needCaptainId: "Sube el ID del capitán.",
      needMmc: "Sube el Merchant Mariner Credential.",
      needCaptainPhoto: "Sube la foto del capitán.",
      needLanguage: "Elige al menos un idioma.",
      needWallet: "Ingresa una wallet Solana válida.",
      error: "No se pudo agregar el yate. Inténtalo de nuevo.",
      listed: "Publicado",
    },
  },
  fr: {
    appName: "Kaenz",
    location: "Dans le monde",
    tabs: {
      places: "Lieux",
      yachts: "Yachts",
      trip: "Votre trajet",
      crew: "Équipage",
      account: "Compte",
    },
    placesLead:
      "Touchez une marina ou un port sur la carte. Les lieux en vedette sont en dessous, les plus proches d’abord.",
    searchPlaces: "Rechercher marinas, ports, sandbars…",
    kinds: { all: "Tous", marina: "Marinas", port: "Ports", place: "Lieux" },
    featuredPlaces: "Lieux en vedette",
    featuredNearYou: "Près de vous",
    featuredSwipe: "Faites glisser pour voir tous les lieux créés, les plus proches d’abord.",
    locating: "Recherche de votre position…",
    duration: "Durée (heures)",
    hoursUnit: "heures",
    fareHow:
      "Prix selon le marché local du charter, le type de voyage, la durée, la classe du yacht, les passagers et le départ immédiat ou planifié. Paiement Stripe.",
    stripePay: "Payer avec Stripe",
    gratuityHint:
      "Optionnel 15–20 % du tarif, versé directement au capitaine. Vous pouvez saisir un pourcentage personnalisé jusqu’à 25 %.",
    gratuityCustom: "% personnalisé",
    splitLead:
      "Répartition : capitaine 30 %, propriétaire 38 %, marina de départ 3,5 %, marina d’arrivée 3,5 %, Kaenz 25 %. Le pourboire est en plus et va uniquement au capitaine.",
    payAfterQuote: "Payez ce tarif avec Stripe pour confirmer le trajet.",
    paidWithStripe: "Payé avec Stripe",
    stripeCancel: "Paiement annulé. Vous pourrez payer plus tard.",
    stripeMissing: "Stripe n’est pas configuré sur ce serveur.",
    payingStripe: "Ouverture de Stripe…",
    captainPlusTip: "Capitaine + pourboire",
    featured: {
      sandbar: "Sandbars et mouillages",
      beach: "Plages et parcs",
      dine: "Restaurants Dock & Dine",
      scenic: "Villas, îles et croisières",
    },
    byYacht: "en yacht",
    byCar: "en voiture",
    setPickup: "Départ",
    setDropoff: "Arrivée",
    waterOnly: "Eau seulement",
    yachtsLead:
      "Yachts avec capitaine vérifié, classés Fast, Small ou Luxurious. La capacité est indiquée. Le prix se calcule sur votre demande.",
    nearby: "Près de vous",
    verified: "Capitaine vérifié",
    guests: "invités",
    maxGuests: "Capacité max",
    classAll: "Tous",
    from: "À partir de",
    away: "de vous",
    requestThis: "Demander ce yacht",
    useLocation: "Utiliser ma position",
    requestLead: "Demandez un yacht pour un trajet, une croisière ou une occasion spéciale.",
    kindsTrip: {
      commute: { title: "Trajet", body: "Moins de 2 heures. Gagnez sur les ponts, plus vite qu’en voiture." },
      tour: { title: "Croisière", body: "3–6 heures. Sandbars, skyline, du temps sur l’eau." },
      special: { title: "Occasion spéciale", body: "4–8 heures. Couchers de soleil, célébrations, clients à bord." },
    },
    whenNow: "Now",
    whenSchedule: "Planifier",
    whenNowLead: "Partez dès qu’un capitaine est prêt.",
    whenScheduleLead: "Choisissez une date et une heure.",
    leavingNow: "Départ immédiat",
    marketBased: "Marché local",
    durationRange: {
      commute: "Moins de 2 heures (1–1,5 h)",
      tour: "3–6 heures",
      special: "4–8 heures",
    },
    pickup: "Départ",
    dropoff: "Destination",
    when: "Quand",
    time: "Heure",
    who: "Invités",
    yacht: "Yacht",
    name: "Nom complet",
    email: "E-mail",
    phone: "Téléphone",
    continueTrip: "Demander ce trajet",
    choosePickup: "Choisissez un départ",
    chooseDropoff: "Choisissez une destination",
    searchPickup: "Tapez une marina ou un lieu…",
    searchDropoff: "Tapez une destination…",
    noPlaceMatch: "Aucune marina ou lieu ne correspond. Essayez un autre mot.",
    suggestedNearYou: "Près de vous",
    tripLead: "Demandez un yacht et suivez le trajet jusqu’à l’évaluation.",
    noTrip: "Pas encore de trajet. Demandez un yacht pour voir le tarif et payer.",
    requestCta: "Demander un yacht",
    route: "Itinéraire",
    captain: "Capitaine",
    fare: "Tarif",
    boat: "Yacht et carburant",
    ownerShare: "Propriétaire (38 %)",
    captainShare: "Capitaine (30 %)",
    marinaPickupShare: "Marina de départ (3,5 %)",
    marinaDropoffShare: "Marina d’arrivée (3,5 %)",
    marinaRoundShare: "Marina aller-retour (7 %)",
    platformShare: "Kaenz (25 %)",
    gratuity: "Pourboire optionnel",
    gratuityNone: "Sans pourboire",
    total: "Total",
    pay: "Paiement",
    card: "Carte",
    solana: "Solana",
    cardNumber: "Numéro de carte",
    expiry: "Expiration",
    cvc: "CVC",
    wallet: "Portefeuille Solana",
    payConfirm: "Payer et confirmer le trajet",
    paying: "Confirmation…",
    confirmed: "Trajet confirmé",
    statusRequested: "Demande envoyée",
    statusConfirmed: "Capitaine confirmé",
    statusUnderway: "En route",
    tripSteps: {
      requested: "Demandé",
      approved: "Approuvé par le capitaine",
      waiting: "En attente à la marina",
      underway: "En voyage",
      paid: "Payé",
      rated: "Évalué",
    },
    tripStepLead: {
      requested: "Le capitaine examine votre demande.",
      approved: "Le capitaine a accepté. Rendez-vous à la marina.",
      waiting: "Le yacht est à quai. Embarquez quand vous êtes prêt.",
      underway: "Suivi en direct du yacht et de l’équipage à bord.",
      paid: "Paiement reçu. Évaluez votre expérience.",
      rated: "Merci d’avoir navigué avec Kaenz.",
    },
    onboard: "Équipage à bord",
    onboardYou: "Vous",
    rateTrip: "Noter ce trajet",
    ratedAs: "Vous avez noté ce trajet",
    stars: "étoiles",
    arrivedPay: "Vous êtes arrivé. Payez le tarif Stripe si ce n’est pas déjà fait.",
    payTrip: "Payer le trajet",
    demoPay:
      "Stripe Checkout encaisse le tarif de l’algorithme plus le pourboire capitaine optionnel. Le tarif est ensuite réparti entre capitaine, propriétaire, marinas et Kaenz.",
    crewLead: "Partagez avec des personnes intéressantes dans cette expérience sociale.",
    goingTo: "Va vers",
    joinCrew: "Rejoindre cet équipage",
    joined: "Vous êtes dans cet équipage",
    likes: "j’aime",
    write: "Partagez une note avec l’équipage…",
    post: "Publier",
    interests: "Aime",
    openMarketing: "Kaenz.com",
    errCard: "Vérifiez le numéro de carte.",
    errExp: "Utilisez MM/AA.",
    errCvc: "CVC invalide.",
    errWallet: "Portefeuille Solana incomplet.",
    errConfirm: "Confirmation impossible. Réessayez.",
    account: {
      lead: "Enregistrez vos informations une fois. Les demandes et paiements les utilisent automatiquement.",
      personal: "Informations personnelles",
      payments: "Moyens de paiement",
      paymentsLead:
        "Kaenz conserve uniquement les quatre derniers chiffres et la date d’expiration. Le CVC n’est jamais enregistré.",
      fullName: "Nom complet",
      email: "E-mail",
      phone: "Téléphone",
      creditCard: "Carte de crédit",
      debitCard: "Carte de débit",
      solanaWallet: "Portefeuille Solana",
      cardNumber: "Numéro de carte",
      expiry: "Expiration",
      replace: "Remplacer",
      remove: "Retirer",
      keep: "Conserver la carte enregistrée",
      walletPlaceholder: "Votre adresse Solana",
      save: "Enregistrer le compte",
      saving: "Enregistrement…",
      savedOk: "Enregistré. Les demandes utiliseront ces informations.",
      saveError: "Impossible d’enregistrer. Réessayez.",
      errName: "Entrez votre nom complet.",
      errEmail: "Entrez un e-mail valide.",
      errPhone: "Entrez un numéro de téléphone valide.",
      errCredit: "Vérifiez le numéro et l’expiration de la carte de crédit.",
      errDebit: "Vérifiez le numéro et l’expiration de la carte de débit.",
      errWallet: "Le portefeuille Solana semble incomplet.",
      logout: "Se déconnecter",
      incomplete: "Ajoutez votre nom et e-mail dans Compte avant de demander un yacht.",
      goAccount: "Aller à votre compte",
      usingAccount: "Utilisation des informations de votre compte.",
      editAccount: "Modifier le compte",
      payWith: "Payer avec",
      payCredit: "Carte de crédit",
      payDebit: "Carte de débit",
      paySolana: "Portefeuille Solana",
      noPayMethod:
        "Ajoutez une carte de crédit, une carte de débit ou un portefeuille Solana dans votre compte pour payer.",
      role: "Rôle",
      roleLead: "Choisissez le rôle qui vous correspond.",
      roles: {
        customer: {
          title: "Customer",
          body: "Demandez des yachts, payez et rejoignez l’équipage.",
        },
        owner: {
          title: "Owner",
          body: "Publiez des yachts et gagnez 38 % de chaque tarif.",
        },
        captain: {
          title: "Captain",
          body: "Assurez les trajets et recevez 30 % plus un pourboire optionnel.",
        },
      },
      instagram: "Instagram",
      instagramPlaceholder: "@identifiant",
      errInstagram: "Entrez un identifiant Instagram valide.",
      city: "Ville",
      cityFromGps: "Déterminée à partir de votre GPS.",
      locatingCity: "Recherche de votre ville…",
      cityDenied: "Autorisez la localisation pour définir votre ville.",
      useGps: "Utiliser mon GPS",
      trips: "Vos trajets",
      tripsLead: "Calendrier de vos trajets et photos de l’expérience.",
      noTrips: "Pas encore de trajet. Demandez un yacht et ils apparaîtront ici.",
      noTripsDay: "Aucun trajet ce jour-là.",
      addPhotos: "Ajouter des photos",
      photos: "Photos",
      photoLimit: "Jusqu’à 8 photos par trajet.",
      photoError: "Impossible d’enregistrer ces photos. Essayez moins d’images ou plus légères.",
      prevMonth: "Mois précédent",
      nextMonth: "Mois suivant",
    },
    addMarina: {
      cta: "Ajouter une marina ou un port",
      title: "Ajouter une marina ou un port",
      lead: "Les partenaires publient leur marina ou port. Ils reçoivent 3,5 % du prix client à chaque usage, ou 7 % si le yacht part et revient au même endroit.",
      cancel: "Annuler",
      kind: "Type",
      marina: "Marina",
      port: "Port",
      name: "Nom de la marina ou du port",
      lat: "Latitude",
      lng: "Longitude",
      address: "Adresse",
      region: "Région",
      dockmaster: "Nom du dockmaster",
      phone: "Téléphone",
      website: "Site web",
      wallet: "Wallet Solana",
      shareNote: "3,5 % du prix client chaque fois que votre marina est utilisée. 7 % si départ et arrivée sont le même lieu.",
      submit: "Publier cette marina",
      sending: "Enregistrement…",
      needAuth: "Connectez-vous pour publier une marina.",
      needWallet: "Entrez un wallet Solana valide.",
      needCoords: "Entrez une latitude et une longitude valides.",
      needUrl: "Entrez un site web valide.",
      error: "Impossible d’ajouter la marina. Réessayez.",
      listed: "Publiée",
      partner: "Partenaire",
      fee: "3,5–7 %",
    },
    addYacht: {
      cta: "Ajouter un yacht",
      title: "Ajouter un yacht",
      lead: "Propriétaire, yacht et capitaine. Les documents restent privés ; les photos apparaissent dans l’annonce.",
      cancel: "Annuler",
      owner: "1. Propriétaire",
      ownerShare: "Reçoit 38 % du paiement total.",
      ownerName: "Nom complet du propriétaire",
      ownerId: "Photo de pièce d’identité du propriétaire",
      ownerWallet: "Wallet Solana du propriétaire",
      yachtSection: "2. Yacht",
      yachtName: "Nom du yacht",
      photos: "Photos du yacht (jusqu’à 5)",
      hin: "HIN",
      capacity: "Capacité passagers",
      traits: "Classification",
      luxurious: "Luxurious",
      fast: "Fast",
      small: "Small",
      homePort: "Home port ou marina principale",
      captainSection: "3. Capitaine",
      captainShare: "Reçoit 30 % du paiement total + pourboire optionnel.",
      captainName: "Nom complet du capitaine",
      captainId: "Pièce d’identité du capitaine",
      mmc: "Merchant Mariner Credential (MMC)",
      captainPhoto: "Photo du capitaine",
      languages: "Langues",
      langEn: "Anglais",
      langEs: "Espagnol",
      langPt: "Portugais",
      langFr: "Français",
      region: "Région disponible",
      captainWallet: "Wallet Solana du capitaine",
      submit: "Publier ce yacht",
      sending: "Enregistrement…",
      needAuth: "Connectez-vous pour ajouter un yacht.",
      needOwnerId: "Ajoutez la photo d’identité du propriétaire.",
      needPhotos: "Ajoutez 1 à 5 photos du yacht.",
      needHin: "Entrez un HIN valide.",
      needTrait: "Choisissez au moins une caractéristique.",
      needCaptainId: "Ajoutez la pièce d’identité du capitaine.",
      needMmc: "Ajoutez le Merchant Mariner Credential.",
      needCaptainPhoto: "Ajoutez la photo du capitaine.",
      needLanguage: "Choisissez au moins une langue.",
      needWallet: "Entrez un wallet Solana valide.",
      error: "Impossible d’ajouter le yacht. Réessayez.",
      listed: "Publié",
    },
  },
  it: {
    appName: "Kaenz",
    location: "Nel mondo",
    tabs: {
      places: "Luoghi",
      yachts: "Yacht",
      trip: "Il tuo viaggio",
      crew: "Equipaggio",
      account: "Account",
    },
    placesLead:
      "Tocca una marina o un porto sulla mappa. I luoghi in evidenza sono sotto, i più vicini per primi.",
    searchPlaces: "Cerca marine, porti, sandbar…",
    kinds: { all: "Tutti", marina: "Marine", port: "Porti", place: "Luoghi" },
    featuredPlaces: "Luoghi in evidenza",
    featuredNearYou: "Vicino a te",
    featuredSwipe: "Scorri di lato per vedere tutti i luoghi creati, i più vicini per primi.",
    locating: "Cerco la tua posizione…",
    duration: "Durata (ore)",
    hoursUnit: "ore",
    fareHow:
      "Prezzo dal mercato charter locale, tipo di viaggio, durata, classe dello yacht, passeggeri e se parti ora o in programma. Paghi con Stripe.",
    stripePay: "Paga con Stripe",
    gratuityHint:
      "Opzionale 15–20% della tariffa, versata direttamente al capitano. Puoi inserire una percentuale personalizzata fino al 25%.",
    gratuityCustom: "% personalizzata",
    splitLead:
      "Ripartizione: capitano 30%, proprietario 38%, marina di partenza 3,5%, marina di arrivo 3,5%, Kaenz 25%. La mancia è extra e va solo al capitano.",
    payAfterQuote: "Paga questa tariffa con Stripe per confermare il viaggio.",
    paidWithStripe: "Pagato con Stripe",
    stripeCancel: "Checkout annullato. Potrai pagare quando vuoi.",
    stripeMissing: "Stripe non è configurato su questo server.",
    payingStripe: "Apertura di Stripe…",
    captainPlusTip: "Capitano + mancia",
    featured: {
      sandbar: "Sandbar e ancoraggi",
      beach: "Spiagge e parchi",
      dine: "Ristoranti Dock & Dine",
      scenic: "Ville, isole e crociere panoramiche",
    },
    byYacht: "in yacht",
    byCar: "in auto",
    setPickup: "Partenza",
    setDropoff: "Arrivo",
    waterOnly: "Solo acqua",
    yachtsLead:
      "Yacht con capitano verificato, classificati Fast, Small o Luxurious. La capacità è indicata. Il prezzo si calcola sulla richiesta.",
    nearby: "Vicino a te",
    verified: "Capitano verificato",
    guests: "ospiti",
    maxGuests: "Ospiti max",
    classAll: "Tutti",
    from: "Da",
    away: "da te",
    requestThis: "Richiedi questo yacht",
    useLocation: "Usa la mia posizione",
    requestLead: "Richiedi uno yacht per un tragitto, un tour o un’occasione speciale.",
    kindsTrip: {
      commute: { title: "Tragitto", body: "Meno di 2 ore. Batti i ponti, più veloce dell’auto." },
      tour: { title: "Tour", body: "3–6 ore. Sandbar, skyline, tempo in acqua." },
      special: { title: "Occasione speciale", body: "4–8 ore. Tramonti, celebrazioni, clienti a bordo." },
    },
    whenNow: "Now",
    whenSchedule: "Programma",
    whenNowLead: "Parti appena un capitano è pronto.",
    whenScheduleLead: "Scegli data e ora.",
    leavingNow: "Partenza adesso",
    marketBased: "Mercato locale",
    durationRange: {
      commute: "Meno di 2 ore (1–1,5 h)",
      tour: "3–6 ore",
      special: "4–8 ore",
    },
    pickup: "Partenza",
    dropoff: "Destinazione",
    when: "Quando",
    time: "Ora",
    who: "Ospiti",
    yacht: "Yacht",
    name: "Nome completo",
    email: "Email",
    phone: "Telefono",
    continueTrip: "Richiedi questo viaggio",
    choosePickup: "Scegli una partenza",
    chooseDropoff: "Scegli una destinazione",
    searchPickup: "Scrivi una marina o un luogo…",
    searchDropoff: "Scrivi una destinazione…",
    noPlaceMatch: "Nessuna marina o luogo corrisponde. Prova un’altra parola.",
    suggestedNearYou: "Vicino a te",
    tripLead: "Richiedi uno yacht e segui il viaggio fino alla valutazione.",
    noTrip: "Nessun viaggio ancora. Richiedi uno yacht per vedere la tariffa e pagare.",
    requestCta: "Richiedi uno yacht",
    route: "Rotta",
    captain: "Capitano",
    fare: "Tariffa",
    boat: "Yacht e carburante",
    ownerShare: "Proprietario (38%)",
    captainShare: "Capitano (30%)",
    marinaPickupShare: "Marina di partenza (3,5%)",
    marinaDropoffShare: "Marina di arrivo (3,5%)",
    marinaRoundShare: "Marina andata e ritorno (7%)",
    platformShare: "Kaenz (25%)",
    gratuity: "Mancia opzionale",
    gratuityNone: "Nessuna mancia",
    total: "Totale",
    pay: "Pagamento",
    card: "Carta",
    solana: "Solana",
    cardNumber: "Numero della carta",
    expiry: "Scadenza",
    cvc: "CVC",
    wallet: "Wallet Solana",
    payConfirm: "Paga e conferma il viaggio",
    paying: "Conferma in corso…",
    confirmed: "Viaggio confermato",
    statusRequested: "Richiesta inviata",
    statusConfirmed: "Capitano confermato",
    statusUnderway: "In navigazione",
    tripSteps: {
      requested: "Richiesto",
      approved: "Approvato dal capitano",
      waiting: "In attesa in marina",
      underway: "In viaggio",
      paid: "Pagato",
      rated: "Valutato",
    },
    tripStepLead: {
      requested: "Il capitano sta esaminando la richiesta.",
      approved: "Il capitano ha accettato. Vai alla marina di partenza.",
      waiting: "Lo yacht è al molo. Imbarcati quando sei pronto.",
      underway: "Tracciamento in diretta dello yacht e dell’equipaggio a bordo.",
      paid: "Pagamento ricevuto. Valuta l’esperienza.",
      rated: "Grazie per aver navigato con Kaenz.",
    },
    onboard: "Equipaggio a bordo",
    onboardYou: "Tu",
    rateTrip: "Valuta questo viaggio",
    ratedAs: "Hai valutato questo viaggio",
    stars: "stelle",
    arrivedPay: "Sei arrivato. Paga la tariffa con Stripe se non l’hai già fatto.",
    payTrip: "Paga il viaggio",
    demoPay:
      "Stripe Checkout addebita la tariffa dell’algoritmo più la mancia capitano opzionale. Poi si ripartisce tra capitano, proprietario, marine e Kaenz.",
    crewLead: "Condividi con persone interessanti in questa esperienza sociale.",
    goingTo: "Va a",
    joinCrew: "Unisciti a questo equipaggio",
    joined: "Sei in questo equipaggio",
    likes: "mi piace",
    write: "Condividi una nota con l’equipaggio…",
    post: "Pubblica",
    interests: "Ama",
    openMarketing: "Kaenz.com",
    errCard: "Controlla il numero della carta.",
    errExp: "Usa MM/AA.",
    errCvc: "CVC non valido.",
    errWallet: "Wallet Solana incompleto.",
    errConfirm: "Conferma non riuscita. Riprova.",
    account: {
      lead: "Salva i tuoi dati una volta. Richieste e pagamenti li usano automaticamente.",
      personal: "Dati personali",
      payments: "Metodi di pagamento",
      paymentsLead:
        "Kaenz conserva solo le ultime quattro cifre e la scadenza. Il CVC non viene mai salvato.",
      fullName: "Nome completo",
      email: "Email",
      phone: "Telefono",
      creditCard: "Carta di credito",
      debitCard: "Carta di debito",
      solanaWallet: "Wallet Solana",
      cardNumber: "Numero della carta",
      expiry: "Scadenza",
      replace: "Sostituisci",
      remove: "Rimuovi",
      keep: "Mantieni la carta salvata",
      walletPlaceholder: "Il tuo indirizzo Solana",
      save: "Salva account",
      saving: "Salvataggio…",
      savedOk: "Salvato. Le richieste useranno questi dati.",
      saveError: "Impossibile salvare. Riprova.",
      errName: "Inserisci il nome completo.",
      errEmail: "Inserisci un’email valida.",
      errPhone: "Inserisci un telefono valido.",
      errCredit: "Controlla numero e scadenza della carta di credito.",
      errDebit: "Controlla numero e scadenza della carta di debito.",
      errWallet: "Il wallet Solana sembra incompleto.",
      logout: "Esci",
      incomplete: "Aggiungi nome e email in Account prima di richiedere uno yacht.",
      goAccount: "Vai al tuo account",
      usingAccount: "Usiamo i dati del tuo account.",
      editAccount: "Modifica account",
      payWith: "Paga con",
      payCredit: "Carta di credito",
      payDebit: "Carta di debito",
      paySolana: "Wallet Solana",
      noPayMethod:
        "Aggiungi una carta di credito, una carta di debito o un wallet Solana nel tuo account per pagare.",
      role: "Ruolo",
      roleLead: "Scegli il ruolo che ti corrisponde.",
      roles: {
        customer: {
          title: "Customer",
          body: "Richiedi yacht, paga e unisciti all’equipaggio.",
        },
        owner: {
          title: "Owner",
          body: "Pubblica yacht e guadagna il 38% di ogni tariffa.",
        },
        captain: {
          title: "Captain",
          body: "Conduci i viaggi e ricevi il 30% più mancia opzionale.",
        },
      },
      instagram: "Instagram",
      instagramPlaceholder: "@username",
      errInstagram: "Inserisci un username Instagram valido.",
      city: "Città",
      cityFromGps: "Determinata dalla tua posizione GPS.",
      locatingCity: "Cerco la tua città…",
      cityDenied: "Consenti la posizione per impostare la città.",
      useGps: "Usa il mio GPS",
      trips: "I tuoi viaggi",
      tripsLead: "Calendario dei tuoi viaggi e foto di quell’esperienza.",
      noTrips: "Nessun viaggio ancora. Richiedi uno yacht e compariranno qui.",
      noTripsDay: "Nessun viaggio in questo giorno.",
      addPhotos: "Aggiungi foto",
      photos: "Foto",
      photoLimit: "Fino a 8 foto per viaggio.",
      photoError: "Impossibile salvare queste foto. Prova con meno immagini o più leggere.",
      prevMonth: "Mese precedente",
      nextMonth: "Mese successivo",
    },
    addMarina: {
      cta: "Aggiungi marina o porto",
      title: "Aggiungi marina o porto",
      lead: "I partner pubblicano la propria marina o porto. Guadagnano il 3,5% del prezzo cliente a ogni uso, o il 7% se lo yacht parte e torna nello stesso luogo.",
      cancel: "Annulla",
      kind: "Tipo",
      marina: "Marina",
      port: "Porto",
      name: "Nome della marina o del porto",
      lat: "Latitudine",
      lng: "Longitudine",
      address: "Indirizzo",
      region: "Regione",
      dockmaster: "Nome del dockmaster",
      phone: "Telefono",
      website: "Sito web",
      wallet: "Wallet Solana",
      shareNote: "3,5% del prezzo cliente ogni volta che la marina è usata. 7% se partenza e arrivo sono lo stesso luogo.",
      submit: "Pubblica questa marina",
      sending: "Salvataggio…",
      needAuth: "Accedi per pubblicare una marina.",
      needWallet: "Inserisci un wallet Solana valido.",
      needCoords: "Inserisci latitudine e longitudine valide.",
      needUrl: "Inserisci un sito web valido.",
      error: "Impossibile aggiungere la marina. Riprova.",
      listed: "Pubblicata",
      partner: "Partner",
      fee: "3,5–7%",
    },
    addYacht: {
      cta: "Aggiungi uno yacht",
      title: "Aggiungi uno yacht",
      lead: "Proprietario, yacht e capitano. I documenti restano privati; le foto compaiono nell’annuncio.",
      cancel: "Annulla",
      owner: "1. Proprietario",
      ownerShare: "Riceve il 38% del pagamento totale.",
      ownerName: "Nome completo del proprietario",
      ownerId: "Foto documento del proprietario",
      ownerWallet: "Wallet Solana del proprietario",
      yachtSection: "2. Yacht",
      yachtName: "Nome dello yacht",
      photos: "Foto dello yacht (fino a 5)",
      hin: "HIN",
      capacity: "Capacità passeggeri",
      traits: "Classificazione",
      luxurious: "Luxurious",
      fast: "Fast",
      small: "Small",
      homePort: "Home port o marina principale",
      captainSection: "3. Capitano",
      captainShare: "Riceve il 30% del pagamento totale + mancia opzionale.",
      captainName: "Nome completo del capitano",
      captainId: "Documento d’identità del capitano",
      mmc: "Merchant Mariner Credential (MMC)",
      captainPhoto: "Foto del capitano",
      languages: "Lingue",
      langEn: "Inglese",
      langEs: "Spagnolo",
      langPt: "Portoghese",
      langFr: "Francese",
      region: "Regione disponibile",
      captainWallet: "Wallet Solana del capitano",
      submit: "Pubblica questo yacht",
      sending: "Salvataggio…",
      needAuth: "Accedi per aggiungere uno yacht.",
      needOwnerId: "Carica la foto del documento del proprietario.",
      needPhotos: "Carica da 1 a 5 foto dello yacht.",
      needHin: "Inserisci un HIN valido.",
      needTrait: "Scegli almeno una caratteristica.",
      needCaptainId: "Carica il documento del capitano.",
      needMmc: "Carica il Merchant Mariner Credential.",
      needCaptainPhoto: "Carica la foto del capitano.",
      needLanguage: "Scegli almeno una lingua.",
      needWallet: "Inserisci un wallet Solana valido.",
      error: "Impossibile aggiungere lo yacht. Riprova.",
      listed: "Pubblicato",
    },
  },
  pt: {
    appName: "Kaenz",
    location: "No mundo",
    tabs: {
      places: "Lugares",
      yachts: "Iates",
      trip: "Sua viagem",
      crew: "Tripulação",
      account: "Conta",
    },
    placesLead:
      "Toque uma marina ou porto no mapa. Os lugares em destaque ficam abaixo, os mais próximos primeiro.",
    searchPlaces: "Buscar marinas, portos, sandbars…",
    kinds: { all: "Todos", marina: "Marinas", port: "Portos", place: "Lugares" },
    featuredPlaces: "Lugares em destaque",
    featuredNearYou: "Perto de você",
    featuredSwipe: "Deslize para o lado para ver todos os lugares que criamos, os mais próximos primeiro.",
    locating: "Buscando sua localização…",
    duration: "Duração (horas)",
    hoursUnit: "horas",
    fareHow:
      "Preço pelo mercado local de charter, tipo de viagem, duração, classe do iate, passageiros e se você sai agora ou agenda. Cobrado com Stripe.",
    stripePay: "Pagar com Stripe",
    gratuityHint:
      "Opcional 15–20% da tarifa, paga direto ao capitão. Você pode informar um percentual próprio até 25%.",
    gratuityCustom: "% personalizado",
    splitLead:
      "A tarifa se reparte: capitão 30%, dono do iate 38%, marina de partida 3,5%, marina de chegada 3,5%, Kaenz 25%. A gorjeta é extra e vai só ao capitão.",
    payAfterQuote: "Pague esta tarifa com Stripe para confirmar a viagem.",
    paidWithStripe: "Pago com Stripe",
    stripeCancel: "Checkout cancelado. Você pode pagar quando quiser.",
    stripeMissing: "Stripe não está configurado neste servidor.",
    payingStripe: "Abrindo o Stripe…",
    captainPlusTip: "Capitão + gorjeta",
    featured: {
      sandbar: "Sandbars e fundeadouros",
      beach: "Praias e parques",
      dine: "Restaurantes Dock & Dine",
      scenic: "Mansões, ilhas e cruzeiros cênicos",
    },
    byYacht: "de iate",
    byCar: "de carro",
    setPickup: "Partida",
    setDropoff: "Chegada",
    waterOnly: "Só água",
    yachtsLead:
      "Iates com capitão verificado, classificados Fast, Small ou Luxurious. A capacidade aparece no anúncio. O preço é calculado no pedido.",
    nearby: "Perto de você",
    verified: "Capitão verificado",
    guests: "convidados",
    maxGuests: "Capacidade máx.",
    classAll: "Todos",
    from: "A partir de",
    away: "de você",
    requestThis: "Solicitar este iate",
    useLocation: "Usar minha localização",
    requestLead: "Solicite um iate para trajeto, passeio ou ocasião especial.",
    kindsTrip: {
      commute: { title: "Trajeto", body: "Menos de 2 horas. Ganhe das pontes, mais rápido que de carro." },
      tour: { title: "Passeio", body: "3–6 horas. Sandbars, skyline e tempo na água." },
      special: { title: "Ocasião especial", body: "4–8 horas. Pores do sol, celebrações, clientes a bordo." },
    },
    whenNow: "Now",
    whenSchedule: "Agendar",
    whenNowLead: "Sair assim que um capitão estiver pronto.",
    whenScheduleLead: "Escolha data e hora.",
    leavingNow: "Saindo agora",
    marketBased: "Mercado local",
    durationRange: {
      commute: "Menos de 2 horas (1–1,5 h)",
      tour: "3–6 horas",
      special: "4–8 horas",
    },
    pickup: "Partida",
    dropoff: "Destino",
    when: "Quando",
    time: "Hora",
    who: "Convidados",
    yacht: "Iate",
    name: "Nome completo",
    email: "E-mail",
    phone: "Telefone",
    continueTrip: "Solicitar esta viagem",
    choosePickup: "Escolha uma partida",
    chooseDropoff: "Escolha um destino",
    searchPickup: "Digite uma marina ou lugar…",
    searchDropoff: "Digite um destino…",
    noPlaceMatch: "Nenhuma marina ou lugar corresponde. Tente outra palavra.",
    suggestedNearYou: "Perto de você",
    tripLead: "Solicite um iate e acompanhe a viagem até a avaliação.",
    noTrip: "Ainda não há viagem. Solicite um iate para ver a tarifa e pagar.",
    requestCta: "Solicitar um iate",
    route: "Rota",
    captain: "Capitão",
    fare: "Tarifa",
    boat: "Iate e combustível",
    ownerShare: "Dono (38%)",
    captainShare: "Capitão (30%)",
    marinaPickupShare: "Marina de partida (3,5%)",
    marinaDropoffShare: "Marina de chegada (3,5%)",
    marinaRoundShare: "Marina ida e volta (7%)",
    platformShare: "Kaenz (25%)",
    gratuity: "Gorjeta opcional",
    gratuityNone: "Sem gorjeta",
    total: "Total",
    pay: "Pagamento",
    card: "Cartão",
    solana: "Solana",
    cardNumber: "Número do cartão",
    expiry: "Validade",
    cvc: "CVC",
    wallet: "Carteira Solana",
    payConfirm: "Pagar e confirmar viagem",
    paying: "Confirmando…",
    confirmed: "Viagem confirmada",
    statusRequested: "Pedido enviado",
    statusConfirmed: "Capitão confirmou",
    statusUnderway: "Em andamento",
    tripSteps: {
      requested: "Solicitado",
      approved: "Aprovado pelo capitão",
      waiting: "Esperando na marina",
      underway: "Viajando",
      paid: "Pago",
      rated: "Avaliado",
    },
    tripStepLead: {
      requested: "O capitão está analisando seu pedido.",
      approved: "O capitão aceitou. Vá à marina de partida.",
      waiting: "O iate está no cais. Embarque quando estiver pronto.",
      underway: "Acompanhe ao vivo o iate e a tripulação a bordo.",
      paid: "Pagamento recebido. Avalie a experiência.",
      rated: "Obrigado por navegar com a Kaenz.",
    },
    onboard: "Tripulação a bordo",
    onboardYou: "Você",
    rateTrip: "Avalie esta viagem",
    ratedAs: "Você avaliou esta viagem",
    stars: "estrelas",
    arrivedPay: "Você chegou. Pague a tarifa com Stripe se ainda não pagou.",
    payTrip: "Pagar viagem",
    demoPay:
      "O Stripe Checkout cobra a tarifa do algoritmo mais a gorjeta opcional ao capitão. Depois reparte entre capitão, dono, marinas e Kaenz.",
    crewLead: "Compartilhe com pessoas interessantes nesta experiência social.",
    goingTo: "Vai para",
    joinCrew: "Entrar nesta tripulação",
    joined: "Você está nesta tripulação",
    likes: "curtidas",
    write: "Compartilhe uma nota com a tripulação…",
    post: "Publicar",
    interests: "Curte",
    openMarketing: "Kaenz.com",
    errCard: "Confira o número do cartão.",
    errExp: "Use MM/AA.",
    errCvc: "CVC inválido.",
    errWallet: "Carteira Solana incompleta.",
    errConfirm: "Não foi possível confirmar. Tente de novo.",
    account: {
      lead: "Salve seus dados uma vez. Solicitações e pagamentos os usam automaticamente.",
      personal: "Dados pessoais",
      payments: "Formas de pagamento",
      paymentsLead:
        "A Kaenz guarda só os últimos quatro dígitos e a validade. O CVC nunca é salvo.",
      fullName: "Nome completo",
      email: "E-mail",
      phone: "Telefone",
      creditCard: "Cartão de crédito",
      debitCard: "Cartão de débito",
      solanaWallet: "Wallet Solana",
      cardNumber: "Número do cartão",
      expiry: "Validade",
      replace: "Trocar",
      remove: "Remover",
      keep: "Manter cartão salvo",
      walletPlaceholder: "Seu endereço Solana",
      save: "Salvar conta",
      saving: "Salvando…",
      savedOk: "Salvo. As solicitações usarão estes dados.",
      saveError: "Não foi possível salvar. Tente de novo.",
      errName: "Informe seu nome completo.",
      errEmail: "Informe um e-mail válido.",
      errPhone: "Informe um telefone válido.",
      errCredit: "Confira o número e a validade do cartão de crédito.",
      errDebit: "Confira o número e a validade do cartão de débito.",
      errWallet: "A wallet Solana parece incompleta.",
      logout: "Sair",
      incomplete: "Adicione nome e e-mail em Conta antes de solicitar um iate.",
      goAccount: "Ir para sua conta",
      usingAccount: "Usando os dados da sua conta.",
      editAccount: "Editar conta",
      payWith: "Pagar com",
      payCredit: "Cartão de crédito",
      payDebit: "Cartão de débito",
      paySolana: "Wallet Solana",
      noPayMethod:
        "Adicione um cartão de crédito, débito ou wallet Solana na sua conta para pagar.",
      role: "Função",
      roleLead: "Escolha a função que corresponde a você.",
      roles: {
        customer: {
          title: "Customer",
          body: "Solicite iates, pague e entre na crew.",
        },
        owner: {
          title: "Owner",
          body: "Publique iates e ganhe 38% de cada tarifa.",
        },
        captain: {
          title: "Captain",
          body: "Conduza viagens e receba 30% mais gorjeta opcional.",
        },
      },
      instagram: "Instagram",
      instagramPlaceholder: "@usuario",
      errInstagram: "Informe um usuário de Instagram válido.",
      city: "Cidade",
      cityFromGps: "Definida pelo seu GPS.",
      locatingCity: "Buscando sua cidade…",
      cityDenied: "Permita a localização para definir sua cidade.",
      useGps: "Usar meu GPS",
      trips: "Suas viagens",
      tripsLead: "Calendário das suas viagens e fotos dessa experiência.",
      noTrips: "Ainda não há viagens. Solicite um iate e elas aparecem aqui.",
      noTripsDay: "Nenhuma viagem neste dia.",
      addPhotos: "Adicionar fotos",
      photos: "Fotos",
      photoLimit: "Até 8 fotos por viagem.",
      photoError: "Não foi possível salvar essas fotos. Tente menos imagens ou mais leves.",
      prevMonth: "Mês anterior",
      nextMonth: "Mês seguinte",
    },
    addMarina: {
      cta: "Adicionar marina ou porto",
      title: "Adicionar marina ou porto",
      lead: "Os partners publicam a marina ou o porto. Ganham 3,5% do preço do cliente a cada uso, ou 7% se o iate sai e volta ao mesmo lugar.",
      cancel: "Cancelar",
      kind: "Tipo",
      marina: "Marina",
      port: "Porto",
      name: "Nome da marina ou porto",
      lat: "Latitude",
      lng: "Longitude",
      address: "Endereço",
      region: "Região",
      dockmaster: "Nome do dockmaster",
      phone: "Telefone",
      website: "Site",
      wallet: "Wallet Solana",
      shareNote: "3,5% do preço do cliente cada vez que a marina é usada. 7% se partida e chegada são o mesmo lugar.",
      submit: "Publicar esta marina",
      sending: "Salvando…",
      needAuth: "Entre para publicar uma marina.",
      needWallet: "Informe uma wallet Solana válida.",
      needCoords: "Informe latitude e longitude válidas.",
      needUrl: "Informe um site válido.",
      error: "Não foi possível adicionar a marina. Tente de novo.",
      listed: "Publicada",
      partner: "Partner",
      fee: "3,5–7%",
    },
    addYacht: {
      cta: "Adicionar um iate",
      title: "Adicionar um iate",
      lead: "Dono, iate e capitão. Os documentos ficam privados; as fotos aparecem no anúncio.",
      cancel: "Cancelar",
      owner: "1. Dono",
      ownerShare: "Recebe 38% do pagamento total.",
      ownerName: "Nome completo do dono",
      ownerId: "Foto de ID do dono",
      ownerWallet: "Wallet Solana do dono",
      yachtSection: "2. Iate",
      yachtName: "Nome do iate",
      photos: "Fotos do iate (até 5)",
      hin: "HIN",
      capacity: "Capacidade de passageiros",
      traits: "Classificação",
      luxurious: "Luxurious",
      fast: "Fast",
      small: "Small",
      homePort: "Home port ou marina principal",
      captainSection: "3. Capitão",
      captainShare: "Recebe 30% do pagamento total + gorjeta opcional.",
      captainName: "Nome completo do capitão",
      captainId: "Documento de ID do capitão",
      mmc: "Merchant Mariner Credential (MMC)",
      captainPhoto: "Foto do capitão",
      languages: "Idiomas",
      langEn: "Inglês",
      langEs: "Espanhol",
      langPt: "Português",
      langFr: "Francês",
      region: "Região disponível",
      captainWallet: "Wallet Solana do capitão",
      submit: "Publicar este iate",
      sending: "Salvando…",
      needAuth: "Entre para adicionar um iate.",
      needOwnerId: "Envie a foto de ID do dono.",
      needPhotos: "Envie de 1 a 5 fotos do iate.",
      needHin: "Informe um HIN válido.",
      needTrait: "Escolha pelo menos uma característica.",
      needCaptainId: "Envie o ID do capitão.",
      needMmc: "Envie o Merchant Mariner Credential.",
      needCaptainPhoto: "Envie a foto do capitão.",
      needLanguage: "Escolha pelo menos um idioma.",
      needWallet: "Informe uma wallet Solana válida.",
      error: "Não foi possível adicionar o iate. Tente de novo.",
      listed: "Publicado",
    },
  },
} as const;

export function at(locale: Locale) {
  return appCopy[locale];
}

export type AppTab =
  | "places"
  | "yachts"
  | "trip"
  | "crew"
  | "account";
