import type { Locale } from "./locale";

export const copy = {
  en: {
    metaTitle: "Kaenz: Commute, Tour & Special Occasion by yacht",
    metaDescription:
      "Kaenz is an end-to-end yacht platform — not a charter operator — for Commute, Tour, and Special Occasion trips worldwide. Price by trip type, duration, yacht, guests, and date. Pay with Stripe.",
    brand: "Kaenz",
    nav: {
      app: "Platform",
      fleet: "Yachts",
      book: "Book",
      concierge: "Concierge",
      join: "Join",
      terms: "Terms",
      privacy: "Privacy",
      login: "Log in",
      signup: "Sign up",
      logout: "Log out",
    },
    heroTitle: "Skip the traffic. Travel by yacht.",
    heroLead:
      "Commute, tour, and celebrate on the water. Immortalize your trip, give Vibes, list yachts and marinas — all on one platform.",
    heroCta: "Enter the platform",
    heroSecondary: "See yachts",
    platformEyebrow: "Inside Kaenz",
    platformTitle: "The platform, end to end",
    platformLead:
      "Places, yachts, live trips, Crew selfies, and your account — built for water, people, and Stripe.",
    platformFeatures: [
      {
        title: "Places",
        body: "Tap marinas and ports on the map. Partners add their marina or port in Places.",
        cta: "Add a marina",
      },
      {
        title: "Yachts",
        body: "Verified captains. Owners and captains list a yacht in Yachts and earn on every fare.",
        cta: "Add your yacht",
      },
      {
        title: "Your Trip",
        body: "Request, follow live, pay with Stripe, and rate. Fare splits to owner, captain, marinas, and Kaenz.",
        cta: "Start a trip",
      },
      {
        title: "Crew",
        body: "Immortalize your trip with a selfie, earn Vibes, and vote the Top 100 Selfies 2026.",
        cta: "Open Crew",
      },
      {
        title: "Account",
        body: "Profile photo, text size, and Kaenz colors — navy and cyan, your way.",
        cta: "Your account",
      },
    ],
    crewSiteTitle: "Immortalize your trip",
    crewSiteLead:
      "Upload a selfie from onboard, earn Vibes, and give Vibes to family, partners, friends, colleagues, or your crush in Drive Kaenz TopQ1.",
    crewSiteCta: "Open Top 100 Selfies",
    solveEyebrow: "What Do We Solve?",
    solveLead:
      "Water is the smartest way to commute, tour, and celebrate — in South Florida and around the world.",
    pillars: [
      {
        title: "Buy Time",
        body: "Save yourself hours of traffic and arrive earlier because nothing stands in your way.",
      },
      {
        title: "Eliminates Stress",
        body: "Forget the honking and frustration. Here, tranquility and peace abound.",
      },
      {
        title: "Enjoy your Journeys",
        body: "There are thousands of cruising miles, sandbars and skylines to enjoy.",
      },
    ],
    uniqueTitle: "A platform, not a charter.",
    uniqueBody:
      "Kaenz is an end-to-end platform for Commute, Tour, and Special Occasion yacht trips in marinas and ports worldwide. Independent owners, captains, and marinas run each trip. An algorithm sets the price from trip type, duration, yacht type, guests, and date — then you pay with Stripe.",
    tripTypesTitle: "Commute, Tour & Special Occasion",
    tripTypesLead:
      "One platform for getting there, staying on the water, and celebrating — wherever Kaenz has a marina or port.",
    tripTypes: [
      {
        title: "Commute",
        body: "Beat bridges and traffic. A captained yacht hop that gets you there faster than the car.",
      },
      {
        title: "Tour",
        body: "Sandbars, skyline cruises, dock-and-dine, and hours on the water in the destination you choose.",
      },
      {
        title: "Special occasion",
        body: "Sunsets, proposals, clients on deck, and celebrations with a verified captain worldwide.",
      },
    ],
    pricingTitle: "How the price is set",
    pricingBody:
      "An algorithm prices every trip from the local charter market, trip type (Commute under 2 hours, Tour 3–6 hours, Special Occasion 4–8 hours), duration, yacht class, guests, and date. You pay with Stripe. The fare splits: Yacht owner 38%, Captain 30%, Kaenz 25%, pickup marina 3.5%, dropoff marina 3.5%. Optional captain gratuity (15–20%) is added on top and goes directly to the captain.",
    uniqueTerms: "Read the Terms and Conditions.",
    testimonialsTitle: "What Do Our Customers Think?",
    testimonials: [
      {
        quote:
          "Fort Lauderdale to Hollywood Beach in 35 minutes with a sandbar. Perfect family day out!",
        name: "Mia Lee",
        city: "Fort Lauderdale",
      },
      {
        quote: "From Miami Beach to Brickell in 18 minutes by yacht. Goodbye traffic!",
        name: "William Brown",
        city: "Miami",
      },
      {
        quote:
          "From Fort Lauderdale to Palm Beach in 45 minutes at sunset. Unforgettable romance!",
        name: "Emily Johnson",
        city: "Palm Beach",
      },
    ],
    marinasTitle: "Marinas & Ports",
    marinasBody:
      "Kaenz connects private yachts at marinas and ports worldwide. Arrive and depart by water — from South Florida to the Med, the Caribbean, and beyond. Open the platform and add your marina or port in Places.",
    marinasCta: "Open the platform and add your marina",
    joinTitle: "Do you Own a Yacht and Are you a Captain?",
    joinCta: "Open the platform and add your yacht",
    joinLead:
      "Open Kaenz, go to Yachts, and list your boat with a verified captain. Independent owners and captains are paid through Stripe on every trip.",
    fleetTitle: "Choose your yacht",
    fleetLead: "Private, captained, ready when you are.",
    from: "From",
    guests: "guests",
    hours: "hours",
    bookNow: "View yacht",
    requestPlatform: "Request on the platform",
    requestPlatformLead:
      "Trips are requested in Kaenz Yachts — verified captain, Stripe, live tracking.",
    bookStripe: "Book this trip — pay with Stripe",
    bookStripeLead:
      "Choose Commute, Tour, or Special Occasion. Pay in USD with Stripe. No app login required.",
    bookableNow: "Bookable now",
    catalogLabel: "Catalog",
    catalogLead: "Marketing catalog — not live inventory.",
    seeBookable: "See bookable yachts",
    payStripe: "Pay with Stripe",
    bookingConfirmed: "Trip booked",
    bookingReceipt: "Stripe receipt",
    bookingProcessing: "Payment received. Confirming your booking…",
    bookingUnpaid: "This checkout was not completed. You can book again from the yacht page.",
    stripeMissing: "Stripe is not configured on this server.",
    guestEmail: "Email for your receipt",
    bookTitle: "Book a private yacht",
    bookLead:
      "Request a Commute, Tour, or Special Occasion. A verified captain is included. Stripe checkout, priced by our algorithm.",
    form: {
      name: "Full name",
      email: "Email",
      phone: "Phone",
      kind: "Trip type",
      duration: "Duration (hours)",
      yacht: "Yacht",
      origin: "Pickup marina",
      destination: "Destination",
      date: "Date",
      time: "Time",
      guests: "Guests",
      notes: "Notes",
      submit: "Request booking",
      sending: "Sending…",
      success: "Request received. A Kaenz concierge will confirm shortly.",
    },
    conciergeTitle: "Kaenz Concierge",
    conciergeLead:
      "Plan a Commute, Tour, or Special Occasion by yacht — worldwide. Routes, timing, and the right boat.",
    conciergePlaceholder: "Where do you want to go, and when?",
    conciergeSend: "Send",
    joinPageTitle: "Join the Kaenz platform",
    joinPageLead:
      "Open Kaenz to list what you operate. Owners and captains add a yacht in Yachts. Marinas and ports add their place in Places.",
    owner: "Yacht owner",
    captain: "Captain",
    both: "Owner & captain",
    uscg: "USCG license (captains)",
    yachtName: "Yacht name",
    submitJoin: "Apply to join",
    rights: "All Rights Reserved for Salvazion Inc. 2026.",
    termsTitle: "Terms and Conditions",
    termsHref: "/terms",
    privacyTitle: "Privacy Policy",
    privacyHref: "/privacy",
    mapTitle: "Kaenz world marinas & ports",
    mapWorld: "World",
    mapFlorida: "South Florida",
    legendMarina: "Marina",
    legendPort: "Port",
    legendPlace: "Drop-off",
    hubsLabel: "marinas and ports for yacht arrivals and departures",
    mapZoomIn: "Zoom in",
    mapZoomOut: "Zoom out",
    mapNearMe: "Near me",
    liveTrip: "Trip in progress",
    liveBadge: "Live",
    liveAway: "{n} min away",
    liveFaster: "{n} min faster than driving",
    liveArrived: "Arrived — ready to pay",
    appPreviewEyebrow: "On your phone",
    appPreviewTitle: "Watch your yacht move, marina to marina",
    appPreviewLead:
      "The Kaenz platform on mobile: pick a marina, board, and follow the live hop while the causeway sits still.",
    appPreviewCta: "Open the platform",
    role: "Role",
    joinFee:
      "Paid with Stripe. Owner 38%. Captain 30%. Kaenz 25%. Pickup marina 3.5%. Dropoff marina 3.5%. Optional captain gratuity (15–20%) goes directly to the captain.",
    joinCaptains:
      "Captains: current USCG OUPV Six-Pack or equivalent local license, plus background check.",
    joinOwners:
      "Owners: yacht registration, HIN, and commercial marine insurance (min. $1,000,000).",
    formError: "Could not send. Please try again.",
    joinSuccess:
      "Application received. We will contact you to verify license and yacht.",
    conciergeHello:
      "I’m the Kaenz concierge. Tell me Commute, Tour, or Special Occasion — origin, destination, guests, duration, and date. I’ll match a yacht worldwide.",
    conciergeMissingKey:
      "Missing XAI_API_KEY on the server. Add it to enable Grok.",
    conciergeUnavailable:
      "Concierge is unavailable right now. Book directly from the fleet.",
    loginTitle: "Enter the Kaenz platform",
    signupTitle: "Create your Kaenz account",
    password: "Password",
    passwordConfirm: "Confirm password",
    haveAccount: "Already have an account? Log in",
    needAccount: "New here? Create an account",
    loginCta: "Log in",
    signupCta: "Create account",
    loginError: "Email or password is incorrect.",
    signupError: "Could not create the account.",
    passwordMismatch: "Passwords do not match.",
    passwordShort: "Use at least 8 characters.",
    sessionNeeded: "Log in to open the Kaenz platform.",
    nameRequired: "Full name is required.",
    googleCta: "Continue with Gmail",
    orContinue: "or",
    googleError: "Could not sign in with Gmail. Try again, or use email and password.",
    googleUnconfigured: "Gmail sign-in is not available right now. Use email and password.",
    googleDenied: "Gmail sign-in was cancelled. Try again, or use email and password.",
    biometricEnter: "Sign in with your thumb",
    biometricProcessing: "Waiting for your fingerprint…",
    biometricRetry: "Place your finger on the sensor again",
    biometricFailed: "Fingerprint could not be verified. Try again.",
    biometricUnavailable:
      "This device has no fingerprint, Face ID, or Windows Hello available.",
    biometricExpired: "Fingerprint session expired. Sign in with email or Google.",
    biometricLockTitle: "Kaenz",
    biometricLockSubtitle: "Place your finger on the sensor",
    biometricUsePassword: "Use password",
  },
  es: {
    metaTitle: "Kaenz: Commute, Tour y Ocasión especial en yate",
    metaDescription:
      "Kaenz es una plataforma integral de yates — no un operador de chárter — para Commute, Tour y Ocasión especial en el mundo. El precio sale del tipo de viaje, duración, yate, pasajeros y fecha. Pagas con Stripe.",
    brand: "Kaenz",
    nav: {
      app: "Plataforma",
      fleet: "Yates",
      book: "Reservar",
      concierge: "Concierge",
      join: "Únete",
      terms: "Términos",
      privacy: "Privacidad",
      login: "Entrar",
      signup: "Crear cuenta",
      logout: "Salir",
    },
    heroTitle: "Salta el tráfico. Viaja en yate.",
    heroLead:
      "Commute, tour y celebra en el agua. Inmortaliza tu viaje, da Vibes, publica yates y marinas — en una sola plataforma.",
    heroCta: "Entrar a la plataforma",
    heroSecondary: "Ver yates",
    platformEyebrow: "Dentro de Kaenz",
    platformTitle: "La plataforma, de punta a punta",
    platformLead:
      "Lugares, yates, viajes en vivo, selfies de Crew y tu cuenta — agua, gente y Stripe.",
    platformFeatures: [
      {
        title: "Lugares",
        body: "Toca marinas y puertos en el mapa. Los socios agregan su marina o puerto en Lugares.",
        cta: "Agregar una marina",
      },
      {
        title: "Yates",
        body: "Capitanes verificados. Dueños y capitanes publican un yate en Yates y ganan en cada tarifa.",
        cta: "Agregar tu yate",
      },
      {
        title: "Tu Viaje",
        body: "Solicita, sigue en vivo, paga con Stripe y evalúa. La tarifa se reparte entre dueño, capitán, marinas y Kaenz.",
        cta: "Empezar un viaje",
      },
      {
        title: "Crew",
        body: "Inmortaliza tu viaje con un selfie, gana Vibes y vota el Top 100 Selfies 2026.",
        cta: "Abrir Crew",
      },
      {
        title: "Cuenta",
        body: "Foto de perfil, tamaño de letra y colores Kaenz — navy y cian, a tu manera.",
        cta: "Tu cuenta",
      },
    ],
    crewSiteTitle: "Inmortaliza tu viaje",
    crewSiteLead:
      "Sube un selfie a bordo, gana Vibes y dáselos a familia, pareja, amigos, colegas o crush en Drive Kaenz TopQ1.",
    crewSiteCta: "Abrir Top 100 Selfies",
    solveEyebrow: "¿Qué Resolvemos?",
    solveLead:
      "El agua es la forma más inteligente de hacer commute, tour y celebrar — en South Florida y en el mundo.",
    pillars: [
      {
        title: "Gana Tiempo",
        body: "Ahorra horas de atascos y llega antes porque nada se interpone en tu camino.",
      },
      {
        title: "Elimina Estrés",
        body: "Olvídate de los bocinazos y la frustración. Aquí la tranquilidad y paz abundan.",
      },
      {
        title: "Disfruta tus Viajes",
        body: "Hay miles de millas navegables, sandbars y skyline para disfrutar.",
      },
    ],
    uniqueTitle: "Una plataforma, no un chárter.",
    uniqueBody:
      "Kaenz es una plataforma integral para viajes en yate de Commute, Tour y Ocasión especial en marinas y puertos del mundo. Dueños, capitanes y marinas independientes operan cada viaje. Un algoritmo fija el precio según tipo de viaje, duración, tipo de yate, pasajeros y fecha — y pagas con Stripe.",
    tripTypesTitle: "Commute, Tour y Ocasión especial",
    tripTypesLead:
      "Una plataforma para llegar, quedarte en el agua y celebrar — donde Kaenz tenga marina o puerto.",
    tripTypes: [
      {
        title: "Commute",
        body: "Gánale a puentes y tráfico. Un salto en yate con capitán más rápido que el auto.",
      },
      {
        title: "Tour",
        body: "Sandbars, skyline, dock-and-dine y horas en el agua en el destino que elijas.",
      },
      {
        title: "Ocasión especial",
        body: "Atardeceres, propuestas, clientes a bordo y celebraciones con capitán verificado.",
      },
    ],
    pricingTitle: "Cómo se calcula el precio",
    pricingBody:
      "Un algoritmo fija cada viaje según el mercado local de chárter, tipo (Commute menos de 2 horas, Tour 3–6 horas, Ocasión especial 4–8 horas), duración, clase de yate, pasajeros y fecha. Pagas con Stripe. El pago se reparte: dueño del yate 38%, capitán 30%, Kaenz 25%, marina de origen 3.5%, marina de destino 3.5%. La gratificación al capitán (15–20%) es opcional, va encima del pago y llega directo al capitán.",
    uniqueTerms: "Lee los Términos y Condiciones.",
    testimonialsTitle: "¿Qué Piensan Nuestros Clientes?",
    testimonials: [
      {
        quote:
          "¡Fort Lauderdale a Hollywood Beach en 35 min con sandbar. Día familiar perfecto!",
        name: "Mia Lee",
        city: "Fort Lauderdale",
      },
      {
        quote: "De Miami Beach a Brickell en 18 minutos por yate. ¡Adiós tráfico!",
        name: "William Brown",
        city: "Miami",
      },
      {
        quote:
          "De Fort Lauderdale a Palm Beach en 45 min al atardecer. ¡Romance inolvidable!",
        name: "Emily Johnson",
        city: "Palm Beach",
      },
    ],
    marinasTitle: "Marinas y Puertos",
    marinasBody:
      "Kaenz conecta yates privados en marinas y puertos de todo el mundo. Llega y sale por agua — de South Florida al Mediterráneo, el Caribe y más allá. Abre la plataforma y agrega tu marina o puerto en Lugares.",
    marinasCta: "Abre la plataforma y agrega tu marina",
    joinTitle: "¿Tienes un Yate y eres Capitán?",
    joinCta: "Abre la plataforma y agrega tu yate",
    joinLead:
      "Abre Kaenz, ve a Yates y publica tu yate con capitán verificado. Dueños y capitanes independientes se pagan con Stripe en cada viaje.",
    fleetTitle: "Elige tu yate",
    fleetLead: "Privado, con capitán, listo cuando tú lo estés.",
    from: "Desde",
    guests: "huéspedes",
    hours: "horas",
    bookNow: "Ver yate",
    requestPlatform: "Solicitar en la plataforma",
    requestPlatformLead:
      "Los viajes se piden en Yates de Kaenz — capitán verificado, Stripe y seguimiento en vivo.",
    bookStripe: "Reserva este viaje — paga con Stripe",
    bookStripeLead:
      "Elige Commute, Tour u Ocasión especial. Paga en USD con Stripe. No hace falta entrar a la app.",
    bookableNow: "Reservable ahora",
    catalogLabel: "Catálogo",
    catalogLead: "Catálogo de marketing — no es inventario en vivo.",
    seeBookable: "Ver yates reservables",
    payStripe: "Pagar con Stripe",
    bookingConfirmed: "Viaje reservado",
    bookingReceipt: "Recibo de Stripe",
    bookingProcessing: "Pago recibido. Confirmando tu reserva…",
    bookingUnpaid: "Este checkout no se completó. Puedes reservar de nuevo desde la ficha del yate.",
    stripeMissing: "Stripe no está configurado en este servidor.",
    guestEmail: "Correo para tu recibo",
    bookTitle: "Reserva un yate privado",
    bookLead:
      "Solicita Commute, Tour u Ocasión especial. Capitán verificado incluido. Pago con Stripe, precio del algoritmo.",
    form: {
      name: "Nombre completo",
      email: "Correo",
      phone: "Teléfono",
      kind: "Tipo de viaje",
      duration: "Duración (horas)",
      yacht: "Yate",
      origin: "Marina de salida",
      destination: "Destino",
      date: "Fecha",
      time: "Hora",
      guests: "Huéspedes",
      notes: "Notas",
      submit: "Solicitar reserva",
      sending: "Enviando…",
      success: "Solicitud recibida. Un concierge de Kaenz confirmará en breve.",
    },
    conciergeTitle: "Concierge Kaenz",
    conciergeLead:
      "Planifica Commute, Tour u Ocasión especial en yate — en el mundo. Rutas, horarios y el barco correcto.",
    conciergePlaceholder: "¿A dónde quieres ir, y cuándo?",
    conciergeSend: "Enviar",
    joinPageTitle: "Únete a la plataforma Kaenz",
    joinPageLead:
      "Abre Kaenz para publicar lo que operas. Dueños y capitanes agregan un yate en Yates. Marinas y puertos agregan su lugar en Lugares.",
    owner: "Dueño de yate",
    captain: "Capitán",
    both: "Dueño y capitán",
    uscg: "Licencia USCG (capitanes)",
    yachtName: "Nombre del yate",
    submitJoin: "Postularme",
    rights: "Todos los Derechos Reservados para Salvazion Inc. 2026.",
    termsTitle: "Términos y Condiciones",
    termsHref: "/terms",
    privacyTitle: "Política de Privacidad",
    privacyHref: "/privacy",
    mapTitle: "Marinas y puertos mundiales Kaenz",
    mapWorld: "Mundo",
    mapFlorida: "South Florida",
    legendMarina: "Marina",
    legendPort: "Puerto",
    legendPlace: "Destino",
    hubsLabel: "marinas y puertos para llegadas y salidas en yate",
    mapZoomIn: "Acercar",
    mapZoomOut: "Alejar",
    mapNearMe: "Cerca de mí",
    liveTrip: "Viaje en curso",
    liveBadge: "En vivo",
    liveAway: "A {n} min",
    liveFaster: "{n} min más rápido que en auto",
    liveArrived: "Llegaste — listo para pagar",
    appPreviewEyebrow: "En tu móvil",
    appPreviewTitle: "Mira el yate ir de marina a marina",
    appPreviewLead:
      "La plataforma Kaenz en el teléfono: elige una marina, sube y sigue el salto en vivo mientras el tráfico se queda quieto.",
    appPreviewCta: "Abrir la plataforma",
    role: "Rol",
    joinFee:
      "Se cobra con Stripe. Dueño 38%. Capitán 30%. Kaenz 25%. Marina de origen 3.5%. Marina de destino 3.5%. Gratificación opcional al capitán (15–20%) va directo al capitán.",
    joinCaptains:
      "Capitanes: credencial USCG OUPV Six-Pack o licencia local equivalente, y verificación de antecedentes.",
    joinOwners:
      "Dueños: registro del yate, HIN y seguro marítimo comercial (mín. $1,000,000).",
    formError: "No se pudo enviar. Inténtalo de nuevo.",
    joinSuccess:
      "Solicitud enviada. Te contactamos para verificar licencia y yate.",
    conciergeHello:
      "Soy el concierge de Kaenz. Dime Commute, Tour u Ocasión especial — origen, destino, pasajeros, duración y fecha. Te propongo un yate en el mundo.",
    conciergeMissingKey:
      "Falta XAI_API_KEY en el servidor. Añádela para activar Grok.",
    conciergeUnavailable:
      "El concierge no está disponible ahora. Reserva directo en la flota.",
    loginTitle: "Entra a la plataforma Kaenz",
    signupTitle: "Crea tu cuenta Kaenz",
    password: "Contraseña",
    passwordConfirm: "Confirmar contraseña",
    haveAccount: "¿Ya tienes cuenta? Entra",
    needAccount: "¿Eres nuevo? Crea una cuenta",
    loginCta: "Entrar",
    signupCta: "Crear cuenta",
    loginError: "Correo o contraseña incorrectos.",
    signupError: "No se pudo crear la cuenta.",
    passwordMismatch: "Las contraseñas no coinciden.",
    passwordShort: "Usa al menos 8 caracteres.",
    sessionNeeded: "Entra para abrir la plataforma Kaenz.",
    nameRequired: "El nombre completo es obligatorio.",
    googleCta: "Continuar con Gmail",
    orContinue: "o",
    googleError: "No se pudo entrar con Gmail. Inténtalo de nuevo o usa email y contraseña.",
    googleUnconfigured: "El acceso con Gmail no está disponible ahora. Usa email y contraseña.",
    googleDenied: "Cancelaste el acceso con Gmail. Inténtalo de nuevo o usa email y contraseña.",
    biometricEnter: "Entrar con el pulgar",
    biometricProcessing: "Esperando tu huella…",
    biometricRetry: "Vuelve a colocar el pulgar",
    biometricFailed: "No se pudo verificar la huella. Inténtalo de nuevo.",
    biometricUnavailable:
      "Este dispositivo no tiene huella, Face ID o Windows Hello disponible.",
    biometricExpired: "La sesión con huella expiró. Entra con email o Google.",
    biometricLockTitle: "Kaenz",
    biometricLockSubtitle: "Coloca tu pulgar en el sensor",
    biometricUsePassword: "Usar contraseña",
  },
  fr: {
    metaTitle: "Kaenz : trajet, croisière et occasion spéciale en yacht",
    metaDescription:
      "Kaenz est une plateforme yacht de bout en bout — pas un opérateur de charter — pour trajets, croisières et occasions spéciales dans le monde. Le prix dépend du type de voyage, de la durée, du yacht, des passagers et de la date. Paiement Stripe.",
    brand: "Kaenz",
    nav: {
      app: "Plateforme",
      fleet: "Yachts",
      book: "Réserver",
      concierge: "Concierge",
      join: "Rejoindre",
      terms: "Conditions",
      privacy: "Confidentialité",
      login: "Connexion",
      signup: "Créer un compte",
      logout: "Sortir",
    },
    heroTitle: "Évitez le trafic. Voyagez en yacht.",
    heroLead:
      "Trajets, croisières et célébrations sur l’eau. Immortalisez votre trajet, donnez des Vibes, inscrivez yachts et marinas — une seule plateforme.",
    heroCta: "Entrer dans la plateforme",
    heroSecondary: "Voir les yachts",
    platformEyebrow: "Dans Kaenz",
    platformTitle: "La plateforme, de bout en bout",
    platformLead:
      "Lieux, yachts, trajets en direct, selfies Crew et votre compte — l’eau, les gens, Stripe.",
    platformFeatures: [
      {
        title: "Lieux",
        body: "Touchez marinas et ports sur la carte. Les partenaires ajoutent leur marina ou port dans Lieux.",
        cta: "Ajouter une marina",
      },
      {
        title: "Yachts",
        body: "Capitaines vérifiés. Propriétaires et capitaines inscrivent un yacht dans Yachts et gagnent à chaque tarif.",
        cta: "Ajouter votre yacht",
      },
      {
        title: "Votre trajet",
        body: "Demandez, suivez en direct, payez avec Stripe et évaluez. Le tarif se répartit entre propriétaire, capitaine, marinas et Kaenz.",
        cta: "Démarrer un trajet",
      },
      {
        title: "Crew",
        body: "Immortalisez votre trajet avec un selfie, gagnez des Vibes et votez le Top 100 Selfies 2026.",
        cta: "Ouvrir Crew",
      },
      {
        title: "Compte",
        body: "Photo de profil, taille du texte et couleurs Kaenz — navy et cyan, à votre façon.",
        cta: "Votre compte",
      },
    ],
    crewSiteTitle: "Immortalisez votre trajet",
    crewSiteLead:
      "Téléchargez un selfie à bord, gagnez des Vibes et donnez-les à famille, partenaire, amis, collègues ou crush dans Drive Kaenz TopQ1.",
    crewSiteCta: "Ouvrir Top 100 Selfies",
    solveEyebrow: "Que résolvons-nous ?",
    solveLead:
      "L’eau est la façon la plus intelligente de se déplacer, de croiser et de célébrer — en South Florida et dans le monde.",
    pillars: [
      {
        title: "Gagnez du temps",
        body: "Économisez des heures de trafic et arrivez plus tôt, parce que rien ne vous barre la route.",
      },
      {
        title: "Élimine le stress",
        body: "Oubliez klaxons et frustration. Ici, la tranquillité et la paix abondent.",
      },
      {
        title: "Profitez du voyage",
        body: "Des milliers de milles navigables, de sandbars et de skylines à savourer.",
      },
    ],
    uniqueTitle: "Une plateforme, pas un charter.",
    uniqueBody:
      "Kaenz est une plateforme de bout en bout pour des trajets, croisières et occasions spéciales en yacht dans des marinas et ports du monde. Propriétaires, capitaines et marinas indépendants opèrent chaque trajet. Un algorithme fixe le prix selon le type de voyage, la durée, le yacht, les passagers et la date — paiement par Stripe.",
    tripTypesTitle: "Trajet, croisière et occasion spéciale",
    tripTypesLead:
      "Une plateforme pour arriver, rester sur l’eau et célébrer — partout où Kaenz a une marina ou un port.",
    tripTypes: [
      {
        title: "Trajet",
        body: "Gagnez sur les ponts et le trafic. Un saut en yacht avec capitaine plus rapide que la voiture.",
      },
      {
        title: "Croisière",
        body: "Sandbars, skyline, dock-and-dine et des heures sur l’eau à la destination choisie.",
      },
      {
        title: "Occasion spéciale",
        body: "Couchers de soleil, demandes, clients à bord et célébrations avec un capitaine vérifié.",
      },
    ],
    pricingTitle: "Comment le prix est fixé",
    pricingBody:
      "Un algorithme tarife chaque trajet selon le type, la durée, le yacht, le nombre de passagers et la date. Paiement Stripe. Répartition : propriétaire 38 %, capitaine 30 %, Kaenz 25 %, marina de départ 3,5 %, marina d’arrivée 3,5 %. Pourboire capitaine optionnel (15–20 %) en plus, versé directement au capitaine.",
    uniqueTerms: "Lire les conditions générales.",
    testimonialsTitle: "Que pensent nos clients ?",
    testimonials: [
      {
        quote:
          "Fort Lauderdale à Hollywood Beach en 35 minutes avec sandbar. Journée familiale parfaite !",
        name: "Mia Lee",
        city: "Fort Lauderdale",
      },
      {
        quote:
          "De Miami Beach à Brickell en 18 minutes en yacht. Adieu le trafic !",
        name: "William Brown",
        city: "Miami",
      },
      {
        quote:
          "De Fort Lauderdale à Palm Beach en 45 minutes au coucher du soleil. Romance inoubliable !",
        name: "Emily Johnson",
        city: "Palm Beach",
      },
    ],
    marinasTitle: "Marinas et ports",
    marinasBody:
      "Kaenz relie des yachts privés dans des marinas et ports du monde entier. Arrivez et partez par l’eau — de South Florida à la Méditerranée, aux Caraïbes et au-delà. Ouvrez la plateforme et ajoutez votre marina ou port dans Lieux.",
    marinasCta: "Ouvrir la plateforme et ajouter votre marina",
    joinTitle: "Vous possédez un yacht et vous êtes capitaine ?",
    joinCta: "Ouvrir la plateforme et ajouter votre yacht",
    joinLead:
      "Ouvrez Kaenz, allez dans Yachts, et inscrivez votre bateau avec un capitaine vérifié. Propriétaires et capitaines indépendants sont payés via Stripe à chaque trajet.",
    fleetTitle: "Choisissez votre yacht",
    fleetLead: "Privé, avec capitaine, prêt quand vous l’êtes.",
    from: "À partir de",
    guests: "invités",
    hours: "heures",
    bookNow: "Voir le yacht",
    requestPlatform: "Demander sur la plateforme",
    requestPlatformLead:
      "Les trajets se demandent dans Yachts Kaenz — capitaine vérifié, Stripe et suivi en direct.",
    bookStripe: "Réserver ce trajet — payer avec Stripe",
    bookStripeLead:
      "Choisissez Trajet, Tour ou Occasion spéciale. Payez en USD avec Stripe. Pas besoin de vous connecter à l’app.",
    bookableNow: "Réservable maintenant",
    catalogLabel: "Catalogue",
    catalogLead: "Catalogue marketing — pas d’inventaire en direct.",
    seeBookable: "Voir les yachts réservables",
    payStripe: "Payer avec Stripe",
    bookingConfirmed: "Trajet réservé",
    bookingReceipt: "Reçu Stripe",
    bookingProcessing: "Paiement reçu. Confirmation de la réservation…",
    bookingUnpaid: "Ce paiement n’a pas été terminé. Vous pouvez réserver depuis la fiche du yacht.",
    stripeMissing: "Stripe n’est pas configuré sur ce serveur.",
    guestEmail: "E-mail pour votre reçu",
    bookTitle: "Réserver un yacht privé",
    bookLead:
      "Demandez un trajet, une croisière ou une occasion spéciale. Capitaine vérifié inclus. Paiement Stripe, prix de l’algorithme.",
    form: {
      name: "Nom complet",
      email: "E-mail",
      phone: "Téléphone",
      kind: "Type de voyage",
      duration: "Durée (heures)",
      yacht: "Yacht",
      origin: "Marina de départ",
      destination: "Destination",
      date: "Date",
      time: "Heure",
      guests: "Invités",
      notes: "Notes",
      submit: "Demander une réservation",
      sending: "Envoi…",
      success: "Demande reçue. Un concierge Kaenz confirmera sous peu.",
    },
    conciergeTitle: "Concierge Kaenz",
    conciergeLead:
      "Planifiez un trajet, une croisière ou une occasion spéciale en yacht — dans le monde. Itinéraires, horaires et le bon bateau.",
    conciergePlaceholder: "Où voulez-vous aller, et quand ?",
    conciergeSend: "Envoyer",
    joinPageTitle: "Rejoindre la plateforme Kaenz",
    joinPageLead:
      "Ouvrez Kaenz pour publier ce que vous opérez. Propriétaires et capitaines ajoutent un yacht dans Yachts. Marinas et ports ajoutent leur lieu dans Lieux.",
    owner: "Propriétaire de yacht",
    captain: "Capitaine",
    both: "Propriétaire et capitaine",
    uscg: "Licence USCG (capitaines)",
    yachtName: "Nom du yacht",
    submitJoin: "Postuler",
    rights: "Tous droits réservés pour Salvazion Inc. 2026.",
    termsTitle: "Conditions générales",
    termsHref: "/terms",
    privacyTitle: "Politique de confidentialité",
    privacyHref: "/privacy",
    mapTitle: "Marinas et ports mondiaux Kaenz",
    mapWorld: "Monde",
    mapFlorida: "South Florida",
    legendMarina: "Marina",
    legendPort: "Port",
    legendPlace: "Arrivée",
    hubsLabel: "marinas et ports pour arrivées et départs en yacht",
    mapZoomIn: "Zoom avant",
    mapZoomOut: "Zoom arrière",
    mapNearMe: "Près de moi",
    liveTrip: "Trajet en cours",
    liveBadge: "En direct",
    liveAway: "À {n} min",
    liveFaster: "{n} min plus rapide qu’en voiture",
    liveArrived: "Arrivé — prêt à payer",
    appPreviewEyebrow: "Sur votre téléphone",
    appPreviewTitle: "Voyez le yacht aller de marina en marina",
    appPreviewLead:
      "La plateforme Kaenz sur mobile : choisissez une marina, embarquez et suivez le saut en direct pendant que la route reste bloquée.",
    appPreviewCta: "Ouvrir la plateforme",
    role: "Rôle",
    joinFee:
      "Paiement Stripe. Propriétaire 38 %. Capitaine 30 %. Kaenz 25 %. Marina de départ 3,5 %. Marina d’arrivée 3,5 %. Pourboire capitaine optionnel (15–20 %) versé directement au capitaine.",
    joinCaptains:
      "Capitaines : credencial USCG OUPV Six-Pack ou licence locale équivalente, plus vérification des antécédents.",
    joinOwners:
      "Propriétaires : immatriculation du yacht, HIN et assurance maritime commerciale (min. 1 000 000 $).",
    formError: "Envoi impossible. Réessayez.",
    joinSuccess:
      "Candidature reçue. Nous vous contactons pour vérifier licence et yacht.",
    conciergeHello:
      "Je suis le concierge Kaenz. Dites-moi trajet, croisière ou occasion spéciale — origine, destination, passagers, durée et date. Je vous propose un yacht dans le monde.",
    conciergeMissingKey:
      "XAI_API_KEY manquante sur le serveur. Ajoutez-la pour activer Grok.",
    conciergeUnavailable:
      "Le concierge n’est pas disponible pour le moment. Réservez directement dans la flotte.",
    loginTitle: "Entrer dans la plateforme Kaenz",
    signupTitle: "Créer votre compte Kaenz",
    password: "Mot de passe",
    passwordConfirm: "Confirmer le mot de passe",
    haveAccount: "Déjà un compte ? Connexion",
    needAccount: "Nouveau ? Créer un compte",
    loginCta: "Connexion",
    signupCta: "Créer un compte",
    loginError: "E-mail ou mot de passe incorrect.",
    signupError: "Impossible de créer le compte.",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    passwordShort: "Utilisez au moins 8 caractères.",
    sessionNeeded: "Connectez-vous pour ouvrir la plateforme Kaenz.",
    nameRequired: "Le nom complet est obligatoire.",
    googleCta: "Continuer avec Gmail",
    orContinue: "ou",
    googleError: "Connexion Gmail impossible. Réessayez, ou utilisez e-mail et mot de passe.",
    googleUnconfigured: "La connexion Gmail n'est pas disponible pour le moment. Utilisez e-mail et mot de passe.",
    googleDenied: "Connexion Gmail annulée. Réessayez, ou utilisez e-mail et mot de passe.",
    biometricEnter: "Entrer avec le pouce",
    biometricProcessing: "En attente de votre empreinte…",
    biometricRetry: "Replacez le pouce sur le capteur",
    biometricFailed: "Empreinte non vérifiée. Réessayez.",
    biometricUnavailable:
      "Cet appareil n’a pas d’empreinte, Face ID ou Windows Hello.",
    biometricExpired: "La session empreinte a expiré. Entrez avec e-mail ou Google.",
    biometricLockTitle: "Kaenz",
    biometricLockSubtitle: "Placez le pouce sur le capteur",
    biometricUsePassword: "Utiliser le mot de passe",
  },
  it: {
    metaTitle: "Kaenz: tragitto, tour e occasione speciale in yacht",
    metaDescription:
      "Kaenz è una piattaforma yacht end-to-end — non un operatore di charter — per tragitto, tour e occasione speciale nel mondo. Il prezzo dipende da tipo di viaggio, durata, yacht, passeggeri e data. Paghi con Stripe.",
    brand: "Kaenz",
    nav: {
      app: "Piattaforma",
      fleet: "Yacht",
      book: "Prenota",
      concierge: "Concierge",
      join: "Unisciti",
      terms: "Termini",
      privacy: "Privacy",
      login: "Accedi",
      signup: "Crea account",
      logout: "Esci",
    },
    heroTitle: "Salta il traffico. Viaggia in yacht.",
    heroLead:
      "Spostati, fai un tour e festeggia in acqua. Immortalizza il viaggio, dai Vibes, pubblica yacht e marine — una sola piattaforma.",
    heroCta: "Entra nella piattaforma",
    heroSecondary: "Vedi gli yacht",
    platformEyebrow: "Dentro Kaenz",
    platformTitle: "La piattaforma, da capo a fine",
    platformLead:
      "Luoghi, yacht, viaggi live, selfie Crew e il tuo account — acqua, persone e Stripe.",
    platformFeatures: [
      {
        title: "Luoghi",
        body: "Tocca marine e porti sulla mappa. I partner aggiungono marina o porto in Luoghi.",
        cta: "Aggiungi una marina",
      },
      {
        title: "Yacht",
        body: "Capitani verificati. Proprietari e capitani pubblicano uno yacht in Yacht e guadagnano su ogni tariffa.",
        cta: "Aggiungi il tuo yacht",
      },
      {
        title: "Il tuo viaggio",
        body: "Richiedi, segui in diretta, paga con Stripe e valuta. La tariffa si ripartisce tra proprietario, capitano, marine e Kaenz.",
        cta: "Inizia un viaggio",
      },
      {
        title: "Crew",
        body: "Immortalizza il viaggio con un selfie, guadagna Vibes e vota il Top 100 Selfies 2026.",
        cta: "Apri Crew",
      },
      {
        title: "Account",
        body: "Foto profilo, dimensione del testo e colori Kaenz — navy e cyan, a modo tuo.",
        cta: "Il tuo account",
      },
    ],
    crewSiteTitle: "Immortalizza il tuo viaggio",
    crewSiteLead:
      "Carica un selfie a bordo, guadagna Vibes e dalle a famiglia, partner, amici, colleghi o crush in Drive Kaenz TopQ1.",
    crewSiteCta: "Apri Top 100 Selfies",
    solveEyebrow: "Cosa risolviamo?",
    solveLead:
      "L’acqua è il modo più intelligente per spostarsi, fare un tour e festeggiare — in South Florida e nel mondo.",
    pillars: [
      {
        title: "Guadagna tempo",
        body: "Risparmia ore di traffico e arrivi prima, perché nulla ti si para davanti.",
      },
      {
        title: "Elimina lo stress",
        body: "Dimentica clacson e frustrazione. Qui abbondano tranquillità e pace.",
      },
      {
        title: "Goditi i viaggi",
        body: "Ci sono migliaia di miglia navigabili, sandbar e skyline da godere.",
      },
    ],
    uniqueTitle: "Una piattaforma, non un charter.",
    uniqueBody:
      "Kaenz è una piattaforma end-to-end per tragitto, tour e occasione speciale in yacht in marine e porti del mondo. Proprietari, capitani e marine indipendenti gestiscono ogni viaggio. Un algoritmo fissa il prezzo da tipo di viaggio, durata, yacht, passeggeri e data — paghi con Stripe.",
    tripTypesTitle: "Tragitto, tour e occasione speciale",
    tripTypesLead:
      "Una piattaforma per arrivare, restare in acqua e festeggiare — ovunque Kaenz abbia una marina o un porto.",
    tripTypes: [
      {
        title: "Tragitto",
        body: "Batti ponti e traffico. Un salto in yacht con capitano più veloce dell’auto.",
      },
      {
        title: "Tour",
        body: "Sandbar, skyline, dock-and-dine e ore in acqua nella destinazione che scegli.",
      },
      {
        title: "Occasione speciale",
        body: "Tramonti, proposte, clienti a bordo e celebrazioni con un capitano verificato.",
      },
    ],
    pricingTitle: "Come si calcola il prezzo",
    pricingBody:
      "Un algoritmo tarifa ogni viaggio da tipo, durata, yacht, numero di passeggeri e data. Paghi con Stripe. Ripartizione: proprietario 38%, capitano 30%, Kaenz 25%, marina di partenza 3,5%, marina di arrivo 3,5%. Mancia capitano opzionale (15–20%) in più, versata direttamente al capitano.",
    uniqueTerms: "Leggi i Termini e Condizioni.",
    testimonialsTitle: "Cosa pensano i nostri clienti?",
    testimonials: [
      {
        quote:
          "Da Fort Lauderdale a Hollywood Beach in 35 minuti con sandbar. Giornata in famiglia perfetta!",
        name: "Mia Lee",
        city: "Fort Lauderdale",
      },
      {
        quote:
          "Da Miami Beach a Brickell in 18 minuti in yacht. Addio traffico!",
        name: "William Brown",
        city: "Miami",
      },
      {
        quote:
          "Da Fort Lauderdale a Palm Beach in 45 minuti al tramonto. Romance indimenticabile!",
        name: "Emily Johnson",
        city: "Palm Beach",
      },
    ],
    marinasTitle: "Marine e porti",
    marinasBody:
      "Kaenz collega yacht privati in marine e porti di tutto il mondo. Arriva e parti via acqua — da South Florida al Mediterraneo, ai Caraibi e oltre. Apri la piattaforma e aggiungi la tua marina o porto in Luoghi.",
    marinasCta: "Apri la piattaforma e aggiungi la tua marina",
    joinTitle: "Possiedi uno yacht e sei un capitano?",
    joinCta: "Apri la piattaforma e aggiungi il tuo yacht",
    joinLead:
      "Apri Kaenz, vai in Yacht e pubblica la tua barca con capitano verificato. Proprietari e capitani indipendenti sono pagati con Stripe a ogni viaggio.",
    fleetTitle: "Scegli il tuo yacht",
    fleetLead: "Privato, con capitano, pronto quando lo sei tu.",
    from: "Da",
    guests: "ospiti",
    hours: "ore",
    bookNow: "Vedi yacht",
    requestPlatform: "Richiedi sulla piattaforma",
    requestPlatformLead:
      "I viaggi si richiedono in Yacht Kaenz — capitano verificato, Stripe e tracciamento in diretta.",
    bookStripe: "Prenota questo viaggio — paga con Stripe",
    bookStripeLead:
      "Scegli Commute, Tour o Occasione speciale. Paga in USD con Stripe. Non serve accedere all’app.",
    bookableNow: "Prenotabile ora",
    catalogLabel: "Catalogo",
    catalogLead: "Catalogo marketing — non è inventario live.",
    seeBookable: "Vedi yacht prenotabili",
    payStripe: "Paga con Stripe",
    bookingConfirmed: "Viaggio prenotato",
    bookingReceipt: "Ricevuta Stripe",
    bookingProcessing: "Pagamento ricevuto. Conferma della prenotazione…",
    bookingUnpaid: "Questo checkout non è stato completato. Puoi prenotare di nuovo dalla scheda dello yacht.",
    stripeMissing: "Stripe non è configurato su questo server.",
    guestEmail: "Email per la ricevuta",
    bookTitle: "Prenota uno yacht privato",
    bookLead:
      "Richiedi un tragitto, un tour o un’occasione speciale. Capitano verificato incluso. Pagamento Stripe, prezzo dell’algoritmo.",
    form: {
      name: "Nome completo",
      email: "Email",
      phone: "Telefono",
      kind: "Tipo di viaggio",
      duration: "Durata (ore)",
      yacht: "Yacht",
      origin: "Marina di partenza",
      destination: "Destinazione",
      date: "Data",
      time: "Ora",
      guests: "Ospiti",
      notes: "Note",
      submit: "Richiedi prenotazione",
      sending: "Invio…",
      success: "Richiesta ricevuta. Un concierge Kaenz confermerà a breve.",
    },
    conciergeTitle: "Concierge Kaenz",
    conciergeLead:
      "Pianifica un tragitto, un tour o un’occasione speciale in yacht — nel mondo. Rotte, orari e la barca giusta.",
    conciergePlaceholder: "Dove vuoi andare, e quando?",
    conciergeSend: "Invia",
    joinPageTitle: "Unisciti alla piattaforma Kaenz",
    joinPageLead:
      "Apri Kaenz per pubblicare ciò che operi. Proprietari e capitani aggiungono uno yacht in Yacht. Marine e porti aggiungono il loro luogo in Luoghi.",
    owner: "Proprietario di yacht",
    captain: "Capitano",
    both: "Proprietario e capitano",
    uscg: "Licenza USCG (capitani)",
    yachtName: "Nome dello yacht",
    submitJoin: "Candidati",
    rights: "Tutti i diritti riservati per Salvazion Inc. 2026.",
    termsTitle: "Termini e Condizioni",
    termsHref: "/terms",
    privacyTitle: "Informativa sulla privacy",
    privacyHref: "/privacy",
    mapTitle: "Marine e porti mondiali Kaenz",
    mapWorld: "Mondo",
    mapFlorida: "South Florida",
    legendMarina: "Marina",
    legendPort: "Porto",
    legendPlace: "Sbarco",
    hubsLabel: "marine e porti per arrivi e partenze in yacht",
    mapZoomIn: "Ingrandisci",
    mapZoomOut: "Riduci",
    mapNearMe: "Vicino a me",
    liveTrip: "Viaggio in corso",
    liveBadge: "Live",
    liveAway: "A {n} min",
    liveFaster: "{n} min più veloce dell’auto",
    liveArrived: "Arrivato — pronto a pagare",
    appPreviewEyebrow: "Sul tuo telefono",
    appPreviewTitle: "Guarda lo yacht da marina a marina",
    appPreviewLead:
      "La piattaforma Kaenz sul mobile: scegli una marina, sali e segui il salto in diretta mentre il traffico resta fermo.",
    appPreviewCta: "Apri la piattaforma",
    role: "Ruolo",
    joinFee:
      "Pagamento con Stripe. Proprietario 38%. Capitano 30%. Kaenz 25%. Marina di partenza 3,5%. Marina di arrivo 3,5%. Mancia capitano opzionale (15–20%) versata direttamente al capitano.",
    joinCaptains:
      "Capitani: credenziale USCG OUPV Six-Pack o licenza locale equivalente, più verifica dei precedenti.",
    joinOwners:
      "Proprietari: registrazione dello yacht, HIN e assicurazione marittima commerciale (min. $1,000,000).",
    formError: "Invio non riuscito. Riprova.",
    joinSuccess:
      "Candidatura ricevuta. Ti contatteremo per verificare licenza e yacht.",
    conciergeHello:
      "Sono il concierge Kaenz. Dimmi tragitto, tour o occasione speciale — origine, destinazione, passeggeri, durata e data. Ti propongo uno yacht nel mondo.",
    conciergeMissingKey:
      "Manca XAI_API_KEY sul server. Aggiungila per attivare Grok.",
    conciergeUnavailable:
      "Il concierge non è disponibile ora. Prenota direttamente dalla flotta.",
    loginTitle: "Entra nella piattaforma Kaenz",
    signupTitle: "Crea il tuo account Kaenz",
    password: "Password",
    passwordConfirm: "Conferma password",
    haveAccount: "Hai già un account? Accedi",
    needAccount: "Nuovo qui? Crea un account",
    loginCta: "Accedi",
    signupCta: "Crea account",
    loginError: "Email o password non corretti.",
    signupError: "Impossibile creare l’account.",
    passwordMismatch: "Le password non coincidono.",
    passwordShort: "Usa almeno 8 caratteri.",
    sessionNeeded: "Accedi per aprire la piattaforma Kaenz.",
    nameRequired: "Il nome completo è obbligatorio.",
    googleCta: "Continua con Gmail",
    orContinue: "oppure",
    googleError: "Accesso con Gmail non riuscito. Riprova, oppure usa email e password.",
    googleUnconfigured: "L'accesso con Gmail non è disponibile in questo momento. Usa email e password.",
    googleDenied: "Accesso Gmail annullato. Riprova, oppure usa email e password.",
    biometricEnter: "Entra con il pollice",
    biometricProcessing: "In attesa della tua impronta…",
    biometricRetry: "Riposiziona il pollice sul sensore",
    biometricFailed: "Impronta non verificata. Riprova.",
    biometricUnavailable:
      "Questo dispositivo non ha impronta, Face ID o Windows Hello.",
    biometricExpired: "La sessione con impronta è scaduta. Entra con email o Google.",
    biometricLockTitle: "Kaenz",
    biometricLockSubtitle: "Metti il pollice sul sensore",
    biometricUsePassword: "Usa la password",
  },
  pt: {
    metaTitle: "Kaenz: trajeto, passeio e ocasião especial de iate",
    metaDescription:
      "A Kaenz é uma plataforma integral de iates — não uma operadora de charter — para Trajeto, Passeio e Ocasião especial no mundo. O preço sai do tipo de viagem, duração, iate, passageiros e data. Você paga com Stripe.",
    brand: "Kaenz",
    nav: {
      app: "Plataforma",
      fleet: "Iates",
      book: "Reservar",
      concierge: "Concierge",
      join: "Junte-se",
      terms: "Termos",
      privacy: "Privacidade",
      login: "Entrar",
      signup: "Criar conta",
      logout: "Sair",
    },
    heroTitle: "Pule o trânsito. Viaje de iate.",
    heroLead:
      "Desloque-se, passeie e celebre na água. Imortalize a viagem, dê Vibes, anuncie iates e marinas — numa só plataforma.",
    heroCta: "Entrar na plataforma",
    heroSecondary: "Ver iates",
    platformEyebrow: "Dentro da Kaenz",
    platformTitle: "A plataforma, de ponta a ponta",
    platformLead:
      "Lugares, iates, viagens ao vivo, selfies da Crew e a sua conta — água, pessoas e Stripe.",
    platformFeatures: [
      {
        title: "Lugares",
        body: "Toque marinas e portos no mapa. Parceiros adicionam marina ou porto em Lugares.",
        cta: "Adicionar uma marina",
      },
      {
        title: "Iates",
        body: "Capitães verificados. Donos e capitães publicam um iate em Iates e ganham em cada tarifa.",
        cta: "Adicionar o seu iate",
      },
      {
        title: "Sua viagem",
        body: "Peça, acompanhe ao vivo, pague com Stripe e avalie. A tarifa reparte entre dono, capitão, marinas e Kaenz.",
        cta: "Começar uma viagem",
      },
      {
        title: "Crew",
        body: "Imortalize a viagem com um selfie, ganhe Vibes e vote o Top 100 Selfies 2026.",
        cta: "Abrir Crew",
      },
      {
        title: "Conta",
        body: "Foto de perfil, tamanho da letra e cores Kaenz — navy e ciano, do seu jeito.",
        cta: "Sua conta",
      },
    ],
    crewSiteTitle: "Imortalize sua viagem",
    crewSiteLead:
      "Envie um selfie a bordo, ganhe Vibes e dê a família, parceiro, amigos, colegas ou crush no Drive Kaenz TopQ1.",
    crewSiteCta: "Abrir Top 100 Selfies",
    solveEyebrow: "O que resolvemos?",
    solveLead:
      "A água é o jeito mais inteligente de se deslocar, passear e celebrar — no South Florida e no mundo.",
    pillars: [
      {
        title: "Ganhe tempo",
        body: "Economize horas de trânsito e chegue antes, porque nada fica no seu caminho.",
      },
      {
        title: "Elimina o estresse",
        body: "Esqueça buzinas e frustração. Aqui sobram tranquilidade e paz.",
      },
      {
        title: "Aproveite as viagens",
        body: "Há milhares de milhas navegáveis, sandbars e skylines para curtir.",
      },
    ],
    uniqueTitle: "Uma plataforma, não um charter.",
    uniqueBody:
      "A Kaenz é uma plataforma integral para viagens de iate de Trajeto, Passeio e Ocasião especial em marinas e portos do mundo. Donos, capitães e marinas independentes operam cada viagem. Um algoritmo define o preço pelo tipo de viagem, duração, tipo de iate, passageiros e data — e você paga com Stripe.",
    tripTypesTitle: "Trajeto, passeio e ocasião especial",
    tripTypesLead:
      "Uma plataforma para chegar, ficar na água e celebrar — onde a Kaenz tiver marina ou porto.",
    tripTypes: [
      {
        title: "Trajeto",
        body: "Ganhe das pontes e do trânsito. Um salto de iate com capitão mais rápido que o carro.",
      },
      {
        title: "Passeio",
        body: "Sandbars, skyline, dock-and-dine e horas na água no destino que você escolher.",
      },
      {
        title: "Ocasião especial",
        body: "Pores do sol, pedidos, clientes a bordo e celebrações com capitão verificado.",
      },
    ],
    pricingTitle: "Como o preço é definido",
    pricingBody:
      "Um algoritmo precifica cada viagem pelo tipo, duração, iate, número de passageiros e data. Você paga com Stripe. A divisão: dono do iate 38%, capitão 30%, Kaenz 25%, marina de partida 3,5%, marina de chegada 3,5%. Gorjeta opcional ao capitão (15–20%) entra por cima e vai direto ao capitão.",
    uniqueTerms: "Leia os Termos e Condições.",
    testimonialsTitle: "O que pensam os nossos clientes?",
    testimonials: [
      {
        quote:
          "De Fort Lauderdale a Hollywood Beach em 35 minutos com sandbar. Dia em família perfeito!",
        name: "Mia Lee",
        city: "Fort Lauderdale",
      },
      {
        quote: "De Miami Beach a Brickell em 18 minutos de iate. Adeus trânsito!",
        name: "William Brown",
        city: "Miami",
      },
      {
        quote:
          "De Fort Lauderdale a Palm Beach em 45 minutos ao pôr do sol. Romance inesquecível!",
        name: "Emily Johnson",
        city: "Palm Beach",
      },
    ],
    marinasTitle: "Marinas e portos",
    marinasBody:
      "A Kaenz conecta iates privados em marinas e portos do mundo. Chegue e saia pela água — do South Florida ao Mediterrâneo, ao Caribe e além. Abra a plataforma e adicione sua marina ou porto em Lugares.",
    marinasCta: "Abra a plataforma e adicione sua marina",
    joinTitle: "Você tem um iate e é capitão?",
    joinCta: "Abra a plataforma e adicione o seu iate",
    joinLead:
      "Abra a Kaenz, vá em Iates e publique o seu barco com capitão verificado. Donos e capitães independentes são pagos via Stripe em cada viagem.",
    fleetTitle: "Escolha o seu iate",
    fleetLead: "Privado, com capitão, pronto quando você estiver.",
    from: "A partir de",
    guests: "convidados",
    hours: "horas",
    bookNow: "Ver iate",
    requestPlatform: "Pedir na plataforma",
    requestPlatformLead:
      "As viagens pedem-se em Iates da Kaenz — capitão verificado, Stripe e acompanhamento ao vivo.",
    bookStripe: "Reserve esta viagem — pague com Stripe",
    bookStripeLead:
      "Escolha Trajeto, Passeio ou Ocasião especial. Pague em USD com Stripe. Não precisa entrar no app.",
    bookableNow: "Reservável agora",
    catalogLabel: "Catálogo",
    catalogLead: "Catálogo de marketing — não é inventário ao vivo.",
    seeBookable: "Ver iates reserváveis",
    payStripe: "Pagar com Stripe",
    bookingConfirmed: "Viagem reservada",
    bookingReceipt: "Recibo Stripe",
    bookingProcessing: "Pagamento recebido. A confirmar a reserva…",
    bookingUnpaid: "Este checkout não foi concluído. Pode reservar de novo na ficha do iate.",
    stripeMissing: "Stripe não está configurado neste servidor.",
    guestEmail: "Email para o recibo",
    bookTitle: "Reserve um iate privado",
    bookLead:
      "Solicite Trajeto, Passeio ou Ocasião especial. Capitão verificado incluso. Pagamento Stripe, preço do algoritmo.",
    form: {
      name: "Nome completo",
      email: "E-mail",
      phone: "Telefone",
      kind: "Tipo de viagem",
      duration: "Duração (horas)",
      yacht: "Iate",
      origin: "Marina de partida",
      destination: "Destino",
      date: "Data",
      time: "Hora",
      guests: "Convidados",
      notes: "Notas",
      submit: "Solicitar reserva",
      sending: "Enviando…",
      success: "Pedido recebido. Um concierge Kaenz confirmará em breve.",
    },
    conciergeTitle: "Concierge Kaenz",
    conciergeLead:
      "Planeje Trajeto, Passeio ou Ocasião especial de iate — no mundo. Rotas, horários e o barco certo.",
    conciergePlaceholder: "Para onde você quer ir, e quando?",
    conciergeSend: "Enviar",
    joinPageTitle: "Junte-se à plataforma Kaenz",
    joinPageLead:
      "Abra a Kaenz para publicar o que você opera. Donos e capitães adicionam um iate em Iates. Marinas e portos adicionam o lugar em Lugares.",
    owner: "Dono de iate",
    captain: "Capitão",
    both: "Dono e capitão",
    uscg: "Licença USCG (capitães)",
    yachtName: "Nome do iate",
    submitJoin: "Candidatar-se",
    rights: "Todos os direitos reservados para Salvazion Inc. 2026.",
    termsTitle: "Termos e Condições",
    termsHref: "/terms",
    privacyTitle: "Política de Privacidade",
    privacyHref: "/privacy",
    mapTitle: "Marinas e portos mundiais Kaenz",
    mapWorld: "Mundo",
    mapFlorida: "South Florida",
    legendMarina: "Marina",
    legendPort: "Porto",
    legendPlace: "Destino",
    hubsLabel: "marinas e portos para chegadas e partidas de iate",
    mapZoomIn: "Aproximar",
    mapZoomOut: "Afastar",
    mapNearMe: "Perto de mim",
    liveTrip: "Viagem em andamento",
    liveBadge: "Ao vivo",
    liveAway: "A {n} min",
    liveFaster: "{n} min mais rápido que de carro",
    liveArrived: "Chegou — pronto para pagar",
    appPreviewEyebrow: "No seu celular",
    appPreviewTitle: "Veja o iate ir de marina em marina",
    appPreviewLead:
      "A plataforma Kaenz no celular: escolha uma marina, embarque e acompanhe o salto ao vivo enquanto o trânsito fica parado.",
    appPreviewCta: "Abrir a plataforma",
    role: "Função",
    joinFee:
      "Cobrado com Stripe. Dono 38%. Capitão 30%. Kaenz 25%. Marina de partida 3,5%. Marina de chegada 3,5%. Gorjeta opcional ao capitão (15–20%) vai direto ao capitão.",
    joinCaptains:
      "Capitães: credencial USCG OUPV Six-Pack ou licença local equivalente, mais verificação de antecedentes.",
    joinOwners:
      "Donos: registro do iate, HIN e seguro marítimo comercial (mín. US$ 1.000.000).",
    formError: "Não foi possível enviar. Tente de novo.",
    joinSuccess:
      "Candidatura recebida. Vamos contactá-lo para verificar licença e iate.",
    conciergeHello:
      "Sou o concierge Kaenz. Diga Trajeto, Passeio ou Ocasião especial — origem, destino, passageiros, duração e data. Eu combino um iate no mundo.",
    conciergeMissingKey:
      "Falta XAI_API_KEY no servidor. Adicione-a para ativar o Grok.",
    conciergeUnavailable:
      "O concierge está indisponível agora. Reserve direto pela frota.",
    loginTitle: "Entre na plataforma Kaenz",
    signupTitle: "Crie a sua conta Kaenz",
    password: "Senha",
    passwordConfirm: "Confirmar senha",
    haveAccount: "Já tem conta? Entrar",
    needAccount: "Novo por aqui? Criar uma conta",
    loginCta: "Entrar",
    signupCta: "Criar conta",
    loginError: "E-mail ou senha incorretos.",
    signupError: "Não foi possível criar a conta.",
    passwordMismatch: "As senhas não coincidem.",
    passwordShort: "Use pelo menos 8 caracteres.",
    sessionNeeded: "Entre para abrir a plataforma Kaenz.",
    nameRequired: "O nome completo é obrigatório.",
    googleCta: "Continuar com Gmail",
    orContinue: "ou",
    googleError: "Não foi possível entrar com Gmail. Tente de novo ou use e-mail e senha.",
    googleUnconfigured: "O acesso com Gmail não está disponível agora. Use e-mail e senha.",
    googleDenied: "O acesso com Gmail foi cancelado. Tente de novo ou use e-mail e senha.",
    biometricEnter: "Entrar com o polegar",
    biometricProcessing: "Aguardando sua digital…",
    biometricRetry: "Coloque o polegar no sensor de novo",
    biometricFailed: "Não foi possível verificar a digital. Tente de novo.",
    biometricUnavailable:
      "Este dispositivo não tem digital, Face ID ou Windows Hello.",
    biometricExpired: "A sessão com digital expirou. Entre com email ou Google.",
    biometricLockTitle: "Kaenz",
    biometricLockSubtitle: "Coloque o polegar no sensor",
    biometricUsePassword: "Usar senha",
  },
} as const;

export function t(locale: Locale) {
  return copy[locale];
}
