import type { Locale } from "./locale";

const names: Record<string, Record<Locale, string>> = {
  "United States": { en: "United States", es: "Estados Unidos", fr: "États-Unis", it: "Stati Uniti", pt: "Estados Unidos" },
  Canada: { en: "Canada", es: "Canadá", fr: "Canada", it: "Canada", pt: "Canadá" },
  "U.S. Virgin Islands": {
    en: "U.S. Virgin Islands",
    es: "Islas Vírgenes de EE. UU.",
    fr: "Îles Vierges des États-Unis",
    it: "Isole Vergini americane",
    pt: "Ilhas Virgens Americanas",
  },
  "British Virgin Islands": {
    en: "British Virgin Islands",
    es: "Islas Vírgenes Británicas",
    fr: "Îles Vierges britanniques",
    it: "Isole Vergini britanniche",
    pt: "Ilhas Virgens Britânicas",
  },
  Bahamas: { en: "Bahamas", es: "Bahamas", fr: "Bahamas", it: "Bahamas", pt: "Bahamas" },
  "Saint Barthélemy": {
    en: "Saint Barthélemy",
    es: "San Bartolomé",
    fr: "Saint-Barthélemy",
    it: "Saint-Barthélemy",
    pt: "São Bartolomeu",
  },
  "Sint Maarten": { en: "Sint Maarten", es: "Sint Maarten", fr: "Saint-Martin", it: "Sint Maarten", pt: "Sint Maarten" },
  "Saint Martin": { en: "Saint Martin", es: "San Martín", fr: "Saint-Martin", it: "Saint-Martin", pt: "São Martinho" },
  "Antigua and Barbuda": {
    en: "Antigua and Barbuda",
    es: "Antigua y Barbuda",
    fr: "Antigua-et-Barbuda",
    it: "Antigua e Barbuda",
    pt: "Antígua e Barbuda",
  },
  "Saint Lucia": { en: "Saint Lucia", es: "Santa Lucía", fr: "Sainte-Lucie", it: "Santa Lucia", pt: "Santa Lúcia" },
  Barbados: { en: "Barbados", es: "Barbados", fr: "Barbade", it: "Barbados", pt: "Barbados" },
  Martinique: { en: "Martinique", es: "Martinica", fr: "Martinique", it: "Martinica", pt: "Martinica" },
  Guadeloupe: { en: "Guadeloupe", es: "Guadalupe", fr: "Guadeloupe", it: "Guadalupa", pt: "Guadalupe" },
  Grenada: { en: "Grenada", es: "Granada", fr: "Grenade", it: "Grenada", pt: "Granada" },
  "Trinidad and Tobago": {
    en: "Trinidad and Tobago",
    es: "Trinidad y Tobago",
    fr: "Trinité-et-Tobago",
    it: "Trinidad e Tobago",
    pt: "Trinidad e Tobago",
  },
  "Dominican Republic": {
    en: "Dominican Republic",
    es: "República Dominicana",
    fr: "République dominicaine",
    it: "Repubblica Dominicana",
    pt: "República Dominicana",
  },
  "Puerto Rico": { en: "Puerto Rico", es: "Puerto Rico", fr: "Porto Rico", it: "Porto Rico", pt: "Porto Rico" },
  Jamaica: { en: "Jamaica", es: "Jamaica", fr: "Jamaïque", it: "Giamaica", pt: "Jamaica" },
  "Cayman Islands": {
    en: "Cayman Islands",
    es: "Islas Caimán",
    fr: "Îles Caïmans",
    it: "Isole Cayman",
    pt: "Ilhas Cayman",
  },
  "Turks and Caicos": {
    en: "Turks and Caicos",
    es: "Islas Turcas y Caicos",
    fr: "Îles Turques-et-Caïques",
    it: "Turks e Caicos",
    pt: "Ilhas Turks e Caicos",
  },
  Bermuda: { en: "Bermuda", es: "Bermudas", fr: "Bermudes", it: "Bermuda", pt: "Bermudas" },
  Curaçao: { en: "Curaçao", es: "Curazao", fr: "Curaçao", it: "Curaçao", pt: "Curaçao" },
  Aruba: { en: "Aruba", es: "Aruba", fr: "Aruba", it: "Aruba", pt: "Aruba" },
  Bonaire: { en: "Bonaire", es: "Bonaire", fr: "Bonaire", it: "Bonaire", pt: "Bonaire" },
  Mexico: { en: "Mexico", es: "México", fr: "Mexique", it: "Messico", pt: "México" },
  Panama: { en: "Panama", es: "Panamá", fr: "Panama", it: "Panama", pt: "Panamá" },
  "Costa Rica": { en: "Costa Rica", es: "Costa Rica", fr: "Costa Rica", it: "Costa Rica", pt: "Costa Rica" },
  Honduras: { en: "Honduras", es: "Honduras", fr: "Honduras", it: "Honduras", pt: "Honduras" },
  Belize: { en: "Belize", es: "Belice", fr: "Belize", it: "Belize", pt: "Belize" },
  Guatemala: { en: "Guatemala", es: "Guatemala", fr: "Guatemala", it: "Guatemala", pt: "Guatemala" },
  Colombia: { en: "Colombia", es: "Colombia", fr: "Colombie", it: "Colombia", pt: "Colômbia" },
  Brazil: { en: "Brazil", es: "Brasil", fr: "Brésil", it: "Brasile", pt: "Brasil" },
  Argentina: { en: "Argentina", es: "Argentina", fr: "Argentine", it: "Argentina", pt: "Argentina" },
  Uruguay: { en: "Uruguay", es: "Uruguay", fr: "Uruguay", it: "Uruguay", pt: "Uruguai" },
  Chile: { en: "Chile", es: "Chile", fr: "Chili", it: "Cile", pt: "Chile" },
  Peru: { en: "Peru", es: "Perú", fr: "Pérou", it: "Perù", pt: "Peru" },
  Ecuador: { en: "Ecuador", es: "Ecuador", fr: "Équateur", it: "Ecuador", pt: "Equador" },
  Monaco: { en: "Monaco", es: "Mónaco", fr: "Monaco", it: "Monaco", pt: "Mônaco" },
  France: { en: "France", es: "Francia", fr: "France", it: "Francia", pt: "França" },
  Spain: { en: "Spain", es: "España", fr: "Espagne", it: "Spagna", pt: "Espanha" },
  Italy: { en: "Italy", es: "Italia", fr: "Italie", it: "Italia", pt: "Itália" },
  Greece: { en: "Greece", es: "Grecia", fr: "Grèce", it: "Grecia", pt: "Grécia" },
  Croatia: { en: "Croatia", es: "Croacia", fr: "Croatie", it: "Croazia", pt: "Croácia" },
  Montenegro: { en: "Montenegro", es: "Montenegro", fr: "Monténégro", it: "Montenegro", pt: "Montenegro" },
  Albania: { en: "Albania", es: "Albania", fr: "Albanie", it: "Albania", pt: "Albânia" },
  "Bosnia and Herzegovina": {
    en: "Bosnia and Herzegovina",
    es: "Bosnia y Herzegovina",
    fr: "Bosnie-Herzégovine",
    it: "Bosnia ed Erzegovina",
    pt: "Bósnia e Herzegovina",
  },
  Slovenia: { en: "Slovenia", es: "Eslovenia", fr: "Slovénie", it: "Slovenia", pt: "Eslovênia" },
  Gibraltar: { en: "Gibraltar", es: "Gibraltar", fr: "Gibraltar", it: "Gibilterra", pt: "Gibraltar" },
  Malta: { en: "Malta", es: "Malta", fr: "Malte", it: "Malta", pt: "Malta" },
  Portugal: { en: "Portugal", es: "Portugal", fr: "Portugal", it: "Portogallo", pt: "Portugal" },
  "United Kingdom": {
    en: "United Kingdom",
    es: "Reino Unido",
    fr: "Royaume-Uni",
    it: "Regno Unito",
    pt: "Reino Unido",
  },
  Ireland: { en: "Ireland", es: "Irlanda", fr: "Irlande", it: "Irlanda", pt: "Irlanda" },
  Netherlands: { en: "Netherlands", es: "Países Bajos", fr: "Pays-Bas", it: "Paesi Bassi", pt: "Países Baixos" },
  Belgium: { en: "Belgium", es: "Bélgica", fr: "Belgique", it: "Belgio", pt: "Bélgica" },
  Germany: { en: "Germany", es: "Alemania", fr: "Allemagne", it: "Germania", pt: "Alemanha" },
  Denmark: { en: "Denmark", es: "Dinamarca", fr: "Danemark", it: "Danimarca", pt: "Dinamarca" },
  Norway: { en: "Norway", es: "Noruega", fr: "Norvège", it: "Norvegia", pt: "Noruega" },
  Sweden: { en: "Sweden", es: "Suecia", fr: "Suède", it: "Svezia", pt: "Suécia" },
  Finland: { en: "Finland", es: "Finlandia", fr: "Finlande", it: "Finlandia", pt: "Finlândia" },
  Estonia: { en: "Estonia", es: "Estonia", fr: "Estonie", it: "Estonia", pt: "Estônia" },
  Latvia: { en: "Latvia", es: "Letonia", fr: "Lettonie", it: "Lettonia", pt: "Letônia" },
  Poland: { en: "Poland", es: "Polonia", fr: "Pologne", it: "Polonia", pt: "Polônia" },
  Russia: { en: "Russia", es: "Rusia", fr: "Russie", it: "Russia", pt: "Rússia" },
  Turkey: { en: "Turkey", es: "Turquía", fr: "Turquie", it: "Turchia", pt: "Turquia" },
  Cyprus: { en: "Cyprus", es: "Chipre", fr: "Chypre", it: "Cipro", pt: "Chipre" },
  Israel: { en: "Israel", es: "Israel", fr: "Israël", it: "Israele", pt: "Israel" },
  "United Arab Emirates": {
    en: "United Arab Emirates",
    es: "Emiratos Árabes Unidos",
    fr: "Émirats arabes unis",
    it: "Emirati Arabi Uniti",
    pt: "Emirados Árabes Unidos",
  },
  Qatar: { en: "Qatar", es: "Catar", fr: "Qatar", it: "Qatar", pt: "Catar" },
  Bahrain: { en: "Bahrain", es: "Baréin", fr: "Bahreïn", it: "Bahrein", pt: "Bahrein" },
  Oman: { en: "Oman", es: "Omán", fr: "Oman", it: "Oman", pt: "Omã" },
  "Saudi Arabia": {
    en: "Saudi Arabia",
    es: "Arabia Saudita",
    fr: "Arabie saoudite",
    it: "Arabia Saudita",
    pt: "Arábia Saudita",
  },
  Morocco: { en: "Morocco", es: "Marruecos", fr: "Maroc", it: "Marocco", pt: "Marrocos" },
  Tunisia: { en: "Tunisia", es: "Túnez", fr: "Tunisie", it: "Tunisia", pt: "Tunísia" },
  Egypt: { en: "Egypt", es: "Egipto", fr: "Égypte", it: "Egitto", pt: "Egito" },
  "South Africa": {
    en: "South Africa",
    es: "Sudáfrica",
    fr: "Afrique du Sud",
    it: "Sudafrica",
    pt: "África do Sul",
  },
  Namibia: { en: "Namibia", es: "Namibia", fr: "Namibie", it: "Namibia", pt: "Namíbia" },
  Nigeria: { en: "Nigeria", es: "Nigeria", fr: "Nigeria", it: "Nigeria", pt: "Nigéria" },
  Senegal: { en: "Senegal", es: "Senegal", fr: "Sénégal", it: "Senegal", pt: "Senegal" },
  Kenya: { en: "Kenya", es: "Kenia", fr: "Kenya", it: "Kenya", pt: "Quênia" },
  Tanzania: { en: "Tanzania", es: "Tanzania", fr: "Tanzanie", it: "Tanzania", pt: "Tanzânia" },
  Seychelles: { en: "Seychelles", es: "Seychelles", fr: "Seychelles", it: "Seychelles", pt: "Seicheles" },
  Mauritius: { en: "Mauritius", es: "Mauricio", fr: "Maurice", it: "Mauritius", pt: "Maurício" },
  Singapore: { en: "Singapore", es: "Singapur", fr: "Singapour", it: "Singapore", pt: "Singapura" },
  "Hong Kong": { en: "Hong Kong", es: "Hong Kong", fr: "Hong Kong", it: "Hong Kong", pt: "Hong Kong" },
  Thailand: { en: "Thailand", es: "Tailandia", fr: "Thaïlande", it: "Thailandia", pt: "Tailândia" },
  Malaysia: { en: "Malaysia", es: "Malasia", fr: "Malaisie", it: "Malaysia", pt: "Malásia" },
  Indonesia: { en: "Indonesia", es: "Indonesia", fr: "Indonésie", it: "Indonesia", pt: "Indonésia" },
  Philippines: { en: "Philippines", es: "Filipinas", fr: "Philippines", it: "Filippine", pt: "Filipinas" },
  India: { en: "India", es: "India", fr: "Inde", it: "India", pt: "Índia" },
  Maldives: { en: "Maldives", es: "Maldivas", fr: "Maldives", it: "Maldive", pt: "Maldivas" },
  "Sri Lanka": { en: "Sri Lanka", es: "Sri Lanka", fr: "Sri Lanka", it: "Sri Lanka", pt: "Sri Lanka" },
  Japan: { en: "Japan", es: "Japón", fr: "Japon", it: "Giappone", pt: "Japão" },
  "South Korea": { en: "South Korea", es: "Corea del Sur", fr: "Corée du Sud", it: "Corea del Sud", pt: "Coreia do Sul" },
  China: { en: "China", es: "China", fr: "Chine", it: "Cina", pt: "China" },
  Taiwan: { en: "Taiwan", es: "Taiwán", fr: "Taïwan", it: "Taiwan", pt: "Taiwan" },
  Australia: { en: "Australia", es: "Australia", fr: "Australie", it: "Australia", pt: "Austrália" },
  "New Zealand": { en: "New Zealand", es: "Nueva Zelanda", fr: "Nouvelle-Zélande", it: "Nuova Zelanda", pt: "Nova Zelândia" },
  "French Polynesia": {
    en: "French Polynesia",
    es: "Polinesia Francesa",
    fr: "Polynésie française",
    it: "Polinesia francese",
    pt: "Polinésia Francesa",
  },
  "New Caledonia": {
    en: "New Caledonia",
    es: "Nueva Caledonia",
    fr: "Nouvelle-Calédonie",
    it: "Nuova Caledonia",
    pt: "Nova Caledônia",
  },
  Fiji: { en: "Fiji", es: "Fiyi", fr: "Fidji", it: "Figi", pt: "Fiji" },
  Vanuatu: { en: "Vanuatu", es: "Vanuatu", fr: "Vanuatu", it: "Vanuatu", pt: "Vanuatu" },
  Samoa: { en: "Samoa", es: "Samoa", fr: "Samoa", it: "Samoa", pt: "Samoa" },
  "American Samoa": {
    en: "American Samoa",
    es: "Samoa Americana",
    fr: "Samoa américaines",
    it: "Samoa Americane",
    pt: "Samoa Americana",
  },
  Guam: { en: "Guam", es: "Guam", fr: "Guam", it: "Guam", pt: "Guam" },
  "Northern Mariana Islands": {
    en: "Northern Mariana Islands",
    es: "Islas Marianas del Norte",
    fr: "Îles Mariannes du Nord",
    it: "Isole Marianne Settentrionali",
    pt: "Ilhas Marianas do Norte",
  },
};

export function countryName(country: string, locale: Locale) {
  return names[country]?.[locale] || country;
}
