import type { Locale } from "./locale";

const names: Record<string, Record<Locale, string>> = {
  "United States": { en: "United States", es: "Estados Unidos", fr: "États-Unis", it: "Stati Uniti" },
  Canada: { en: "Canada", es: "Canadá", fr: "Canada", it: "Canada" },
  "U.S. Virgin Islands": {
    en: "U.S. Virgin Islands",
    es: "Islas Vírgenes de EE. UU.",
    fr: "Îles Vierges des États-Unis",
    it: "Isole Vergini americane",
  },
  "British Virgin Islands": {
    en: "British Virgin Islands",
    es: "Islas Vírgenes Británicas",
    fr: "Îles Vierges britanniques",
    it: "Isole Vergini britanniche",
  },
  Bahamas: { en: "Bahamas", es: "Bahamas", fr: "Bahamas", it: "Bahamas" },
  "Saint Barthélemy": {
    en: "Saint Barthélemy",
    es: "San Bartolomé",
    fr: "Saint-Barthélemy",
    it: "Saint-Barthélemy",
  },
  "Sint Maarten": { en: "Sint Maarten", es: "Sint Maarten", fr: "Saint-Martin", it: "Sint Maarten" },
  "Saint Martin": { en: "Saint Martin", es: "San Martín", fr: "Saint-Martin", it: "Saint-Martin" },
  "Antigua and Barbuda": {
    en: "Antigua and Barbuda",
    es: "Antigua y Barbuda",
    fr: "Antigua-et-Barbuda",
    it: "Antigua e Barbuda",
  },
  "Saint Lucia": { en: "Saint Lucia", es: "Santa Lucía", fr: "Sainte-Lucie", it: "Santa Lucia" },
  Barbados: { en: "Barbados", es: "Barbados", fr: "Barbade", it: "Barbados" },
  Martinique: { en: "Martinique", es: "Martinica", fr: "Martinique", it: "Martinica" },
  Guadeloupe: { en: "Guadeloupe", es: "Guadalupe", fr: "Guadeloupe", it: "Guadalupa" },
  Grenada: { en: "Grenada", es: "Granada", fr: "Grenade", it: "Grenada" },
  "Trinidad and Tobago": {
    en: "Trinidad and Tobago",
    es: "Trinidad y Tobago",
    fr: "Trinité-et-Tobago",
    it: "Trinidad e Tobago",
  },
  "Dominican Republic": {
    en: "Dominican Republic",
    es: "República Dominicana",
    fr: "République dominicaine",
    it: "Repubblica Dominicana",
  },
  "Puerto Rico": { en: "Puerto Rico", es: "Puerto Rico", fr: "Porto Rico", it: "Porto Rico" },
  Jamaica: { en: "Jamaica", es: "Jamaica", fr: "Jamaïque", it: "Giamaica" },
  "Cayman Islands": {
    en: "Cayman Islands",
    es: "Islas Caimán",
    fr: "Îles Caïmans",
    it: "Isole Cayman",
  },
  "Turks and Caicos": {
    en: "Turks and Caicos",
    es: "Islas Turcas y Caicos",
    fr: "Îles Turques-et-Caïques",
    it: "Turks e Caicos",
  },
  Bermuda: { en: "Bermuda", es: "Bermudas", fr: "Bermudes", it: "Bermuda" },
  Curaçao: { en: "Curaçao", es: "Curazao", fr: "Curaçao", it: "Curaçao" },
  Aruba: { en: "Aruba", es: "Aruba", fr: "Aruba", it: "Aruba" },
  Bonaire: { en: "Bonaire", es: "Bonaire", fr: "Bonaire", it: "Bonaire" },
  Mexico: { en: "Mexico", es: "México", fr: "Mexique", it: "Messico" },
  Panama: { en: "Panama", es: "Panamá", fr: "Panama", it: "Panama" },
  "Costa Rica": { en: "Costa Rica", es: "Costa Rica", fr: "Costa Rica", it: "Costa Rica" },
  Honduras: { en: "Honduras", es: "Honduras", fr: "Honduras", it: "Honduras" },
  Belize: { en: "Belize", es: "Belice", fr: "Belize", it: "Belize" },
  Guatemala: { en: "Guatemala", es: "Guatemala", fr: "Guatemala", it: "Guatemala" },
  Colombia: { en: "Colombia", es: "Colombia", fr: "Colombie", it: "Colombia" },
  Brazil: { en: "Brazil", es: "Brasil", fr: "Brésil", it: "Brasile" },
  Argentina: { en: "Argentina", es: "Argentina", fr: "Argentine", it: "Argentina" },
  Uruguay: { en: "Uruguay", es: "Uruguay", fr: "Uruguay", it: "Uruguay" },
  Chile: { en: "Chile", es: "Chile", fr: "Chili", it: "Cile" },
  Peru: { en: "Peru", es: "Perú", fr: "Pérou", it: "Perù" },
  Ecuador: { en: "Ecuador", es: "Ecuador", fr: "Équateur", it: "Ecuador" },
  Monaco: { en: "Monaco", es: "Mónaco", fr: "Monaco", it: "Monaco" },
  France: { en: "France", es: "Francia", fr: "France", it: "Francia" },
  Spain: { en: "Spain", es: "España", fr: "Espagne", it: "Spagna" },
  Italy: { en: "Italy", es: "Italia", fr: "Italie", it: "Italia" },
  Greece: { en: "Greece", es: "Grecia", fr: "Grèce", it: "Grecia" },
  Croatia: { en: "Croatia", es: "Croacia", fr: "Croatie", it: "Croazia" },
  Montenegro: { en: "Montenegro", es: "Montenegro", fr: "Monténégro", it: "Montenegro" },
  Albania: { en: "Albania", es: "Albania", fr: "Albanie", it: "Albania" },
  "Bosnia and Herzegovina": {
    en: "Bosnia and Herzegovina",
    es: "Bosnia y Herzegovina",
    fr: "Bosnie-Herzégovine",
    it: "Bosnia ed Erzegovina",
  },
  Slovenia: { en: "Slovenia", es: "Eslovenia", fr: "Slovénie", it: "Slovenia" },
  Gibraltar: { en: "Gibraltar", es: "Gibraltar", fr: "Gibraltar", it: "Gibilterra" },
  Malta: { en: "Malta", es: "Malta", fr: "Malte", it: "Malta" },
  Portugal: { en: "Portugal", es: "Portugal", fr: "Portugal", it: "Portogallo" },
  "United Kingdom": {
    en: "United Kingdom",
    es: "Reino Unido",
    fr: "Royaume-Uni",
    it: "Regno Unito",
  },
  Ireland: { en: "Ireland", es: "Irlanda", fr: "Irlande", it: "Irlanda" },
  Netherlands: { en: "Netherlands", es: "Países Bajos", fr: "Pays-Bas", it: "Paesi Bassi" },
  Belgium: { en: "Belgium", es: "Bélgica", fr: "Belgique", it: "Belgio" },
  Germany: { en: "Germany", es: "Alemania", fr: "Allemagne", it: "Germania" },
  Denmark: { en: "Denmark", es: "Dinamarca", fr: "Danemark", it: "Danimarca" },
  Norway: { en: "Norway", es: "Noruega", fr: "Norvège", it: "Norvegia" },
  Sweden: { en: "Sweden", es: "Suecia", fr: "Suède", it: "Svezia" },
  Finland: { en: "Finland", es: "Finlandia", fr: "Finlande", it: "Finlandia" },
  Estonia: { en: "Estonia", es: "Estonia", fr: "Estonie", it: "Estonia" },
  Latvia: { en: "Latvia", es: "Letonia", fr: "Lettonie", it: "Lettonia" },
  Poland: { en: "Poland", es: "Polonia", fr: "Pologne", it: "Polonia" },
  Russia: { en: "Russia", es: "Rusia", fr: "Russie", it: "Russia" },
  Turkey: { en: "Turkey", es: "Turquía", fr: "Turquie", it: "Turchia" },
  Cyprus: { en: "Cyprus", es: "Chipre", fr: "Chypre", it: "Cipro" },
  Israel: { en: "Israel", es: "Israel", fr: "Israël", it: "Israele" },
  "United Arab Emirates": {
    en: "United Arab Emirates",
    es: "Emiratos Árabes Unidos",
    fr: "Émirats arabes unis",
    it: "Emirati Arabi Uniti",
  },
  Qatar: { en: "Qatar", es: "Catar", fr: "Qatar", it: "Qatar" },
  Bahrain: { en: "Bahrain", es: "Baréin", fr: "Bahreïn", it: "Bahrein" },
  Oman: { en: "Oman", es: "Omán", fr: "Oman", it: "Oman" },
  "Saudi Arabia": {
    en: "Saudi Arabia",
    es: "Arabia Saudita",
    fr: "Arabie saoudite",
    it: "Arabia Saudita",
  },
  Morocco: { en: "Morocco", es: "Marruecos", fr: "Maroc", it: "Marocco" },
  Tunisia: { en: "Tunisia", es: "Túnez", fr: "Tunisie", it: "Tunisia" },
  Egypt: { en: "Egypt", es: "Egipto", fr: "Égypte", it: "Egitto" },
  "South Africa": {
    en: "South Africa",
    es: "Sudáfrica",
    fr: "Afrique du Sud",
    it: "Sudafrica",
  },
  Namibia: { en: "Namibia", es: "Namibia", fr: "Namibie", it: "Namibia" },
  Nigeria: { en: "Nigeria", es: "Nigeria", fr: "Nigeria", it: "Nigeria" },
  Senegal: { en: "Senegal", es: "Senegal", fr: "Sénégal", it: "Senegal" },
  Kenya: { en: "Kenya", es: "Kenia", fr: "Kenya", it: "Kenya" },
  Tanzania: { en: "Tanzania", es: "Tanzania", fr: "Tanzanie", it: "Tanzania" },
  Seychelles: { en: "Seychelles", es: "Seychelles", fr: "Seychelles", it: "Seychelles" },
  Mauritius: { en: "Mauritius", es: "Mauricio", fr: "Maurice", it: "Mauritius" },
  Singapore: { en: "Singapore", es: "Singapur", fr: "Singapour", it: "Singapore" },
  "Hong Kong": { en: "Hong Kong", es: "Hong Kong", fr: "Hong Kong", it: "Hong Kong" },
  Thailand: { en: "Thailand", es: "Tailandia", fr: "Thaïlande", it: "Thailandia" },
  Malaysia: { en: "Malaysia", es: "Malasia", fr: "Malaisie", it: "Malaysia" },
  Indonesia: { en: "Indonesia", es: "Indonesia", fr: "Indonésie", it: "Indonesia" },
  Philippines: { en: "Philippines", es: "Filipinas", fr: "Philippines", it: "Filippine" },
  India: { en: "India", es: "India", fr: "Inde", it: "India" },
  Maldives: { en: "Maldives", es: "Maldivas", fr: "Maldives", it: "Maldive" },
  "Sri Lanka": { en: "Sri Lanka", es: "Sri Lanka", fr: "Sri Lanka", it: "Sri Lanka" },
  Japan: { en: "Japan", es: "Japón", fr: "Japon", it: "Giappone" },
  "South Korea": { en: "South Korea", es: "Corea del Sur", fr: "Corée du Sud", it: "Corea del Sud" },
  China: { en: "China", es: "China", fr: "Chine", it: "Cina" },
  Taiwan: { en: "Taiwan", es: "Taiwán", fr: "Taïwan", it: "Taiwan" },
  Australia: { en: "Australia", es: "Australia", fr: "Australie", it: "Australia" },
  "New Zealand": { en: "New Zealand", es: "Nueva Zelanda", fr: "Nouvelle-Zélande", it: "Nuova Zelanda" },
  "French Polynesia": {
    en: "French Polynesia",
    es: "Polinesia Francesa",
    fr: "Polynésie française",
    it: "Polinesia francese",
  },
  "New Caledonia": {
    en: "New Caledonia",
    es: "Nueva Caledonia",
    fr: "Nouvelle-Calédonie",
    it: "Nuova Caledonia",
  },
  Fiji: { en: "Fiji", es: "Fiyi", fr: "Fidji", it: "Figi" },
  Vanuatu: { en: "Vanuatu", es: "Vanuatu", fr: "Vanuatu", it: "Vanuatu" },
  Samoa: { en: "Samoa", es: "Samoa", fr: "Samoa", it: "Samoa" },
  "American Samoa": {
    en: "American Samoa",
    es: "Samoa Americana",
    fr: "Samoa américaines",
    it: "Samoa Americane",
  },
  Guam: { en: "Guam", es: "Guam", fr: "Guam", it: "Guam" },
  "Northern Mariana Islands": {
    en: "Northern Mariana Islands",
    es: "Islas Marianas del Norte",
    fr: "Îles Mariannes du Nord",
    it: "Isole Marianne Settentrionali",
  },
};

export function countryName(country: string, locale: Locale) {
  return names[country]?.[locale] || country;
}
