import type { Place } from "./places";

export const FEATURED_KINDS = ["sandbar", "beach", "dine", "scenic"] as const;
export type FeaturedKind = (typeof FEATURED_KINDS)[number];

export const featuredPlaces: Place[] = [
  {
    id: "haulover-sandbar",
    kind: "place",
    featured: "beach",
    name: "Haulover Sandbar",
    city: "North Miami Beach",
    country: "United States",
    lat: 25.9075,
    lng: -80.1235,
    image: "/featured/haulover-sandbar.jpg",
    minutesByYacht: 28,
    minutesByCar: 0,
    blurb: {
      en: "Miami’s social sandbar inside Haulover Inlet — waist-deep water and weekend raft-ups.",
      es: "El sandbar social de Miami junto a Haulover Inlet: agua a la cintura y botes anclados.",
      fr: "Le sandbar social de Miami dans Haulover Inlet — eau à la taille et bateaux à l’ancre.",
      it: "Il sandbar sociale di Miami dentro Haulover Inlet: acqua alla vita e barche all’ancora.",
      pt: "O sandbar social de Miami em Haulover Inlet — água na cintura e barcos fundeados.",
    },
  },
  {
    id: "hollywood-sandbar",
    kind: "place",
    featured: "sandbar",
    name: "Hollywood Beach Sandbar",
    city: "Hollywood",
    country: "United States",
    lat: 26.021,
    lng: -80.114,
    image: "/featured/hollywood-sandbar.jpg",
    minutesByYacht: 35,
    minutesByCar: 0,
    blurb: {
      en: "Family sandbar off Hollywood Beach — anchor, swim, and paddle from Fort Lauderdale.",
      es: "Sandbar familiar frente a Hollywood Beach: ancla, nado y paddle desde Fort Lauderdale.",
      fr: "Sandbar familial au large d’Hollywood Beach — ancrez et nagez depuis Fort Lauderdale.",
      it: "Sandbar in famiglia al largo di Hollywood Beach: ancora e nuoto da Fort Lauderdale.",
      pt: "Sandbar em família em Hollywood Beach — ancore e nade desde Fort Lauderdale.",
    },
  },
  {
    id: "ses-illetes",
    kind: "place",
    featured: "sandbar",
    name: "Ses Illetes",
    city: "Formentera",
    country: "Spain",
    lat: 38.7617,
    lng: 1.4333,
    image: "/featured/ses-illetes.jpg",
    minutesByYacht: 40,
    minutesByCar: 0,
    blurb: {
      en: "White sand spit and turquoise shallows — the classic Formentera anchorage from Ibiza.",
      es: "Lengua de arena blanca y aguas turquesa: el fondeo clásico de Formentera desde Ibiza.",
      fr: "Langue de sable blanc et eaux turquoise — le mouillage classique de Formentera.",
      it: "Lingua di sabbia bianca e acqua turchese: l’ancoraggio classico di Formentera.",
      pt: "Faixa de areia branca e água turquesa — o fundeadouro clássico de Formentera.",
    },
  },
  {
    id: "cala-comte",
    kind: "place",
    featured: "sandbar",
    name: "Cala Comte",
    city: "Ibiza",
    country: "Spain",
    lat: 38.961,
    lng: 1.219,
    image: "/featured/cala-comte.jpg",
    minutesByYacht: 25,
    minutesByCar: 0,
    blurb: {
      en: "West Ibiza coves for sunset anchoring — limestone cliffs and clear Mediterranean water.",
      es: "Caldas del oeste de Ibiza para fondear al atardecer: acantilados y agua clara.",
      fr: "Cales de l’ouest d’Ibiza pour un mouillage au coucher du soleil.",
      it: "Cale dell’ovest di Ibiza per l’ancoraggio al tramonto.",
      pt: "Enseadas do oeste de Ibiza para fundear ao pôr do sol.",
    },
  },
  {
    id: "south-beach",
    kind: "place",
    featured: "beach",
    name: "South Beach / Lummus Park",
    city: "Miami Beach",
    country: "United States",
    lat: 25.7826,
    lng: -80.134,
    image: "/featured/south-beach.jpg",
    minutesByYacht: 10,
    minutesByCar: 25,
    blurb: {
      en: "Arrive by water to Lummus Park and the Art Deco hotels — skip the Ocean Drive valet line.",
      es: "Llega por agua a Lummus Park y los hoteles Art Déco. Sin fila de valet en Ocean Drive.",
      fr: "Arrivez par l’eau à Lummus Park et aux hôtels Art déco.",
      it: "Arriva via acqua a Lummus Park e agli hotel Art Déco.",
      pt: "Chegue pela água ao Lummus Park e aos hotéis Art Déco.",
    },
  },
  {
    id: "crandon-park",
    kind: "place",
    featured: "beach",
    name: "Crandon Park Beach",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.712,
    lng: -80.1539,
    image: "/featured/crandon-park.jpg",
    minutesByYacht: 22,
    minutesByCar: 35,
    blurb: {
      en: "Key Biscayne’s wide park beach — calm water, pines, and a marina at the north end.",
      es: "La playa-parque de Key Biscayne: agua calma, pinos y marina al norte.",
      fr: "La plage-parc de Key Biscayne — eau calme, pins et marina au nord.",
      it: "La spiaggia-parco di Key Biscayne: acqua calma, pini e marina a nord.",
      pt: "A praia-parque de Key Biscayne — água calma, pinheiros e marina ao norte.",
    },
  },
  {
    id: "nixon-sandbar",
    kind: "place",
    featured: "beach",
    name: "Nixon Sandbar",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.6786,
    lng: -80.1624,
    image: "/featured/nixon-sandbar.jpg",
    minutesByYacht: 20,
    minutesByCar: 0,
    blurb: {
      en: "Boat-only sandbar off Key Biscayne — shallow Biscayne Bay flats with Miami skyline views.",
      es: "Sandbar solo en bote frente a Key Biscayne: bajos de Biscayne Bay y skyline de Miami.",
      fr: "Sandbar accessible seulement en bateau au large de Key Biscayne, vue sur Miami.",
      it: "Sandbar solo in barca al largo di Key Biscayne, con skyline di Miami.",
      pt: "Sandbar só de barco em Key Biscayne — baixios da Biscayne Bay e skyline de Miami.",
    },
  },
  {
    id: "stiltsville",
    kind: "place",
    featured: "beach",
    name: "Stiltsville",
    city: "Biscayne Bay",
    country: "United States",
    lat: 25.653,
    lng: -80.175,
    image: "/featured/stiltsville.jpg",
    minutesByYacht: 35,
    minutesByCar: 0,
    blurb: {
      en: "Historic houses on stilts in Biscayne National Park — a slow scenic run south of Key Biscayne.",
      es: "Casas sobre pilotes en Biscayne National Park: crucero lento al sur de Key Biscayne.",
      fr: "Maisons sur pilotis dans Biscayne National Park, au sud de Key Biscayne.",
      it: "Case su palafitte a Biscayne National Park, a sud di Key Biscayne.",
      pt: "Casas sobre palafitas no Biscayne National Park, ao sul de Key Biscayne.",
    },
  },
  {
    id: "lake-sylvia",
    kind: "place",
    featured: "beach",
    name: "Lake Sylvia",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.10466,
    lng: -80.11154,
    image: "/featured/lake-sylvia.jpg",
    minutesByYacht: 10,
    minutesByCar: 0,
    blurb: {
      en: "Quiet lake off the Intracoastal near Harbor Beach — docks, calm water, and a short hop from Las Olas.",
      es: "Lago tranquilo junto al Intracoastal cerca de Harbor Beach, a un salto de Las Olas.",
      fr: "Lac calme près de l’Intracoastal à Harbor Beach, tout près de Las Olas.",
      it: "Lago calmo sull’Intracoastal a Harbor Beach, a un salto da Las Olas.",
      pt: "Lago calmo no Intracoastal junto a Harbor Beach, perto de Las Olas.",
    },
  },
  {
    id: "lake-boca-raton",
    kind: "place",
    featured: "beach",
    name: "Lake Boca Raton",
    city: "Boca Raton",
    country: "United States",
    lat: 26.347,
    lng: -80.078,
    image: "/featured/lake-boca-raton.jpg",
    minutesByYacht: 18,
    minutesByCar: 0,
    blurb: {
      en: "Wide lake inside the Boca Raton inlet — anchor in protected water before the Atlantic.",
      es: "Lago amplio dentro de la entrada de Boca Raton: fondea al abrigo antes del Atlántico.",
      fr: "Grand lac à l’intérieur de l’inlet de Boca Raton — mouillage protégé avant l’Atlantique.",
      it: "Ampio lago dentro l’inlet di Boca Raton: ancoraggio riparato prima dell’Atlantico.",
      pt: "Lago amplo na entrada de Boca Raton — fundeio protegido antes do Atlântico.",
    },
  },
  {
    id: "maule-lake",
    kind: "place",
    featured: "beach",
    name: "Maule Lake",
    city: "North Miami Beach",
    country: "United States",
    lat: 25.935,
    lng: -80.151,
    image: "/featured/maule-lake.jpg",
    minutesByYacht: 22,
    minutesByCar: 0,
    blurb: {
      en: "Residential lake off the Intracoastal in Eastern Shores — calm water just west of Sunny Isles.",
      es: "Lago residencial del Intracoastal en Eastern Shores, al oeste de Sunny Isles.",
      fr: "Lac résidentiel de l’Intracoastal à Eastern Shores, à l’ouest de Sunny Isles.",
      it: "Lago residenziale sull’Intracoastal a Eastern Shores, a ovest di Sunny Isles.",
      pt: "Lago residencial no Intracoastal em Eastern Shores, a oeste de Sunny Isles.",
    },
  },
  {
    id: "john-u-lloyd",
    kind: "place",
    featured: "beach",
    name: "John U. Lloyd State Park",
    city: "Dania Beach",
    country: "United States",
    lat: 26.071,
    lng: -80.111,
    image: "/featured/john-u-lloyd.jpg",
    minutesByYacht: 16,
    minutesByCar: 25,
    blurb: {
      en: "Wild beach and Whiskey Creek at Port Everglades — dunes, pines, and a quiet inlet.",
      es: "Playa natural y Whiskey Creek en Port Everglades: dunas, pinos y un inlet tranquilo.",
      fr: "Plage naturelle et Whiskey Creek à Port Everglades — dunes, pins et inlet calme.",
      it: "Spiaggia naturale e Whiskey Creek a Port Everglades: dune, pini e inlet calmo.",
      pt: "Praia natural e Whiskey Creek em Port Everglades — dunas, pinheiros e inlet calmo.",
    },
  },
  {
    id: "no-name-harbor",
    kind: "place",
    featured: "beach",
    name: "No Name Harbor",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.6768,
    lng: -80.1628,
    image: "/featured/no-name-harbor.jpg",
    minutesByYacht: 24,
    minutesByCar: 0,
    blurb: {
      en: "Day-use harbor inside Bill Baggs — tie to the wall and walk to Cape Florida beach.",
      es: "Puerto de día en Bill Baggs: amarra al muro y camina a la playa de Cape Florida.",
      fr: "Port à la journée dans Bill Baggs — amarrez au quai et gagnez Cape Florida à pied.",
      it: "Porto diurna a Bill Baggs: ormeggia al muro e cammina fino a Cape Florida.",
      pt: "Porto de dia em Bill Baggs — atraque no muro e caminhe até Cape Florida.",
    },
  },
  {
    id: "bill-baggs",
    kind: "place",
    featured: "beach",
    name: "Bill Baggs Cape Florida State Park",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.6735,
    lng: -80.1573,
    image: "/featured/bill-baggs.jpg",
    minutesByYacht: 24,
    minutesByCar: 40,
    blurb: {
      en: "Cape Florida Lighthouse and Atlantic beach at the south tip of Key Biscayne.",
      es: "Faro de Cape Florida y playa atlántica en la punta sur de Key Biscayne.",
      fr: "Phare de Cape Florida et plage atlantique à la pointe sud de Key Biscayne.",
      it: "Faro di Cape Florida e spiaggia atlantica sulla punta sud di Key Biscayne.",
      pt: "Farol de Cape Florida e praia atlântica na ponta sul de Key Biscayne.",
    },
  },
  {
    id: "hollywood-broadwalk",
    kind: "place",
    featured: "beach",
    name: "Hollywood Beach Broadwalk",
    city: "Hollywood",
    country: "United States",
    lat: 26.011,
    lng: -80.117,
    image: "/featured/hollywood-broadwalk.jpg",
    minutesByYacht: 30,
    minutesByCar: 20,
    blurb: {
      en: "Palm promenade and Atlantic sand — arrive by water and walk the Broadwalk.",
      es: "Paseo de palmeras y arena atlántica: llega por agua y camina el Broadwalk.",
      fr: "Promenade des palmiers et sable atlantique — arrivez par l’eau.",
      it: "Passeggiata delle palme e sabbia atlantica: arriva via acqua.",
      pt: "Calçadão de palmeiras e areia atlântica — chegue pela água.",
    },
  },
  {
    id: "pompano-beach",
    kind: "place",
    featured: "beach",
    name: "Pompano Beach",
    city: "Pompano Beach",
    country: "United States",
    lat: 26.234,
    lng: -80.09,
    image: "/featured/pompano-beach.jpg",
    minutesByYacht: 28,
    minutesByCar: 22,
    blurb: {
      en: "Long Atlantic beach and pier north of Fort Lauderdale — an easy Intracoastal hop.",
      es: "Playa atlántica y muelle al norte de Fort Lauderdale, un salto por el Intracoastal.",
      fr: "Plage atlantique et jetée au nord de Fort Lauderdale, un saut par l’Intracoastal.",
      it: "Spiaggia atlantica e pier a nord di Fort Lauderdale, un salto sull’Intracoastal.",
      pt: "Praia atlântica e píer ao norte de Fort Lauderdale, um salto pelo Intracoastal.",
    },
  },
  {
    id: "deerfield-beach",
    kind: "place",
    featured: "beach",
    name: "Deerfield Beach",
    city: "Deerfield Beach",
    country: "United States",
    lat: 26.318,
    lng: -80.075,
    image: "/featured/deerfield-beach.jpg",
    minutesByYacht: 35,
    minutesByCar: 28,
    blurb: {
      en: "Family beach and fishing pier on the Broward–Palm Beach line.",
      es: "Playa familiar y muelle de pesca en la línea Broward–Palm Beach.",
      fr: "Plage familiale et jetée de pêche à la limite Broward–Palm Beach.",
      it: "Spiaggia per famiglie e pier da pesca sul confine Broward–Palm Beach.",
      pt: "Praia familiar e píer de pesca na linha Broward–Palm Beach.",
    },
  },
  {
    id: "bal-harbour-beach",
    kind: "place",
    featured: "beach",
    name: "Bal Harbour Beach",
    city: "Bal Harbour",
    country: "United States",
    lat: 25.899,
    lng: -80.123,
    image: "/featured/bal-harbour-beach.jpg",
    minutesByYacht: 18,
    minutesByCar: 20,
    blurb: {
      en: "Quiet Atlantic sand just south of Haulover Inlet — a short run from Miami Beach.",
      es: "Arena atlántica tranquila al sur de Haulover Inlet, un salto desde Miami Beach.",
      fr: "Sable atlantique calme au sud de Haulover Inlet, tout près de Miami Beach.",
      it: "Sabbia atlantica tranquilla a sud di Haulover Inlet, a un salto da Miami Beach.",
      pt: "Areia atlântica calma ao sul de Haulover Inlet, perto de Miami Beach.",
    },
  },
  {
    id: "sunny-isles-beach",
    kind: "place",
    featured: "beach",
    name: "Sunny Isles Beach",
    city: "Sunny Isles Beach",
    country: "United States",
    lat: 25.95,
    lng: -80.121,
    image: "/featured/sunny-isles-beach.jpg",
    minutesByYacht: 22,
    minutesByCar: 25,
    blurb: {
      en: "Condo skyline and Atlantic beach north of Haulover — arrive along the Intracoastal.",
      es: "Skyline de condos y playa atlántica al norte de Haulover, por el Intracoastal.",
      fr: "Skyline de condos et plage atlantique au nord de Haulover, via l’Intracoastal.",
      it: "Skyline di condo e spiaggia atlantica a nord di Haulover, via Intracoastal.",
      pt: "Skyline de condos e praia atlântica ao norte de Haulover, pelo Intracoastal.",
    },
  },
  {
    id: "fort-lauderdale-beach",
    kind: "place",
    featured: "beach",
    name: "Fort Lauderdale Beach",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.122,
    lng: -80.104,
    image: "/featured/fort-lauderdale-beach.jpg",
    minutesByYacht: 14,
    minutesByCar: 15,
    blurb: {
      en: "A1A Wave Wall, palms, and Atlantic sand — drop by water instead of the beach traffic.",
      es: "Wave Wall de A1A, palmeras y arena atlántica: llega por agua, no por el tráfico.",
      fr: "Wave Wall d’A1A, palmiers et sable atlantique — arrivez par l’eau.",
      it: "Wave Wall di A1A, palme e sabbia atlantica: arriva via acqua.",
      pt: "Wave Wall da A1A, palmeiras e areia atlântica — chegue pela água.",
    },
  },
  {
    id: "hugh-taylor-birch",
    kind: "place",
    featured: "beach",
    name: "Hugh Taylor Birch State Park",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.145,
    lng: -80.104,
    image: "/featured/hugh-taylor-birch.jpg",
    minutesByYacht: 16,
    minutesByCar: 18,
    blurb: {
      en: "Barrier-island park between the Atlantic and a mangrove lagoon on the Intracoastal.",
      es: "Parque entre el Atlántico y una laguna de manglar en el Intracoastal.",
      fr: "Parc entre l’Atlantique et une lagune de palétuviers sur l’Intracoastal.",
      it: "Parco tra Atlantico e laguna di mangrovie sull’Intracoastal.",
      pt: "Parque entre o Atlântico e uma lagoa de mangue no Intracoastal.",
    },
  },
  {
    id: "barceloneta-beach",
    kind: "place",
    featured: "beach",
    name: "Barceloneta Beach",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3768,
    lng: 2.1925,
    image: "/featured/barceloneta.jpg",
    minutesByYacht: 15,
    minutesByCar: 28,
    blurb: {
      en: "City beach beside Port Vell — step off the yacht into Barcelona’s waterfront barrio.",
      es: "Playa urbana junto a Port Vell: del yate al barrio marítimo de Barcelona.",
      fr: "Plage urbaine à Port Vell — du yacht au quartier maritime de Barcelone.",
      it: "Spiaggia urbana a Port Vell: dallo yacht al quartiere marittimo di Barcellona.",
      pt: "Praia urbana em Port Vell — do iate ao bairro marítimo de Barcelona.",
    },
  },
  {
    id: "cannes-croisette",
    kind: "place",
    featured: "beach",
    name: "La Croisette",
    city: "Cannes",
    country: "France",
    lat: 43.5507,
    lng: 7.0174,
    image: "/featured/cannes-croisette.jpg",
    minutesByYacht: 12,
    minutesByCar: 20,
    blurb: {
      en: "Palm promenade, palace hotels, and beach clubs on the Bay of Cannes.",
      es: "Paseo de palmeras, hoteles palacio y beach clubs en la bahía de Cannes.",
      fr: "Promenade des palmiers, palaces et plages privées sur la baie de Cannes.",
      it: "Passeggiata delle palme, hotel palazzo e spiagge sulla baia di Cannes.",
      pt: "Calçadão de palmeiras, hotéis palácio e beach clubs na baía de Cannes.",
    },
  },
  {
    id: "montys-grove",
    kind: "place",
    featured: "dine",
    name: "Monty's Raw Bar",
    city: "Coconut Grove",
    country: "United States",
    lat: 25.7285,
    lng: -80.238,
    image: "/featured/montys.jpg",
    minutesByYacht: 18,
    minutesByCar: 22,
    blurb: {
      en: "Dock-and-dine on Biscayne Bay since 1969 — tiki deck, raw bar, and slips at the Grove.",
      es: "Dock & dine en Biscayne Bay desde 1969: terraza tiki, raw bar y amarres en The Grove.",
      fr: "Dock & dine sur Biscayne Bay depuis 1969 — terrasse tiki et pontons à Coconut Grove.",
      it: "Dock & dine su Biscayne Bay dal 1969: terrazza tiki e ormeggi a Coconut Grove.",
      pt: "Dock & dine em Biscayne Bay desde 1969 — deck tiki e vagas em Coconut Grove.",
    },
  },
  {
    id: "fifteenth-street-fisheries",
    kind: "place",
    featured: "dine",
    name: "15th Street Fisheries",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.1033,
    lng: -80.1188,
    image: "/featured/fifteenth-street.jpg",
    minutesByYacht: 12,
    minutesByCar: 18,
    blurb: {
      en: "Seafood at Lauderdale Marina — free dockage on the Intracoastal and tarpon at the docks.",
      es: "Mariscos en Lauderdale Marina: atraque en el Intracoastal y sábalos en los muelles.",
      fr: "Fruits de mer à Lauderdale Marina — pontons sur l’Intracoastal et tarpons aux docks.",
      it: "Pesce a Lauderdale Marina: ormeggio sull’Intracoastal e tarpon ai pontili.",
      pt: "Frutos do mar na Lauderdale Marina — atracação no Intracoastal e tarpons nos cais.",
    },
  },
  {
    id: "shooters-waterfront",
    kind: "place",
    featured: "dine",
    name: "Shooters Waterfront",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.167,
    lng: -80.106,
    image: "/featured/shooters.jpg",
    minutesByYacht: 16,
    minutesByCar: 18,
    blurb: {
      en: "Intracoastal icon since 1982 — 340 feet of dock, brunch, and boats pulling up for lunch.",
      es: "Ícono del Intracoastal desde 1982: 340 pies de muelle, brunch y botes al almuerzo.",
      fr: "Icône de l’Intracoastal depuis 1982 — 340 pieds de ponton et brunch au fil de l’eau.",
      it: "Icona dell’Intracoastal dal 1982: 340 piedi di pontile e brunch in barca.",
      pt: "Ícone do Intracoastal desde 1982 — 340 pés de cais e brunch de barco.",
    },
  },
  {
    id: "coconuts",
    kind: "place",
    featured: "dine",
    name: "Coconuts",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.118,
    lng: -80.107,
    image: "/featured/coconuts.jpg",
    minutesByYacht: 12,
    minutesByCar: 12,
    blurb: {
      en: "Dockside seafood by Bahia Mar — Scoobies, sunset, and a short hop from Fort Lauderdale Beach.",
      es: "Mariscos junto a Bahia Mar: Scoobies, atardecer y un salto a Fort Lauderdale Beach.",
      fr: "Fruits de mer près de Bahia Mar — Scoobies, sunset, tout près de la plage.",
      it: "Pesce a Bahia Mar: Scoobies, tramonto e un salto dalla spiaggia.",
      pt: "Frutos do mar em Bahia Mar — Scoobies, pôr do sol e um salto da praia.",
    },
  },
  {
    id: "boatyard",
    kind: "place",
    featured: "dine",
    name: "Boatyard",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.101,
    lng: -80.122,
    image: "/featured/boatyard.jpg",
    minutesByYacht: 10,
    minutesByCar: 14,
    blurb: {
      en: "Coastal dining on 17th Street — dock slips for yachts and an Intracoastal patio.",
      es: "Cocina costera en 17th Street: amarres para yates y terraza al Intracoastal.",
      fr: "Table côtière sur 17th Street — pontons pour yachts et terrasse sur l’Intracoastal.",
      it: "Cucina costiera su 17th Street: ormeggi per yacht e terrazza sull’Intracoastal.",
      pt: "Cozinha costeira na 17th Street — vagas para iates e terraço no Intracoastal.",
    },
  },
  {
    id: "kaluz",
    kind: "place",
    featured: "dine",
    name: "Kaluz Restaurant",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.188,
    lng: -80.106,
    image: "/featured/kaluz.jpg",
    minutesByYacht: 18,
    minutesByCar: 16,
    blurb: {
      en: "Surf and turf on the west bank of the Intracoastal, a stone’s throw from Lauderdale-by-the-Sea.",
      es: "Surf and turf en la orilla oeste del Intracoastal, junto a Lauderdale-by-the-Sea.",
      fr: "Surf and turf sur la rive ouest de l’Intracoastal, près de Lauderdale-by-the-Sea.",
      it: "Surf and turf sulla riva ovest dell’Intracoastal, vicino a Lauderdale-by-the-Sea.",
      pt: "Surf and turf na margem oeste do Intracoastal, perto de Lauderdale-by-the-Sea.",
    },
  },
  {
    id: "caps-place",
    kind: "place",
    featured: "dine",
    name: "Cap's Place",
    city: "Lighthouse Point",
    country: "United States",
    lat: 26.282,
    lng: -80.092,
    image: "/featured/caps-place.jpg",
    minutesByYacht: 28,
    minutesByCar: 0,
    blurb: {
      en: "1920s island speakeasy — dock nearby and take the launch for crab cakes at Broward’s oldest restaurant.",
      es: "Speakeasy isleño de los años 20: amarra cerca y cruza en lancha al restaurante más antiguo de Broward.",
      fr: "Speakeasy insulaire des années 20 — accostez et prenez la navette vers le plus vieux restaurant de Broward.",
      it: "Speakeasy sull’isola anni 20: ormeggia e prendi il lancio verso il ristorante più antico di Broward.",
      pt: "Speakeasy numa ilha dos anos 20 — atraque e pegue a lancha até o restaurante mais antigo de Broward.",
    },
  },
  {
    id: "boathouse-riverside",
    kind: "place",
    featured: "dine",
    name: "Boathouse at the Riverside",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.1197,
    lng: -80.137,
    image: "/featured/boathouse-riverside.jpg",
    minutesByYacht: 14,
    minutesByCar: 12,
    blurb: {
      en: "New River patio downtown — tie up and watch the water taxi pass Las Olas.",
      es: "Terraza en el New River del centro: amarra y mira el water taxi pasar por Las Olas.",
      fr: "Terrasse sur la New River en centre-ville — amarrez et voyez le water taxi à Las Olas.",
      it: "Terrazza sul New River in centro: ormeggia e guarda il water taxi a Las Olas.",
      pt: "Terraço no New River no centro — atraque e veja o water taxi em Las Olas.",
    },
  },
  {
    id: "ocean-prime",
    kind: "place",
    featured: "dine",
    name: "Ocean Prime",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.119,
    lng: -80.109,
    image: "/featured/ocean-prime.jpg",
    minutesByYacht: 12,
    minutesByCar: 14,
    blurb: {
      en: "Steak and seafood at Las Olas Marina — two terraces over the megayacht basin.",
      es: "Carne y mariscos en Las Olas Marina: dos terrazas sobre la dársena de megayates.",
      fr: "Viandes et fruits de mer à Las Olas Marina — deux terrasses sur le bassin des mégayachts.",
      it: "Carne e pesce a Las Olas Marina: due terrazze sul bacino dei megayacht.",
      pt: "Carne e frutos do mar na Las Olas Marina — dois terraços sobre a dársena de megaiates.",
    },
  },
  {
    id: "billys-stone-crab",
    kind: "place",
    featured: "dine",
    name: "Billy's Stone Crab",
    city: "Hollywood",
    country: "United States",
    lat: 26.013,
    lng: -80.118,
    image: "/featured/billys-stone-crab.jpg",
    minutesByYacht: 22,
    minutesByCar: 20,
    blurb: {
      en: "Stone crab on the Hollywood Intracoastal — 150 feet of dock and claws in season.",
      es: "Stone crab en el Intracoastal de Hollywood: 150 pies de muelle y pinzas en temporada.",
      fr: "Stone crab sur l’Intracoastal d’Hollywood — 150 pieds de ponton et pinces en saison.",
      it: "Stone crab sull’Intracoastal di Hollywood: 150 piedi di pontile e chele in stagione.",
      pt: "Stone crab no Intracoastal de Hollywood — 150 pés de cais e garras na temporada.",
    },
  },
  {
    id: "rustic-inn",
    kind: "place",
    featured: "dine",
    name: "Rustic Inn Crabhouse",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.068,
    lng: -80.162,
    image: "/featured/rustic-inn.jpg",
    minutesByYacht: 18,
    minutesByCar: 16,
    blurb: {
      en: "Garlic crabs and wooden mallets on the Dania Cut-Off Canal — bibs required.",
      es: "Cangrejos al ajo y mazos de madera en el Dania Cut-Off Canal: babero obligatorio.",
      fr: "Crabes à l’ail et maillets sur le Dania Cut-Off Canal — bavoir obligatoire.",
      it: "Granchi all’aglio e mazze sul Dania Cut-Off Canal: bavaglino obbligatorio.",
      pt: "Caranguejos no alho e malhos no Dania Cut-Off Canal — babador obrigatório.",
    },
  },
  {
    id: "casablanca-cafe",
    kind: "place",
    featured: "dine",
    name: "Casablanca Cafe",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.137,
    lng: -80.104,
    image: "/featured/casablanca-cafe.jpg",
    minutesByYacht: 14,
    minutesByCar: 10,
    blurb: {
      en: "1927 beach house on the Atlantic — oceanfront patio a block from A1A.",
      es: "Casa de playa de 1927 en el Atlántico: terraza al mar a una cuadra de A1A.",
      fr: "Maison de plage de 1927 sur l’Atlantique — terrasse face à l’océan, une rue d’A1A.",
      it: "Casa sulla spiaggia del 1927 sull’Atlantico: terrazza oceanica a un isolato da A1A.",
      pt: "Casa de praia de 1927 no Atlântico — terraço oceânico a uma quadra da A1A.",
    },
  },
  {
    id: "yot-bar",
    kind: "place",
    featured: "dine",
    name: "YOT Bar & Kitchen",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.096,
    lng: -80.168,
    image: "/featured/yot-bar.jpg",
    minutesByYacht: 16,
    minutesByCar: 14,
    blurb: {
      en: "American fare inside Safe Harbor Lauderdale — marina views from the terrace.",
      es: "Cocina americana en Safe Harbor Lauderdale: vistas a la marina desde la terraza.",
      fr: "Cuisine américaine à Safe Harbor Lauderdale — vue marina depuis la terrasse.",
      it: "Cucina americana a Safe Harbor Lauderdale: vista marina dalla terrazza.",
      pt: "Cozinha americana no Safe Harbor Lauderdale — vista da marina no terraço.",
    },
  },
  {
    id: "joia-beach",
    kind: "place",
    featured: "dine",
    name: "Joia Beach",
    city: "Watson Island",
    country: "United States",
    lat: 25.7855,
    lng: -80.1755,
    image: "/featured/joia-beach.jpg",
    minutesByYacht: 10,
    minutesByCar: 12,
    blurb: {
      en: "Bay beach club on Watson Island — cabanas, Biscayne views, and a short run from the Grove.",
      es: "Beach club en Watson Island: camas, vistas a Biscayne y un salto desde The Grove.",
      fr: "Beach club sur Watson Island — cabanes, vue sur Biscayne, tout près de Coconut Grove.",
      it: "Beach club a Watson Island: cabana, vista su Biscayne, a un salto dal Grove.",
      pt: "Beach club em Watson Island — cabanas, vista da Biscayne e um salto do Grove.",
    },
  },
  {
    id: "kiki-on-the-river",
    kind: "place",
    featured: "dine",
    name: "Kiki on the River",
    city: "Miami",
    country: "United States",
    lat: 25.7695,
    lng: -80.1935,
    image: "/featured/kiki-on-the-river.jpg",
    minutesByYacht: 14,
    minutesByCar: 10,
    blurb: {
      en: "Greek terrace on the Miami River — Brickell towers and boats tying up downtown.",
      es: "Terraza griega en el Miami River: torres de Brickell y botes en el centro.",
      fr: "Terrasse grecque sur la Miami River — tours de Brickell et bateaux en centre-ville.",
      it: "Terrazza greca sul Miami River: torri di Brickell e barche in centro.",
      pt: "Terraço grego no Miami River — torres de Brickell e barcos no centro.",
    },
  },
  {
    id: "shuckers",
    kind: "place",
    featured: "dine",
    name: "Shuckers Bar & Grill",
    city: "Miami Beach",
    country: "United States",
    lat: 25.848,
    lng: -80.142,
    image: "/featured/shuckers.jpg",
    minutesByYacht: 16,
    minutesByCar: 18,
    blurb: {
      en: "Casual raw bar on the 79th Street Causeway — picnic tables and Biscayne Bay docks.",
      es: "Raw bar informal en la calzada 79th Street: mesas picnic y muelles de Biscayne Bay.",
      fr: "Raw bar décontracté sur la 79th Street Causeway — tables pique-nique et pontons.",
      it: "Raw bar informale sulla 79th Street Causeway: tavoli picnic e pontili su Biscayne Bay.",
      pt: "Raw bar casual na 79th Street Causeway — mesas picnic e cais na Biscayne Bay.",
    },
  },
  {
    id: "sands-waterfront",
    kind: "place",
    featured: "dine",
    name: "Sands Waterfront",
    city: "Pompano Beach",
    country: "United States",
    lat: 26.2355,
    lng: -80.0925,
    image: "/featured/sands-waterfront.jpg",
    minutesByYacht: 26,
    minutesByCar: 22,
    blurb: {
      en: "Dockside dining at Sands Harbor — sportfishers in the slips and Intracoastal traffic.",
      es: "Comida en el muelle de Sands Harbor: pesqueros en dársena y tráfico del Intracoastal.",
      fr: "Table au ponton de Sands Harbor — pêcheurs au bassin et trafic de l’Intracoastal.",
      it: "Tavolo al pontile di Sands Harbor: pescherecci in darsena e traffico sull’Intracoastal.",
      pt: "Refeição no cais de Sands Harbor — barcos de pesca na dársena e tráfego do Intracoastal.",
    },
  },
  {
    id: "senequier",
    kind: "place",
    featured: "dine",
    name: "Le Sénéquier",
    city: "Saint-Tropez",
    country: "France",
    lat: 43.2725,
    lng: 6.6394,
    image: "/featured/senequier.jpg",
    minutesByYacht: 8,
    minutesByCar: 15,
    blurb: {
      en: "Red awnings on the Vieux Port — the classic Saint-Tropez quay lunch after you tie up.",
      es: "Toldos rojos en el Vieux Port: el almuerzo clásico del muelle de Saint-Tropez.",
      fr: "Les stores rouges du Vieux Port — le déjeuner mythique du quai de Saint-Tropez.",
      it: "Tende rosse al Vieux Port: il pranzo classico sulla banchina di Saint-Tropez.",
      pt: "Toldos vermelhos no Vieux Port — o almoço clássico no cais de Saint-Tropez.",
    },
  },
  {
    id: "agua-port-olimpic",
    kind: "place",
    featured: "dine",
    name: "Port Olímpic",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3865,
    lng: 2.1995,
    image: "/featured/agua-olimpic.jpg",
    minutesByYacht: 10,
    minutesByCar: 20,
    blurb: {
      en: "Beach restaurants on Barcelona’s Olympic port — yachts in the basin, tables on the sand.",
      es: "Restaurantes de playa en el Port Olímpic: yates en dársena y mesas en la arena.",
      fr: "Restaurants de plage au Port Olímpic — yachts dans le bassin, tables sur le sable.",
      it: "Ristoranti in spiaggia al Port Olímpic: yacht in darsena e tavoli sulla sabbia.",
      pt: "Restaurantes na praia do Port Olímpic — iates na dársena e mesas na areia.",
    },
  },
  {
    id: "star-island",
    kind: "place",
    featured: "scenic",
    name: "Star Island",
    city: "Miami Beach",
    country: "United States",
    lat: 25.777,
    lng: -80.151,
    image: "/featured/star-island.jpg",
    minutesByYacht: 14,
    minutesByCar: 0,
    blurb: {
      en: "Slow cruise past Miami’s most photographed waterfront mansions on Biscayne Bay.",
      es: "Crucero lento frente a las mansiones más fotografiadas de Miami en Biscayne Bay.",
      fr: "Croisière lente devant les villas les plus photographiées de Miami.",
      it: "Crociera lenta davanti alle ville più fotografate di Miami.",
      pt: "Cruzeiro lento diante das mansões mais fotografadas de Miami.",
    },
  },
  {
    id: "vizcaya",
    kind: "place",
    featured: "scenic",
    name: "Vizcaya",
    city: "Coconut Grove",
    country: "United States",
    lat: 25.7434,
    lng: -80.2104,
    image: "/featured/vizcaya.jpg",
    minutesByYacht: 16,
    minutesByCar: 0,
    blurb: {
      en: "Renaissance villa and stone barge on Biscayne Bay — the scenic Grove run from Miami Beach.",
      es: "Villa renacentista y barcaza de piedra en Biscayne Bay, el crucero escénico del Grove.",
      fr: "Villa Renaissance et barge de pierre sur Biscayne Bay, la croisière du Grove.",
      it: "Villa rinascimentale e barge di pietra su Biscayne Bay, la crociera del Grove.",
      pt: "Vila renascentista e barcaça de pedra em Biscayne Bay, o cruzeiro do Grove.",
    },
  },
  {
    id: "palm-beach-estates",
    kind: "place",
    featured: "scenic",
    name: "Palm Beach Estates",
    city: "Palm Beach",
    country: "United States",
    lat: 26.7056,
    lng: -80.041,
    image: "/featured/palm-beach-estates.jpg",
    minutesByYacht: 45,
    minutesByCar: 0,
    blurb: {
      en: "Intracoastal mansions and private docks on Lake Worth — the golden-hour run from FTL.",
      es: "Mansiones del Intracoastal y muelles privados en Lake Worth, al atardecer desde FTL.",
      fr: "Villas de l’Intracoastal et pontons privés sur Lake Worth, au coucher du soleil.",
      it: "Ville sull’Intracoastal e pontili privati su Lake Worth, all’ora d’oro da FTL.",
      pt: "Mansões do Intracoastal e cais privados em Lake Worth, ao pôr do sol desde FTL.",
    },
  },
  {
    id: "ile-sainte-marguerite",
    kind: "place",
    featured: "scenic",
    name: "Île Sainte-Marguerite",
    city: "Cannes",
    country: "France",
    lat: 43.5225,
    lng: 7.0467,
    image: "/featured/ile-sainte-marguerite.jpg",
    minutesByYacht: 20,
    minutesByCar: 0,
    blurb: {
      en: "Pine island and Fort Royal in the Lérins — the scenic hop from the Cannes quays.",
      es: "Isla de pinos y Fort Royal en las Lérins: el salto escénico desde los muelles de Cannes.",
      fr: "Île de pins et Fort Royal aux Lérins — la traversée depuis les quais de Cannes.",
      it: "Isola di pini e Fort Royal alle Lérins: il salto scenico dai moli di Cannes.",
      pt: "Ilha de pinheiros e Fort Royal nas Lérins — o salto cênico dos cais de Cannes.",
    },
  },
];

export function featuredByKind(kind: FeaturedKind) {
  return featuredPlaces.filter((p) => p.featured === kind);
}
