import type { Place } from "./places";

export const FEATURED_KINDS = ["sandbar", "beach", "dine", "scenic"] as const;
export type FeaturedKind = (typeof FEATURED_KINDS)[number];

export const featuredPlaces: Place[] = [
  {
    id: "haulover-sandbar",
    kind: "place",
    featured: "beach",
    name: "Haulover Sandbar",
    city: "North Miami Beach",
    country: "United States",
    lat: 25.9075,
    lng: -80.1235,
    image: "/featured/haulover-sandbar.jpg",
    minutesByYacht: 28,
    minutesByCar: 0,
    blurb: {
      en: "Miami’s social sandbar inside Haulover Inlet — waist-deep water and weekend raft-ups.",
      es: "El sandbar social de Miami junto a Haulover Inlet: agua a la cintura y botes anclados.",
      fr: "Le sandbar social de Miami dans Haulover Inlet — eau à la taille et bateaux à l’ancre.",
      it: "Il sandbar sociale di Miami dentro Haulover Inlet: acqua alla vita e barche all’ancora.",
      pt: "O sandbar social de Miami em Haulover Inlet — água na cintura e barcos fundeados.",
    },
  },
  {
    id: "hollywood-sandbar",
    kind: "place",
    featured: "sandbar",
    name: "Hollywood Beach Sandbar",
    city: "Hollywood",
    country: "United States",
    lat: 26.021,
    lng: -80.114,
    image: "/featured/hollywood-sandbar.jpg",
    minutesByYacht: 35,
    minutesByCar: 0,
    blurb: {
      en: "Family sandbar off Hollywood Beach — anchor, swim, and paddle from Fort Lauderdale.",
      es: "Sandbar familiar frente a Hollywood Beach: ancla, nado y paddle desde Fort Lauderdale.",
      fr: "Sandbar familial au large d’Hollywood Beach — ancrez et nagez depuis Fort Lauderdale.",
      it: "Sandbar in famiglia al largo di Hollywood Beach: ancora e nuoto da Fort Lauderdale.",
      pt: "Sandbar em família em Hollywood Beach — ancore e nade desde Fort Lauderdale.",
    },
  },
  {
    id: "ses-illetes",
    kind: "place",
    featured: "sandbar",
    name: "Ses Illetes",
    city: "Formentera",
    country: "Spain",
    lat: 38.7617,
    lng: 1.4333,
    image: "/featured/ses-illetes.jpg",
    minutesByYacht: 40,
    minutesByCar: 0,
    blurb: {
      en: "White sand spit and turquoise shallows — the classic Formentera anchorage from Ibiza.",
      es: "Lengua de arena blanca y aguas turquesa: el fondeo clásico de Formentera desde Ibiza.",
      fr: "Langue de sable blanc et eaux turquoise — le mouillage classique de Formentera.",
      it: "Lingua di sabbia bianca e acqua turchese: l’ancoraggio classico di Formentera.",
      pt: "Faixa de areia branca e água turquesa — o fundeadouro clássico de Formentera.",
    },
  },
  {
    id: "cala-comte",
    kind: "place",
    featured: "sandbar",
    name: "Cala Comte",
    city: "Ibiza",
    country: "Spain",
    lat: 38.961,
    lng: 1.219,
    image: "/featured/cala-comte.jpg",
    minutesByYacht: 25,
    minutesByCar: 0,
    blurb: {
      en: "West Ibiza coves for sunset anchoring — limestone cliffs and clear Mediterranean water.",
      es: "Caldas del oeste de Ibiza para fondear al atardecer: acantilados y agua clara.",
      fr: "Cales de l’ouest d’Ibiza pour un mouillage au coucher du soleil.",
      it: "Cale dell’ovest di Ibiza per l’ancoraggio al tramonto.",
      pt: "Enseadas do oeste de Ibiza para fundear ao pôr do sol.",
    },
  },
  {
    id: "south-beach",
    kind: "place",
    featured: "beach",
    name: "South Beach / Lummus Park",
    city: "Miami Beach",
    country: "United States",
    lat: 25.7826,
    lng: -80.134,
    image: "/featured/south-beach.jpg",
    minutesByYacht: 10,
    minutesByCar: 25,
    blurb: {
      en: "Arrive by water to Lummus Park and the Art Deco hotels — skip the Ocean Drive valet line.",
      es: "Llega por agua a Lummus Park y los hoteles Art Déco. Sin fila de valet en Ocean Drive.",
      fr: "Arrivez par l’eau à Lummus Park et aux hôtels Art déco.",
      it: "Arriva via acqua a Lummus Park e agli hotel Art Déco.",
      pt: "Chegue pela água ao Lummus Park e aos hotéis Art Déco.",
    },
  },
  {
    id: "crandon-park",
    kind: "place",
    featured: "beach",
    name: "Crandon Park Beach",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.712,
    lng: -80.1539,
    image: "/featured/crandon-park.jpg",
    minutesByYacht: 22,
    minutesByCar: 35,
    blurb: {
      en: "Key Biscayne’s wide park beach — calm water, pines, and a marina at the north end.",
      es: "La playa-parque de Key Biscayne: agua calma, pinos y marina al norte.",
      fr: "La plage-parc de Key Biscayne — eau calme, pins et marina au nord.",
      it: "La spiaggia-parco di Key Biscayne: acqua calma, pini e marina a nord.",
      pt: "A praia-parque de Key Biscayne — água calma, pinheiros e marina ao norte.",
    },
  },
  {
    id: "nixon-sandbar",
    kind: "place",
    featured: "beach",
    name: "Nixon Sandbar",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.6786,
    lng: -80.1624,
    image: "/featured/nixon-sandbar.jpg",
    minutesByYacht: 20,
    minutesByCar: 0,
    blurb: {
      en: "Boat-only sandbar off Key Biscayne — shallow Biscayne Bay flats with Miami skyline views.",
      es: "Sandbar solo en bote frente a Key Biscayne: bajos de Biscayne Bay y skyline de Miami.",
      fr: "Sandbar accessible seulement en bateau au large de Key Biscayne, vue sur Miami.",
      it: "Sandbar solo in barca al largo di Key Biscayne, con skyline di Miami.",
      pt: "Sandbar só de barco em Key Biscayne — baixios da Biscayne Bay e skyline de Miami.",
    },
  },
  {
    id: "stiltsville",
    kind: "place",
    featured: "beach",
    name: "Stiltsville",
    city: "Biscayne Bay",
    country: "United States",
    lat: 25.653,
    lng: -80.175,
    image: "/featured/stiltsville.jpg",
    minutesByYacht: 35,
    minutesByCar: 0,
    blurb: {
      en: "Historic houses on stilts in Biscayne National Park — a slow scenic run south of Key Biscayne.",
      es: "Casas sobre pilotes en Biscayne National Park: crucero lento al sur de Key Biscayne.",
      fr: "Maisons sur pilotis dans Biscayne National Park, au sud de Key Biscayne.",
      it: "Case su palafitte a Biscayne National Park, a sud di Key Biscayne.",
      pt: "Casas sobre palafitas no Biscayne National Park, ao sul de Key Biscayne.",
    },
  },
  {
    id: "lake-sylvia",
    kind: "place",
    featured: "beach",
    name: "Lake Sylvia",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.10466,
    lng: -80.11154,
    image: "/featured/lake-sylvia.jpg",
    minutesByYacht: 10,
    minutesByCar: 0,
    blurb: {
      en: "Quiet lake off the Intracoastal near Harbor Beach — docks, calm water, and a short hop from Las Olas.",
      es: "Lago tranquilo junto al Intracoastal cerca de Harbor Beach, a un salto de Las Olas.",
      fr: "Lac calme près de l’Intracoastal à Harbor Beach, tout près de Las Olas.",
      it: "Lago calmo sull’Intracoastal a Harbor Beach, a un salto da Las Olas.",
      pt: "Lago calmo no Intracoastal junto a Harbor Beach, perto de Las Olas.",
    },
  },
  {
    id: "lake-boca-raton",
    kind: "place",
    featured: "beach",
    name: "Lake Boca Raton",
    city: "Boca Raton",
    country: "United States",
    lat: 26.347,
    lng: -80.078,
    image: "/featured/lake-boca-raton.jpg",
    minutesByYacht: 18,
    minutesByCar: 0,
    blurb: {
      en: "Wide lake inside the Boca Raton inlet — anchor in protected water before the Atlantic.",
      es: "Lago amplio dentro de la entrada de Boca Raton: fondea al abrigo antes del Atlántico.",
      fr: "Grand lac à l’intérieur de l’inlet de Boca Raton — mouillage protégé avant l’Atlantique.",
      it: "Ampio lago dentro l’inlet di Boca Raton: ancoraggio riparato prima dell’Atlantico.",
      pt: "Lago amplo na entrada de Boca Raton — fundeio protegido antes do Atlântico.",
    },
  },
  {
    id: "maule-lake",
    kind: "place",
    featured: "beach",
    name: "Maule Lake",
    city: "North Miami Beach",
    country: "United States",
    lat: 25.935,
    lng: -80.151,
    image: "/featured/maule-lake.jpg",
    minutesByYacht: 22,
    minutesByCar: 0,
    blurb: {
      en: "Residential lake off the Intracoastal in Eastern Shores — calm water just west of Sunny Isles.",
      es: "Lago residencial del Intracoastal en Eastern Shores, al oeste de Sunny Isles.",
      fr: "Lac résidentiel de l’Intracoastal à Eastern Shores, à l’ouest de Sunny Isles.",
      it: "Lago residenziale sull’Intracoastal a Eastern Shores, a ovest di Sunny Isles.",
      pt: "Lago residencial no Intracoastal em Eastern Shores, a oeste de Sunny Isles.",
    },
  },
  {
    id: "john-u-lloyd",
    kind: "place",
    featured: "beach",
    name: "John U. Lloyd State Park",
    city: "Dania Beach",
    country: "United States",
    lat: 26.071,
    lng: -80.111,
    image: "/featured/john-u-lloyd.jpg",
    minutesByYacht: 16,
    minutesByCar: 25,
    blurb: {
      en: "Wild beach and Whiskey Creek at Port Everglades — dunes, pines, and a quiet inlet.",
      es: "Playa natural y Whiskey Creek en Port Everglades: dunas, pinos y un inlet tranquilo.",
      fr: "Plage naturelle et Whiskey Creek à Port Everglades — dunes, pins et inlet calme.",
      it: "Spiaggia naturale e Whiskey Creek a Port Everglades: dune, pini e inlet calmo.",
      pt: "Praia natural e Whiskey Creek em Port Everglades — dunas, pinheiros e inlet calmo.",
    },
  },
  {
    id: "no-name-harbor",
    kind: "place",
    featured: "beach",
    name: "No Name Harbor",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.6768,
    lng: -80.1628,
    image: "/featured/no-name-harbor.jpg",
    minutesByYacht: 24,
    minutesByCar: 0,
    blurb: {
      en: "Day-use harbor inside Bill Baggs — tie to the wall and walk to Cape Florida beach.",
      es: "Puerto de día en Bill Baggs: amarra al muro y camina a la playa de Cape Florida.",
      fr: "Port à la journée dans Bill Baggs — amarrez au quai et gagnez Cape Florida à pied.",
      it: "Porto diurna a Bill Baggs: ormeggia al muro e cammina fino a Cape Florida.",
      pt: "Porto de dia em Bill Baggs — atraque no muro e caminhe até Cape Florida.",
    },
  },
  {
    id: "bill-baggs",
    kind: "place",
    featured: "beach",
    name: "Bill Baggs Cape Florida State Park",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.6735,
    lng: -80.1573,
    image: "/featured/bill-baggs.jpg",
    minutesByYacht: 24,
    minutesByCar: 40,
    blurb: {
      en: "Cape Florida Lighthouse and Atlantic beach at the south tip of Key Biscayne.",
      es: "Faro de Cape Florida y playa atlántica en la punta sur de Key Biscayne.",
      fr: "Phare de Cape Florida et plage atlantique à la pointe sud de Key Biscayne.",
      it: "Faro di Cape Florida e spiaggia atlantica sulla punta sud di Key Biscayne.",
      pt: "Farol de Cape Florida e praia atlântica na ponta sul de Key Biscayne.",
    },
  },
  {
    id: "hollywood-broadwalk",
    kind: "place",
    featured: "beach",
    name: "Hollywood Beach Broadwalk",
    city: "Hollywood",
    country: "United States",
    lat: 26.011,
    lng: -80.117,
    image: "/featured/hollywood-broadwalk.jpg",
    minutesByYacht: 30,
    minutesByCar: 20,
    blurb: {
      en: "Palm promenade and Atlantic sand — arrive by water and walk the Broadwalk.",
      es: "Paseo de palmeras y arena atlántica: llega por agua y camina el Broadwalk.",
      fr: "Promenade des palmiers et sable atlantique — arrivez par l’eau.",
      it: "Passeggiata delle palme e sabbia atlantica: arriva via acqua.",
      pt: "Calçadão de palmeiras e areia atlântica — chegue pela água.",
    },
  },
  {
    id: "pompano-beach",
    kind: "place",
    featured: "beach",
    name: "Pompano Beach",
    city: "Pompano Beach",
    country: "United States",
    lat: 26.234,
    lng: -80.09,
    image: "/featured/pompano-beach.jpg",
    minutesByYacht: 28,
    minutesByCar: 22,
    blurb: {
      en: "Long Atlantic beach and pier north of Fort Lauderdale — an easy Intracoastal hop.",
      es: "Playa atlántica y muelle al norte de Fort Lauderdale, un salto por el Intracoastal.",
      fr: "Plage atlantique et jetée au nord de Fort Lauderdale, un saut par l’Intracoastal.",
      it: "Spiaggia atlantica e pier a nord di Fort Lauderdale, un salto sull’Intracoastal.",
      pt: "Praia atlântica e píer ao norte de Fort Lauderdale, um salto pelo Intracoastal.",
    },
  },
  {
    id: "deerfield-beach",
    kind: "place",
    featured: "beach",
    name: "Deerfield Beach",
    city: "Deerfield Beach",
    country: "United States",
    lat: 26.318,
    lng: -80.075,
    image: "/featured/deerfield-beach.jpg",
    minutesByYacht: 35,
    minutesByCar: 28,
    blurb: {
      en: "Family beach and fishing pier on the Broward–Palm Beach line.",
      es: "Playa familiar y muelle de pesca en la línea Broward–Palm Beach.",
      fr: "Plage familiale et jetée de pêche à la limite Broward–Palm Beach.",
      it: "Spiaggia per famiglie e pier da pesca sul confine Broward–Palm Beach.",
      pt: "Praia familiar e píer de pesca na linha Broward–Palm Beach.",
    },
  },
  {
    id: "bal-harbour-beach",
    kind: "place",
    featured: "beach",
    name: "Bal Harbour Beach",
    city: "Bal Harbour",
    country: "United States",
    lat: 25.899,
    lng: -80.123,
    image: "/featured/bal-harbour-beach.jpg",
    minutesByYacht: 18,
    minutesByCar: 20,
    blurb: {
      en: "Quiet Atlantic sand just south of Haulover Inlet — a short run from Miami Beach.",
      es: "Arena atlántica tranquila al sur de Haulover Inlet, un salto desde Miami Beach.",
      fr: "Sable atlantique calme au sud de Haulover Inlet, tout près de Miami Beach.",
      it: "Sabbia atlantica tranquilla a sud di Haulover Inlet, a un salto da Miami Beach.",
      pt: "Areia atlântica calma ao sul de Haulover Inlet, perto de Miami Beach.",
    },
  },
  {
    id: "sunny-isles-beach",
    kind: "place",
    featured: "beach",
    name: "Sunny Isles Beach",
    city: "Sunny Isles Beach",
    country: "United States",
    lat: 25.95,
    lng: -80.121,
    image: "/featured/sunny-isles-beach.jpg",
    minutesByYacht: 22,
    minutesByCar: 25,
    blurb: {
      en: "Condo skyline and Atlantic beach north of Haulover — arrive along the Intracoastal.",
      es: "Skyline de condos y playa atlántica al norte de Haulover, por el Intracoastal.",
      fr: "Skyline de condos et plage atlantique au nord de Haulover, via l’Intracoastal.",
      it: "Skyline di condo e spiaggia atlantica a nord di Haulover, via Intracoastal.",
      pt: "Skyline de condos e praia atlântica ao norte de Haulover, pelo Intracoastal.",
    },
  },
  {
    id: "fort-lauderdale-beach",
    kind: "place",
    featured: "beach",
    name: "Fort Lauderdale Beach",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.122,
    lng: -80.104,
    image: "/featured/fort-lauderdale-beach.jpg",
    minutesByYacht: 14,
    minutesByCar: 15,
    blurb: {
      en: "A1A Wave Wall, palms, and Atlantic sand — drop by water instead of the beach traffic.",
      es: "Wave Wall de A1A, palmeras y arena atlántica: llega por agua, no por el tráfico.",
      fr: "Wave Wall d’A1A, palmiers et sable atlantique — arrivez par l’eau.",
      it: "Wave Wall di A1A, palme e sabbia atlantica: arriva via acqua.",
      pt: "Wave Wall da A1A, palmeiras e areia atlântica — chegue pela água.",
    },
  },
  {
    id: "hugh-taylor-birch",
    kind: "place",
    featured: "beach",
    name: "Hugh Taylor Birch State Park",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.145,
    lng: -80.104,
    image: "/featured/hugh-taylor-birch.jpg",
    minutesByYacht: 16,
    minutesByCar: 18,
    blurb: {
      en: "Barrier-island park between the Atlantic and a mangrove lagoon on the Intracoastal.",
      es: "Parque entre el Atlántico y una laguna de manglar en el Intracoastal.",
      fr: "Parc entre l’Atlantique et une lagune de palétuviers sur l’Intracoastal.",
      it: "Parco tra Atlantico e laguna di mangrovie sull’Intracoastal.",
      pt: "Parque entre o Atlântico e uma lagoa de mangue no Intracoastal.",
    },
  },
  {
    id: "barceloneta-beach",
    kind: "place",
    featured: "beach",
    name: "Barceloneta Beach",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3768,
    lng: 2.1925,
    image: "/featured/barceloneta.jpg",
    minutesByYacht: 15,
    minutesByCar: 28,
    blurb: {
      en: "City beach beside Port Vell — step off the yacht into Barcelona’s waterfront barrio.",
      es: "Playa urbana junto a Port Vell: del yate al barrio marítimo de Barcelona.",
      fr: "Plage urbaine à Port Vell — du yacht au quartier maritime de Barcelone.",
      it: "Spiaggia urbana a Port Vell: dallo yacht al quartiere marittimo di Barcellona.",
      pt: "Praia urbana em Port Vell — do iate ao bairro marítimo de Barcelona.",
    },
  },
  {
    id: "cannes-croisette",
    kind: "place",
    featured: "beach",
    name: "La Croisette",
    city: "Cannes",
    country: "France",
    lat: 43.5507,
    lng: 7.0174,
    image: "/featured/cannes-croisette.jpg",
    minutesByYacht: 12,
    minutesByCar: 20,
    blurb: {
      en: "Palm promenade, palace hotels, and beach clubs on the Bay of Cannes.",
      es: "Paseo de palmeras, hoteles palacio y beach clubs en la bahía de Cannes.",
      fr: "Promenade des palmiers, palaces et plages privées sur la baie de Cannes.",
      it: "Passeggiata delle palme, hotel palazzo e spiagge sulla baia di Cannes.",
      pt: "Calçadão de palmeiras, hotéis palácio e beach clubs na baía de Cannes.",
    },
  },
  {
    id: "montys-grove",
    kind: "place",
    featured: "dine",
    name: "Monty's Raw Bar",
    city: "Coconut Grove",
    country: "United States",
    lat: 25.7285,
    lng: -80.238,
    image: "/featured/montys.jpg",
    minutesByYacht: 18,
    minutesByCar: 22,
    blurb: {
      en: "Dock-and-dine on Biscayne Bay since 1969 — tiki deck, raw bar, and slips at the Grove.",
      es: "Dock & dine en Biscayne Bay desde 1969: terraza tiki, raw bar y amarres en The Grove.",
      fr: "Dock & dine sur Biscayne Bay depuis 1969 — terrasse tiki et pontons à Coconut Grove.",
      it: "Dock & dine su Biscayne Bay dal 1969: terrazza tiki e ormeggi a Coconut Grove.",
      pt: "Dock & dine em Biscayne Bay desde 1969 — deck tiki e vagas em Coconut Grove.",
    },
  },
  {
    id: "fifteenth-street-fisheries",
    kind: "place",
    featured: "dine",
    name: "15th Street Fisheries",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.1033,
    lng: -80.1188,
    image: "/featured/fifteenth-street.jpg",
    minutesByYacht: 12,
    minutesByCar: 18,
    blurb: {
      en: "Seafood at Lauderdale Marina — free dockage on the Intracoastal and tarpon at the docks.",
      es: "Mariscos en Lauderdale Marina: atraque en el Intracoastal y sábalos en los muelles.",
      fr: "Fruits de mer à Lauderdale Marina — pontons sur l’Intracoastal et tarpons aux docks.",
      it: "Pesce a Lauderdale Marina: ormeggio sull’Intracoastal e tarpon ai pontili.",
      pt: "Frutos do mar na Lauderdale Marina — atracação no Intracoastal e tarpons nos cais.",
    },
  },
  {
    id: "senequier",
    kind: "place",
    featured: "dine",
    name: "Le Sénéquier",
    city: "Saint-Tropez",
    country: "France",
    lat: 43.2725,
    lng: 6.6394,
    image: "/featured/senequier.jpg",
    minutesByYacht: 8,
    minutesByCar: 15,
    blurb: {
      en: "Red awnings on the Vieux Port — the classic Saint-Tropez quay lunch after you tie up.",
      es: "Toldos rojos en el Vieux Port: el almuerzo clásico del muelle de Saint-Tropez.",
      fr: "Les stores rouges du Vieux Port — le déjeuner mythique du quai de Saint-Tropez.",
      it: "Tende rosse al Vieux Port: il pranzo classico sulla banchina di Saint-Tropez.",
      pt: "Toldos vermelhos no Vieux Port — o almoço clássico no cais de Saint-Tropez.",
    },
  },
  {
    id: "agua-port-olimpic",
    kind: "place",
    featured: "dine",
    name: "Port Olímpic",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3865,
    lng: 2.1995,
    image: "/featured/agua-olimpic.jpg",
    minutesByYacht: 10,
    minutesByCar: 20,
    blurb: {
      en: "Beach restaurants on Barcelona’s Olympic port — yachts in the basin, tables on the sand.",
      es: "Restaurantes de playa en el Port Olímpic: yates en dársena y mesas en la arena.",
      fr: "Restaurants de plage au Port Olímpic — yachts dans le bassin, tables sur le sable.",
      it: "Ristoranti in spiaggia al Port Olímpic: yacht in darsena e tavoli sulla sabbia.",
      pt: "Restaurantes na praia do Port Olímpic — iates na dársena e mesas na areia.",
    },
  },
  {
    id: "star-island",
    kind: "place",
    featured: "scenic",
    name: "Star Island",
    city: "Miami Beach",
    country: "United States",
    lat: 25.777,
    lng: -80.151,
    image: "/featured/star-island.jpg",
    minutesByYacht: 14,
    minutesByCar: 0,
    blurb: {
      en: "Slow cruise past Miami’s most photographed waterfront mansions on Biscayne Bay.",
      es: "Crucero lento frente a las mansiones más fotografiadas de Miami en Biscayne Bay.",
      fr: "Croisière lente devant les villas les plus photographiées de Miami.",
      it: "Crociera lenta davanti alle ville più fotografate di Miami.",
      pt: "Cruzeiro lento diante das mansões mais fotografadas de Miami.",
    },
  },
  {
    id: "vizcaya",
    kind: "place",
    featured: "scenic",
    name: "Vizcaya",
    city: "Coconut Grove",
    country: "United States",
    lat: 25.7434,
    lng: -80.2104,
    image: "/featured/vizcaya.jpg",
    minutesByYacht: 16,
    minutesByCar: 0,
    blurb: {
      en: "Renaissance villa and stone barge on Biscayne Bay — the scenic Grove run from Miami Beach.",
      es: "Villa renacentista y barcaza de piedra en Biscayne Bay, el crucero escénico del Grove.",
      fr: "Villa Renaissance et barge de pierre sur Biscayne Bay, la croisière du Grove.",
      it: "Villa rinascimentale e barge di pietra su Biscayne Bay, la crociera del Grove.",
      pt: "Vila renascentista e barcaça de pedra em Biscayne Bay, o cruzeiro do Grove.",
    },
  },
  {
    id: "palm-beach-estates",
    kind: "place",
    featured: "scenic",
    name: "Palm Beach Estates",
    city: "Palm Beach",
    country: "United States",
    lat: 26.7056,
    lng: -80.041,
    image: "/featured/palm-beach-estates.jpg",
    minutesByYacht: 45,
    minutesByCar: 0,
    blurb: {
      en: "Intracoastal mansions and private docks on Lake Worth — the golden-hour run from FTL.",
      es: "Mansiones del Intracoastal y muelles privados en Lake Worth, al atardecer desde FTL.",
      fr: "Villas de l’Intracoastal et pontons privés sur Lake Worth, au coucher du soleil.",
      it: "Ville sull’Intracoastal e pontili privati su Lake Worth, all’ora d’oro da FTL.",
      pt: "Mansões do Intracoastal e cais privados em Lake Worth, ao pôr do sol desde FTL.",
    },
  },
  {
    id: "ile-sainte-marguerite",
    kind: "place",
    featured: "scenic",
    name: "Île Sainte-Marguerite",
    city: "Cannes",
    country: "France",
    lat: 43.5225,
    lng: 7.0467,
    image: "/featured/ile-sainte-marguerite.jpg",
    minutesByYacht: 20,
    minutesByCar: 0,
    blurb: {
      en: "Pine island and Fort Royal in the Lérins — the scenic hop from the Cannes quays.",
      es: "Isla de pinos y Fort Royal en las Lérins: el salto escénico desde los muelles de Cannes.",
      fr: "Île de pins et Fort Royal aux Lérins — la traversée depuis les quais de Cannes.",
      it: "Isola di pini e Fort Royal alle Lérins: il salto scenico dai moli di Cannes.",
      pt: "Ilha de pinheiros e Fort Royal nas Lérins — o salto cênico dos cais de Cannes.",
    },
  },
];

export function featuredByKind(kind: FeaturedKind) {
  return featuredPlaces.filter((p) => p.featured === kind);
}
