import type { Place } from "./places";

export const FEATURED_KINDS = ["sandbar", "beach", "dine", "scenic"] as const;
export type FeaturedKind = (typeof FEATURED_KINDS)[number];

export const featuredPlaces: Place[] = [
  {
    id: "haulover-sandbar",
    kind: "place",
    featured: "sandbar",
    name: "Haulover Sandbar",
    city: "North Miami Beach",
    country: "United States",
    lat: 25.9075,
    lng: -80.1235,
    image: "/featured/haulover-sandbar.jpg",
    minutesByYacht: 28,
    minutesByCar: 0,
    blurb: {
      en: "Miami’s social sandbar inside Haulover Inlet — waist-deep water and weekend raft-ups.",
      es: "El sandbar social de Miami junto a Haulover Inlet: agua a la cintura y botes anclados.",
      fr: "Le sandbar social de Miami dans Haulover Inlet — eau à la taille et bateaux à l’ancre.",
      it: "Il sandbar sociale di Miami dentro Haulover Inlet: acqua alla vita e barche all’ancora.",
      pt: "O sandbar social de Miami em Haulover Inlet — água na cintura e barcos fundeados.",
    },
  },
  {
    id: "hollywood-sandbar",
    kind: "place",
    featured: "sandbar",
    name: "Hollywood Beach Sandbar",
    city: "Hollywood",
    country: "United States",
    lat: 26.021,
    lng: -80.114,
    image: "/featured/hollywood-sandbar.jpg",
    minutesByYacht: 35,
    minutesByCar: 0,
    blurb: {
      en: "Family sandbar off Hollywood Beach — anchor, swim, and paddle from Fort Lauderdale.",
      es: "Sandbar familiar frente a Hollywood Beach: ancla, nado y paddle desde Fort Lauderdale.",
      fr: "Sandbar familial au large d’Hollywood Beach — ancrez et nagez depuis Fort Lauderdale.",
      it: "Sandbar in famiglia al largo di Hollywood Beach: ancora e nuoto da Fort Lauderdale.",
      pt: "Sandbar em família em Hollywood Beach — ancore e nade desde Fort Lauderdale.",
    },
  },
  {
    id: "ses-illetes",
    kind: "place",
    featured: "sandbar",
    name: "Ses Illetes",
    city: "Formentera",
    country: "Spain",
    lat: 38.7617,
    lng: 1.4333,
    image: "/featured/ses-illetes.jpg",
    minutesByYacht: 40,
    minutesByCar: 0,
    blurb: {
      en: "White sand spit and turquoise shallows — the classic Formentera anchorage from Ibiza.",
      es: "Lengua de arena blanca y aguas turquesa: el fondeo clásico de Formentera desde Ibiza.",
      fr: "Langue de sable blanc et eaux turquoise — le mouillage classique de Formentera.",
      it: "Lingua di sabbia bianca e acqua turchese: l’ancoraggio classico di Formentera.",
      pt: "Faixa de areia branca e água turquesa — o fundeadouro clássico de Formentera.",
    },
  },
  {
    id: "cala-comte",
    kind: "place",
    featured: "sandbar",
    name: "Cala Comte",
    city: "Ibiza",
    country: "Spain",
    lat: 38.961,
    lng: 1.219,
    image: "/featured/cala-comte.jpg",
    minutesByYacht: 25,
    minutesByCar: 0,
    blurb: {
      en: "West Ibiza coves for sunset anchoring — limestone cliffs and clear Mediterranean water.",
      es: "Caldas del oeste de Ibiza para fondear al atardecer: acantilados y agua clara.",
      fr: "Cales de l’ouest d’Ibiza pour un mouillage au coucher du soleil.",
      it: "Cale dell’ovest di Ibiza per l’ancoraggio al tramonto.",
      pt: "Enseadas do oeste de Ibiza para fundear ao pôr do sol.",
    },
  },
  {
    id: "south-beach",
    kind: "place",
    featured: "beach",
    name: "South Beach",
    city: "Miami Beach",
    country: "United States",
    lat: 25.7826,
    lng: -80.134,
    image: "/featured/south-beach.jpg",
    minutesByYacht: 10,
    minutesByCar: 25,
    blurb: {
      en: "Arrive by water to Lummus Park and the Art Deco hotels — skip the Ocean Drive valet line.",
      es: "Llega por agua a Lummus Park y los hoteles Art Déco. Sin fila de valet en Ocean Drive.",
      fr: "Arrivez par l’eau à Lummus Park et aux hôtels Art déco.",
      it: "Arriva via acqua a Lummus Park e agli hotel Art Déco.",
      pt: "Chegue pela água ao Lummus Park e aos hotéis Art Déco.",
    },
  },
  {
    id: "crandon-park",
    kind: "place",
    featured: "beach",
    name: "Crandon Park",
    city: "Key Biscayne",
    country: "United States",
    lat: 25.712,
    lng: -80.1539,
    image: "/featured/crandon-park.jpg",
    minutesByYacht: 22,
    minutesByCar: 35,
    blurb: {
      en: "Key Biscayne’s wide park beach — calm water, pines, and a marina at the north end.",
      es: "La playa-parque de Key Biscayne: agua calma, pinos y marina al norte.",
      fr: "La plage-parc de Key Biscayne — eau calme, pins et marina au nord.",
      it: "La spiaggia-parco di Key Biscayne: acqua calma, pini e marina a nord.",
      pt: "A praia-parque de Key Biscayne — água calma, pinheiros e marina ao norte.",
    },
  },
  {
    id: "barceloneta-beach",
    kind: "place",
    featured: "beach",
    name: "Barceloneta Beach",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3768,
    lng: 2.1925,
    image: "/featured/barceloneta.jpg",
    minutesByYacht: 15,
    minutesByCar: 28,
    blurb: {
      en: "City beach beside Port Vell — step off the yacht into Barcelona’s waterfront barrio.",
      es: "Playa urbana junto a Port Vell: del yate al barrio marítimo de Barcelona.",
      fr: "Plage urbaine à Port Vell — du yacht au quartier maritime de Barcelone.",
      it: "Spiaggia urbana a Port Vell: dallo yacht al quartiere marittimo di Barcellona.",
      pt: "Praia urbana em Port Vell — do iate ao bairro marítimo de Barcelona.",
    },
  },
  {
    id: "cannes-croisette",
    kind: "place",
    featured: "beach",
    name: "La Croisette",
    city: "Cannes",
    country: "France",
    lat: 43.5507,
    lng: 7.0174,
    image: "/featured/cannes-croisette.jpg",
    minutesByYacht: 12,
    minutesByCar: 20,
    blurb: {
      en: "Palm promenade, palace hotels, and beach clubs on the Bay of Cannes.",
      es: "Paseo de palmeras, hoteles palacio y beach clubs en la bahía de Cannes.",
      fr: "Promenade des palmiers, palaces et plages privées sur la baie de Cannes.",
      it: "Passeggiata delle palme, hotel palazzo e spiagge sulla baia di Cannes.",
      pt: "Calçadão de palmeiras, hotéis palácio e beach clubs na baía de Cannes.",
    },
  },
  {
    id: "montys-grove",
    kind: "place",
    featured: "dine",
    name: "Monty's Raw Bar",
    city: "Coconut Grove",
    country: "United States",
    lat: 25.7285,
    lng: -80.238,
    image: "/featured/montys.jpg",
    minutesByYacht: 18,
    minutesByCar: 22,
    blurb: {
      en: "Dock-and-dine on Biscayne Bay since 1969 — tiki deck, raw bar, and slips at the Grove.",
      es: "Dock & dine en Biscayne Bay desde 1969: terraza tiki, raw bar y amarres en The Grove.",
      fr: "Dock & dine sur Biscayne Bay depuis 1969 — terrasse tiki et pontons à Coconut Grove.",
      it: "Dock & dine su Biscayne Bay dal 1969: terrazza tiki e ormeggi a Coconut Grove.",
      pt: "Dock & dine em Biscayne Bay desde 1969 — deck tiki e vagas em Coconut Grove.",
    },
  },
  {
    id: "fifteenth-street-fisheries",
    kind: "place",
    featured: "dine",
    name: "15th Street Fisheries",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.1033,
    lng: -80.1188,
    image: "/featured/fifteenth-street.jpg",
    minutesByYacht: 12,
    minutesByCar: 18,
    blurb: {
      en: "Seafood at Lauderdale Marina — free dockage on the Intracoastal and tarpon at the docks.",
      es: "Mariscos en Lauderdale Marina: atraque en el Intracoastal y sábalos en los muelles.",
      fr: "Fruits de mer à Lauderdale Marina — pontons sur l’Intracoastal et tarpons aux docks.",
      it: "Pesce a Lauderdale Marina: ormeggio sull’Intracoastal e tarpon ai pontili.",
      pt: "Frutos do mar na Lauderdale Marina — atracação no Intracoastal e tarpons nos cais.",
    },
  },
  {
    id: "senequier",
    kind: "place",
    featured: "dine",
    name: "Le Sénéquier",
    city: "Saint-Tropez",
    country: "France",
    lat: 43.2725,
    lng: 6.6394,
    image: "/featured/senequier.jpg",
    minutesByYacht: 8,
    minutesByCar: 15,
    blurb: {
      en: "Red awnings on the Vieux Port — the classic Saint-Tropez quay lunch after you tie up.",
      es: "Toldos rojos en el Vieux Port: el almuerzo clásico del muelle de Saint-Tropez.",
      fr: "Les stores rouges du Vieux Port — le déjeuner mythique du quai de Saint-Tropez.",
      it: "Tende rosse al Vieux Port: il pranzo classico sulla banchina di Saint-Tropez.",
      pt: "Toldos vermelhos no Vieux Port — o almoço clássico no cais de Saint-Tropez.",
    },
  },
  {
    id: "agua-port-olimpic",
    kind: "place",
    featured: "dine",
    name: "Port Olímpic",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3865,
    lng: 2.1995,
    image: "/featured/agua-olimpic.jpg",
    minutesByYacht: 10,
    minutesByCar: 20,
    blurb: {
      en: "Beach restaurants on Barcelona’s Olympic port — yachts in the basin, tables on the sand.",
      es: "Restaurantes de playa en el Port Olímpic: yates en dársena y mesas en la arena.",
      fr: "Restaurants de plage au Port Olímpic — yachts dans le bassin, tables sur le sable.",
      it: "Ristoranti in spiaggia al Port Olímpic: yacht in darsena e tavoli sulla sabbia.",
      pt: "Restaurantes na praia do Port Olímpic — iates na dársena e mesas na areia.",
    },
  },
  {
    id: "star-island",
    kind: "place",
    featured: "scenic",
    name: "Star Island",
    city: "Miami Beach",
    country: "United States",
    lat: 25.777,
    lng: -80.151,
    image: "/featured/star-island.jpg",
    minutesByYacht: 14,
    minutesByCar: 0,
    blurb: {
      en: "Slow cruise past Miami’s most photographed waterfront mansions on Biscayne Bay.",
      es: "Crucero lento frente a las mansiones más fotografiadas de Miami en Biscayne Bay.",
      fr: "Croisière lente devant les villas les plus photographiées de Miami.",
      it: "Crociera lenta davanti alle ville più fotografate di Miami.",
      pt: "Cruzeiro lento diante das mansões mais fotografadas de Miami.",
    },
  },
  {
    id: "vizcaya",
    kind: "place",
    featured: "scenic",
    name: "Vizcaya",
    city: "Coconut Grove",
    country: "United States",
    lat: 25.7434,
    lng: -80.2104,
    image: "/featured/vizcaya.jpg",
    minutesByYacht: 16,
    minutesByCar: 0,
    blurb: {
      en: "Renaissance villa and stone barge on Biscayne Bay — the scenic Grove run from Miami Beach.",
      es: "Villa renacentista y barcaza de piedra en Biscayne Bay, el crucero escénico del Grove.",
      fr: "Villa Renaissance et barge de pierre sur Biscayne Bay, la croisière du Grove.",
      it: "Villa rinascimentale e barge di pietra su Biscayne Bay, la crociera del Grove.",
      pt: "Vila renascentista e barcaça de pedra em Biscayne Bay, o cruzeiro do Grove.",
    },
  },
  {
    id: "palm-beach-estates",
    kind: "place",
    featured: "scenic",
    name: "Palm Beach Estates",
    city: "Palm Beach",
    country: "United States",
    lat: 26.7056,
    lng: -80.041,
    image: "/featured/palm-beach-estates.jpg",
    minutesByYacht: 45,
    minutesByCar: 0,
    blurb: {
      en: "Intracoastal mansions and private docks on Lake Worth — the golden-hour run from FTL.",
      es: "Mansiones del Intracoastal y muelles privados en Lake Worth, al atardecer desde FTL.",
      fr: "Villas de l’Intracoastal et pontons privés sur Lake Worth, au coucher du soleil.",
      it: "Ville sull’Intracoastal e pontili privati su Lake Worth, all’ora d’oro da FTL.",
      pt: "Mansões do Intracoastal e cais privados em Lake Worth, ao pôr do sol desde FTL.",
    },
  },
  {
    id: "ile-sainte-marguerite",
    kind: "place",
    featured: "scenic",
    name: "Île Sainte-Marguerite",
    city: "Cannes",
    country: "France",
    lat: 43.5225,
    lng: 7.0467,
    image: "/featured/ile-sainte-marguerite.jpg",
    minutesByYacht: 20,
    minutesByCar: 0,
    blurb: {
      en: "Pine island and Fort Royal in the Lérins — the scenic hop from the Cannes quays.",
      es: "Isla de pinos y Fort Royal en las Lérins: el salto escénico desde los muelles de Cannes.",
      fr: "Île de pins et Fort Royal aux Lérins — la traversée depuis les quais de Cannes.",
      it: "Isola di pini e Fort Royal alle Lérins: il salto scenico dai moli di Cannes.",
      pt: "Ilha de pinheiros e Fort Royal nas Lérins — o salto cênico dos cais de Cannes.",
    },
  },
];

export function featuredByKind(kind: FeaturedKind) {
  return featuredPlaces.filter((p) => p.featured === kind);
}
