import type { Place } from "./places";

type HubRow = [
  id: string,
  kind: "marina" | "port",
  name: string,
  city: string,
  country: string,
  lat: number,
  lng: number,
];

const IMAGES = [
  "/fleet/ftl-marina.jpg",
  "/fleet/miami-skyline.jpg",
  "/fleet/yacht-1.jpg",
  "/fleet/center-console.jpg",
  "/fleet/sunset.jpg",
  "/hero-poster.jpg",
];

const rows: HubRow[] = [
  ["bahia-mar", "marina", "Bahia Mar Yachting Center", "Fort Lauderdale", "United States", 26.1125, -80.1078],
  ["pier-66-marina", "marina", "Pier 66 Marina", "Fort Lauderdale", "United States", 26.101, -80.117],
  ["hilton-ftl-marina", "marina", "Hilton Fort Lauderdale Marina", "Fort Lauderdale", "United States", 26.118, -80.137],
  ["lauderdale-marine-center", "marina", "Lauderdale Marine Center", "Fort Lauderdale", "United States", 26.085, -80.16],
  ["harbour-towne", "marina", "Harbour Towne Marina", "Dania Beach", "United States", 26.058, -80.115],
  ["hall-of-fame-marina", "marina", "Hall of Fame Marina", "Fort Lauderdale", "United States", 26.116, -80.108],
  ["turnberry-isle", "marina", "Turnberry Isle Marina", "Aventura", "United States", 25.958, -80.126],
  ["crandon-park-marina", "marina", "Crandon Park Marina", "Key Biscayne", "United States", 25.719, -80.155],
  ["grove-harbour", "marina", "Grove Harbour Marina", "Coconut Grove", "United States", 25.728, -80.238],
  ["sea-isle-marina", "marina", "Sea Isle Marina", "Miami", "United States", 25.779, -80.186],
  ["matheson-hammock", "marina", "Matheson Hammock Marina", "Coral Gables", "United States", 25.679, -80.26],
  ["ocean-reef-club", "marina", "Ocean Reef Club Marina", "Key Largo", "United States", 25.309, -80.276],
  ["faro-blanco", "marina", "Faro Blanco Resort & Yacht Club", "Marathon", "United States", 24.713, -81.105],
  ["key-west-seaport", "marina", "Key West Historic Seaport", "Key West", "United States", 24.56, -81.807],
  ["naples-city-dock", "marina", "City of Naples Marina", "Naples", "United States", 26.134, -81.788],
  ["marco-island-marina", "marina", "Marco Island Marina", "Marco Island", "United States", 25.974, -81.728],
  ["sarasota-marina", "marina", "Marina Jack", "Sarasota", "United States", 27.333, -82.545],
  ["st-pete-marina", "marina", "St. Petersburg Marina", "St. Petersburg", "United States", 27.77, -82.63],
  ["tampa-channelside", "marina", "Tampa Marriott Waterside Marina", "Tampa", "United States", 27.941, -82.453],
  ["destin-harbor", "marina", "Destin Harbor Boardwalk", "Destin", "United States", 30.392, -86.495],
  ["pensacola-bay", "marina", "Pensacola Bay Marina", "Pensacola", "United States", 30.403, -87.213],
  ["jacksonville-lsc", "marina", "The Landings at St. Johns", "Jacksonville", "United States", 30.322, -81.66],
  ["port-of-tampa", "port", "Port Tampa Bay", "Tampa", "United States", 27.93, -82.446],
  ["port-canaveral", "port", "Port Canaveral", "Cape Canaveral", "United States", 28.41, -80.608],
  ["port-of-jacksonville", "port", "JAXPORT", "Jacksonville", "United States", 30.385, -81.558],
  ["port-of-key-west", "port", "Port of Key West", "Key West", "United States", 24.555, -81.807],
  ["north-cove", "marina", "North Cove Marina", "New York", "United States", 40.713, -74.016],
  ["chelsea-piers", "marina", "Chelsea Piers", "New York", "United States", 40.747, -74.009],
  ["newport-ri", "marina", "Newport Yachting Center", "Newport", "United States", 41.486, -71.317],
  ["newport-shipyard", "marina", "Newport Shipyard", "Newport", "United States", 41.492, -71.322],
  ["annapolis-city-dock", "marina", "Annapolis City Dock", "Annapolis", "United States", 38.977, -76.485],
  ["baltimore-inner-harbor", "marina", "Baltimore Inner Harbor Marina", "Baltimore", "United States", 39.283, -76.609],
  ["charleston-city-marina", "marina", "Charleston City Marina", "Charleston", "United States", 32.776, -79.955],
  ["savannah-harbour", "marina", "Westin Savannah Harbor Marina", "Savannah", "United States", 32.099, -81.084],
  ["norfolk-waterside", "marina", "Waterside Marina", "Norfolk", "United States", 36.844, -76.291],
  ["boston-rowes-wharf", "marina", "Rowes Wharf Marina", "Boston", "United States", 42.356, -71.05],
  ["boston-constitution", "marina", "Constitution Marina", "Boston", "United States", 42.372, -71.06],
  ["portland-me-marina", "marina", "DiMillo’s Marina", "Portland", "United States", 43.656, -70.252],
  ["montauk-yacht-club", "marina", "Montauk Yacht Club", "Montauk", "United States", 41.072, -71.935],
  ["sag-harbor", "marina", "Sag Harbor Yacht Club", "Sag Harbor", "United States", 41.003, -72.295],
  ["marina-del-rey", "marina", "Marina del Rey", "Los Angeles", "United States", 33.975, -118.447],
  ["san-diego-sunroad", "marina", "Sunroad Resort Marina", "San Diego", "United States", 32.708, -117.166],
  ["san-diego-shelter", "marina", "Shelter Island Marina", "San Diego", "United States", 32.715, -117.225],
  ["newport-beach-balboa", "marina", "Balboa Yacht Basin", "Newport Beach", "United States", 33.603, -117.898],
  ["long-beach-downtown", "marina", "Downtown Long Beach Marina", "Long Beach", "United States", 33.762, -118.192],
  ["sf-south-beach", "marina", "South Beach Harbor", "San Francisco", "United States", 37.78, -122.388],
  ["sausalito-yacht", "marina", "Sausalito Yacht Harbor", "Sausalito", "United States", 37.859, -122.485],
  ["seattle-bell-harbor", "marina", "Bell Harbor Marina", "Seattle", "United States", 47.61, -122.348],
  ["seattle-elliott-bay", "marina", "Elliott Bay Marina", "Seattle", "United States", 47.629, -122.393],
  ["honolulu-ala-wai", "marina", "Ala Wai Harbor", "Honolulu", "United States", 21.286, -157.839],
  ["honolulu-kewalo", "marina", "Kewalo Basin Harbor", "Honolulu", "United States", 21.291, -157.86],
  ["galveston-yacht-basin", "marina", "Galveston Yacht Basin", "Galveston", "United States", 29.319, -94.778],
  ["new-orleans-tchefuncte", "marina", "Orleans Marina", "New Orleans", "United States", 30.027, -90.113],
  ["chicago-burnham", "marina", "Burnham Harbor", "Chicago", "United States", 41.856, -87.613],
  ["detroit-uniroyal", "marina", "Detroit Yacht Club", "Detroit", "United States", 42.348, -82.974],
  ["port-of-ny", "port", "Port of New York", "New York", "United States", 40.684, -74.074],
  ["port-of-la", "port", "Port of Los Angeles", "Los Angeles", "United States", 33.74, -118.272],
  ["port-of-long-beach", "port", "Port of Long Beach", "Long Beach", "United States", 33.755, -118.216],
  ["port-of-miami-cargo", "port", "PortMiami Cargo", "Miami", "United States", 25.774, -80.171],
  ["port-of-charleston", "port", "Port of Charleston", "Charleston", "United States", 32.787, -79.924],
  ["port-of-savannah", "port", "Port of Savannah", "Savannah", "United States", 32.128, -81.14],
  ["port-of-houston", "port", "Port of Houston", "Houston", "United States", 29.737, -95.265],
  ["port-of-seattle", "port", "Port of Seattle", "Seattle", "United States", 47.59, -122.342],
  ["port-of-oakland", "port", "Port of Oakland", "Oakland", "United States", 37.797, -122.279],
  ["port-of-boston", "port", "Port of Boston", "Boston", "United States", 42.352, -71.04],
  ["port-of-honolulu", "port", "Honolulu Harbor", "Honolulu", "United States", 21.306, -157.866],
  ["coal-harbour", "marina", "Coal Harbour Marina", "Vancouver", "Canada", 49.291, -123.125],
  ["vancouver-false-creek", "marina", "False Creek Yacht Club", "Vancouver", "Canada", 49.271, -123.134],
  ["victoria-causeway", "marina", "Causeway Marina", "Victoria", "Canada", 48.422, -123.377],
  ["toronto-outer-harbour", "marina", "Outer Harbour Marina", "Toronto", "Canada", 43.64, -79.321],
  ["montreal-old-port", "marina", "Old Port of Montreal Marina", "Montreal", "Canada", 45.504, -73.553],
  ["halifax-waterfront", "marina", "Halifax Waterfront Marina", "Halifax", "Canada", 44.647, -63.57],
  ["port-of-vancouver", "port", "Port of Vancouver", "Vancouver", "Canada", 49.289, -123.111],
  ["port-of-montreal", "port", "Port of Montreal", "Montreal", "Canada", 45.542, -73.53],
  ["yacht-haven-grande", "marina", "Yacht Haven Grande", "Charlotte Amalie", "U.S. Virgin Islands", 18.3358, -64.9231],
  ["american-yacht-harbor", "marina", "American Yacht Harbor", "Red Hook", "U.S. Virgin Islands", 18.322, -64.853],
  ["virgin-gorda-yacht", "marina", "Virgin Gorda Yacht Harbour", "Spanish Town", "British Virgin Islands", 18.445, -64.439],
  ["nanny-cay", "marina", "Nanny Cay Marina", "Tortola", "British Virgin Islands", 18.4, -64.635],
  ["village-cay", "marina", "Village Cay Marina", "Road Town", "British Virgin Islands", 18.424, -64.618],
  ["atlantis-marina", "marina", "Atlantis Marina", "Nassau", "Bahamas", 25.0858, -77.3229],
  ["harborside-atlantis", "marina", "Harborside Resort Marina", "Paradise Island", "Bahamas", 25.083, -77.316],
  ["bimini-big-game", "marina", "Bimini Big Game Club Marina", "Alice Town", "Bahamas", 25.727, -79.297],
  ["albany-bahamas", "marina", "Albany Marina", "New Providence", "Bahamas", 25.0, -77.533],
  ["exuma-yacht-club", "marina", "February Point / Georgetown", "Great Exuma", "Bahamas", 23.51, -75.767],
  ["staniel-cay", "marina", "Staniel Cay Yacht Club", "Staniel Cay", "Bahamas", 24.175, -76.44],
  ["freeport-lucaya", "marina", "Port Lucaya Marina", "Freeport", "Bahamas", 26.508, -78.642],
  ["port-nassau", "port", "Prince George Wharf", "Nassau", "Bahamas", 25.077, -77.343],
  ["gustavia", "marina", "Port de Gustavia", "Gustavia", "Saint Barthélemy", 17.899, -62.85],
  ["simpson-bay", "marina", "Simpson Bay Marina", "Simpson Bay", "Sint Maarten", 18.038, -63.094],
  ["isle-de-sol", "marina", "Isle de Sol Marina", "Simpson Bay", "Sint Maarten", 18.034, -63.105],
  ["marigot-stmartin", "marina", "Fort Louis Marina", "Marigot", "Saint Martin", 18.07, -63.085],
  ["english-harbour", "marina", "Nelson’s Dockyard", "English Harbour", "Antigua and Barbuda", 17.007, -61.764],
  ["falmouth-antigua", "marina", "Falmouth Harbour Marina", "Falmouth", "Antigua and Barbuda", 17.016, -61.771],
  ["rodney-bay", "marina", "Rodney Bay Marina", "Gros Islet", "Saint Lucia", 14.075, -60.951],
  ["marigot-stlucia", "marina", "Marigot Bay Marina", "Marigot Bay", "Saint Lucia", 13.965, -61.026],
  ["port-st-charles", "marina", "Port St. Charles", "Speightstown", "Barbados", 13.25, -59.644],
  ["bridgetown-marina", "marina", "Barbados Yacht Club", "Bridgetown", "Barbados", 13.087, -59.614],
  ["le-marin", "marina", "Marina du Marin", "Le Marin", "Martinique", 14.47, -60.87],
  ["pointe-a-pitre", "marina", "Marina de Pointe-à-Pitre", "Pointe-à-Pitre", "Guadeloupe", 16.233, -61.536],
  ["st-georges-grenada", "marina", "Port Louis Marina", "St. George’s", "Grenada", 12.049, -61.748],
  ["chaguaramas", "marina", "CrewsInn Marina", "Chaguaramas", "Trinidad and Tobago", 10.677, -61.638],
  ["casa-de-campo", "marina", "Marina Casa de Campo", "La Romana", "Dominican Republic", 18.421, -68.93],
  ["cap-cana", "marina", "Marina Cap Cana", "Punta Cana", "Dominican Republic", 18.508, -68.375],
  ["puerto-bahia-samana", "marina", "Puerto Bahía", "Samaná", "Dominican Republic", 19.194, -69.338],
  ["san-juan-club-nautico", "marina", "Club Náutico de San Juan", "San Juan", "Puerto Rico", 18.458, -66.085],
  ["palmas-del-mar", "marina", "Palmas del Mar Yacht Club", "Humacao", "Puerto Rico", 18.082, -65.798],
  ["port-of-san-juan", "port", "Port of San Juan", "San Juan", "Puerto Rico", 18.46, -66.11],
  ["montego-bay-yacht", "marina", "Montego Bay Yacht Club", "Montego Bay", "Jamaica", 18.463, -77.932],
  ["errol-flynn-marina", "marina", "Errol Flynn Marina", "Port Antonio", "Jamaica", 18.182, -76.451],
  ["cayman-yacht-club", "marina", "Cayman Islands Yacht Club", "Grand Cayman", "Cayman Islands", 19.35, -81.379],
  ["blue-haven-tci", "marina", "Blue Haven Marina", "Providenciales", "Turks and Caicos", 21.807, -72.168],
  ["hamilton-princess", "marina", "Hamilton Princess Marina", "Hamilton", "Bermuda", 32.292, -64.788],
  ["dockyard-bermuda", "marina", "Royal Naval Dockyard", "Sandys", "Bermuda", 32.323, -64.835],
  ["willemstad-cocoa", "marina", "Seru Boca Marina", "Willemstad", "Curaçao", 12.107, -68.862],
  ["aruba-varadero", "marina", "Varadero Aruba Marina", "Oranjestad", "Aruba", 12.51, -70.038],
  ["kralendijk-harbour", "marina", "Harbour Village Marina", "Kralendijk", "Bonaire", 12.16, -68.284],
  ["cabo-san-lucas", "marina", "Marina Cabo San Lucas", "Cabo San Lucas", "Mexico", 22.879, -109.908],
  ["vallarta", "marina", "Marina Vallarta", "Puerto Vallarta", "Mexico", 20.658, -105.248],
  ["puerto-los-cabos", "marina", "Puerto Los Cabos", "San José del Cabo", "Mexico", 23.053, -109.673],
  ["la-paz-marina", "marina", "Marina Costa Baja", "La Paz", "Mexico", 24.21, -110.3],
  ["ensenada-cruiseport", "marina", "Cruiseport Village Marina", "Ensenada", "Mexico", 31.855, -116.627],
  ["puerto-aventuras", "marina", "Puerto Aventuras Marina", "Puerto Aventuras", "Mexico", 20.502, -87.007],
  ["isla-mujeres-marina", "marina", "Marina Puerto Isla Mujeres", "Isla Mujeres", "Mexico", 21.246, -86.743],
  ["cozumel-puerto", "marina", "Puerto de Abrigo", "Cozumel", "Mexico", 20.48, -86.973],
  ["cancun-port", "port", "Puerto Juárez / Cancún", "Cancún", "Mexico", 21.191, -86.807],
  ["acapulco-yacht", "marina", "Club de Yates de Acapulco", "Acapulco", "Mexico", 16.844, -99.905],
  ["mazatlan-marina", "marina", "Marina Mazatlán", "Mazatlán", "Mexico", 23.275, -106.458],
  ["flamenco", "marina", "Flamenco Marina", "Panama City", "Panama", 8.913, -79.521],
  ["shelter-bay", "marina", "Shelter Bay Marina", "Colón", "Panama", 9.368, -79.952],
  ["vista-mar-panama", "marina", "Vista Mar Marina", "San Carlos", "Panama", 8.53, -79.92],
  ["port-of-colon", "port", "Port of Colón", "Colón", "Panama", 9.353, -79.905],
  ["port-of-balboa", "port", "Port of Balboa", "Balboa", "Panama", 8.953, -79.566],
  ["los-suenos", "marina", "Los Sueños Marina", "Herradura", "Costa Rica", 9.664, -84.669],
  ["flamingo-cr", "marina", "Marina Papagayo", "Playas del Coco", "Costa Rica", 10.637, -85.681],
  ["golfito-banana-bay", "marina", "Banana Bay Marina", "Golfito", "Costa Rica", 8.639, -83.168],
  ["roatan-barefoot", "marina", "Barefoot Cay Marina", "Roatán", "Honduras", 16.358, -86.456],
  ["placencia-marina", "marina", "Placencia Marina", "Placencia", "Belize", 16.514, -88.366],
  ["rio-dulce", "marina", "Mario’s Marina", "Río Dulce", "Guatemala", 15.66, -88.994],
  ["cartagena-marina", "marina", "Club de Pesca", "Cartagena", "Colombia", 10.392, -75.538],
  ["manzanillo-cartagena", "marina", "Club Náutico Cartagena", "Cartagena", "Colombia", 10.4, -75.551],
  ["santa-marta-marina", "marina", "Marina Santa Marta", "Santa Marta", "Colombia", 11.245, -74.216],
  ["port-of-cartagena-co", "port", "Port of Cartagena", "Cartagena", "Colombia", 10.399, -75.528],
  ["gloria-rio", "marina", "Marina da Glória", "Rio de Janeiro", "Brazil", -22.92, -43.17],
  ["iacanga-rio", "marina", "Iate Clube do Rio de Janeiro", "Rio de Janeiro", "Brazil", -22.936, -43.17],
  ["santos-yacht", "marina", "Yacht Club Santos", "Santos", "Brazil", -23.988, -46.308],
  ["salvador-nautico", "marina", "Marina de Salvador", "Salvador", "Brazil", -12.971, -38.515],
  ["recife-yacht", "marina", "Cabanga Iate Clube", "Recife", "Brazil", -8.063, -34.871],
  ["port-of-santos", "port", "Port of Santos", "Santos", "Brazil", -23.96, -46.3],
  ["port-of-rio", "port", "Port of Rio de Janeiro", "Rio de Janeiro", "Brazil", -22.894, -43.191],
  ["yacht-club-argentino", "marina", "Yacht Club Argentino", "Buenos Aires", "Argentina", -34.571, -58.398],
  ["punta-del-este-yacht", "marina", "Yacht Club Punta del Este", "Punta del Este", "Uruguay", -34.967, -54.95],
  ["montevideo-yacht", "marina", "Yacht Club Uruguayo", "Montevideo", "Uruguay", -34.91, -56.21],
  ["valparaiso-yacht", "marina", "Club de Yates Valparaíso", "Valparaíso", "Chile", -33.036, -71.628],
  ["puerto-montt-marina", "marina", "Marina del Sur", "Puerto Montt", "Chile", -41.482, -72.96],
  ["callao-yacht", "marina", "Yacht Club Peruano", "Callao", "Peru", -12.06, -77.149],
  ["guayaquil-yacht", "marina", "Salinas Yacht Club", "Salinas", "Ecuador", -2.2, -80.967],
  ["port-hercule", "marina", "Port Hercule", "Monaco", "Monaco", 43.735, 7.425],
  ["port-vauban", "marina", "Port Vauban", "Antibes", "France", 43.587, 7.128],
  ["pierre-canto", "marina", "Port Pierre Canto", "Cannes", "France", 43.547, 7.037],
  ["vieux-port-cannes", "marina", "Vieux Port de Cannes", "Cannes", "France", 43.551, 7.013],
  ["saint-tropez", "marina", "Port de Saint-Tropez", "Saint-Tropez", "France", 43.272, 6.64],
  ["port-grimaud", "marina", "Port Grimaud", "Grimaud", "France", 43.273, 6.58],
  ["beaulieu-sur-mer", "marina", "Port de Beaulieu", "Beaulieu-sur-Mer", "France", 43.707, 7.335],
  ["villefranche", "marina", "Port de la Santé", "Villefranche-sur-Mer", "France", 43.704, 7.312],
  ["cap-ferrat", "marina", "Port de Saint-Jean-Cap-Ferrat", "Saint-Jean-Cap-Ferrat", "France", 43.688, 7.337],
  ["menton-garavan", "marina", "Port de Garavan", "Menton", "France", 43.783, 7.518],
  ["golfe-juan", "marina", "Port de Golfe-Juan", "Golfe-Juan", "France", 43.568, 7.076],
  ["mandelieu", "marina", "Port La Napoule", "Mandelieu", "France", 43.528, 6.938],
  ["hyeres-ayguade", "marina", "Port d’Hyères", "Hyères", "France", 43.108, 6.16],
  ["toulon-mourillon", "marina", "Port du Mourillon", "Toulon", "France", 43.11, 5.94],
  ["marseille-vieux-port", "marina", "Vieux-Port de Marseille", "Marseille", "France", 43.295, 5.374],
  ["bandol", "marina", "Port de Bandol", "Bandol", "France", 43.136, 5.754],
  ["setes-marine", "marina", "Port de Sète", "Sète", "France", 43.4, 3.699],
  ["port-camargue", "marina", "Port Camargue", "Le Grau-du-Roi", "France", 43.519, 4.13],
  ["la-ciotat", "marina", "Port de La Ciotat", "La Ciotat", "France", 43.174, 5.608],
  ["port-of-nice", "port", "Port of Nice", "Nice", "France", 43.695, 7.285],
  ["port-of-marseille", "port", "Grand Port Maritime", "Marseille", "France", 43.329, 5.353],
  ["port-of-toulon", "port", "Port of Toulon", "Toulon", "France", 43.12, 5.91],
  ["oneocean-vell", "marina", "OneOcean Port Vell", "Barcelona", "Spain", 41.378, 2.185],
  ["rcnb-barcelona", "marina", "Real Club Náutico Barcelona", "Barcelona", "Spain", 41.375, 2.178],
  ["club-de-mar-palma", "marina", "Club de Mar", "Palma", "Spain", 39.562, 2.633],
  ["stp-palma", "marina", "STP Shipyard Palma", "Palma", "Spain", 39.561, 2.642],
  ["port-portals", "marina", "Port Portals", "Calvià", "Spain", 39.53, 2.561],
  ["andratx", "marina", "Port d’Andratx", "Andratx", "Spain", 39.544, 2.382],
  ["alcudia-mallorca", "marina", "Port d’Alcúdia", "Alcúdia", "Spain", 39.837, 3.137],
  ["mahon-menorca", "marina", "Port de Maó", "Mahón", "Spain", 39.889, 4.265],
  ["marina-ibiza", "marina", "Marina Ibiza", "Ibiza", "Spain", 38.912, 1.442],
  ["ibiza-boteafoc", "marina", "Marina Botafoch", "Ibiza", "Spain", 38.914, 1.448],
  ["formentera-la-savina", "marina", "La Savina", "Formentera", "Spain", 38.734, 1.419],
  ["puerto-banus", "marina", "Puerto Banús", "Marbella", "Spain", 36.487, -4.953],
  ["puerto-jose-banus", "marina", "Puerto Deportivo Marbella", "Marbella", "Spain", 36.506, -4.885],
  ["sotogrande", "marina", "Puerto Sotogrande", "Sotogrande", "Spain", 36.287, -5.278],
  ["malaga-marina", "marina", "Muelle Uno / Marina Málaga", "Málaga", "Spain", 36.715, -4.416],
  ["alicante-marina", "marina", "Marina Deportiva de Alicante", "Alicante", "Spain", 38.343, -0.482],
  ["denia-marina", "marina", "Marina de Dénia", "Dénia", "Spain", 38.843, 0.117],
  ["valencia-rcn", "marina", "Real Club Náutico Valencia", "Valencia", "Spain", 39.46, -0.323],
  ["sitges-ain", "marina", "Port d’Aiguadolç", "Sitges", "Spain", 41.23, 1.82],
  ["tarragona-port", "marina", "Port Esportiu Tarragona", "Tarragona", "Spain", 41.108, 1.242],
  ["cartagena-spain-marina", "marina", "Puerto Deportivo Cartagena", "Cartagena", "Spain", 37.598, -0.986],
  ["a-coruna-marina", "marina", "Marina Coruña", "A Coruña", "Spain", 43.368, -8.402],
  ["vigo-rcn", "marina", "Real Club Náutico de Vigo", "Vigo", "Spain", 42.232, -8.727],
  ["bilbao-getxo", "marina", "Getxo Marina", "Getxo", "Spain", 43.337, -3.014],
  ["port-of-barcelona", "port", "Port of Barcelona", "Barcelona", "Spain", 41.345, 2.168],
  ["port-of-valencia", "port", "Port of Valencia", "Valencia", "Spain", 39.445, -0.318],
  ["port-of-algeciras", "port", "Port of Algeciras", "Algeciras", "Spain", 36.136, -5.435],
  ["port-of-bilbao", "port", "Port of Bilbao", "Bilbao", "Spain", 43.353, -3.055],
  ["portofino", "marina", "Portofino Marina", "Portofino", "Italy", 44.303, 9.21],
  ["porto-cervo", "marina", "Porto Cervo Marina", "Porto Cervo", "Italy", 41.136, 9.536],
  ["porto-rotondo", "marina", "Marina di Porto Rotondo", "Porto Rotondo", "Italy", 41.027, 9.546],
  ["olbia-marina", "marina", "Marina di Olbia", "Olbia", "Italy", 40.925, 9.515],
  ["cagliari-marina", "marina", "Marina di Cagliari", "Cagliari", "Italy", 39.205, 9.114],
  ["naples-molo", "marina", "Molo Beverello", "Naples", "Italy", 40.836, 14.256],
  ["capri-grande", "marina", "Marina Grande", "Capri", "Italy", 40.557, 14.238],
  ["ischia-porto", "marina", "Porto d’Ischia", "Ischia", "Italy", 40.745, 13.944],
  ["amalfi-port", "marina", "Porto di Amalfi", "Amalfi", "Italy", 40.634, 14.603],
  ["positano-pier", "marina", "Spiaggia Grande / Positano", "Positano", "Italy", 40.628, 14.485],
  ["salerno-marina", "marina", "Marina d’Arechi", "Salerno", "Italy", 40.647, 14.823],
  ["venezia-marina", "marina", "Marina di Venezia", "Venice", "Italy", 45.433, 12.37],
  ["venezia-san-giorgio", "marina", "Compagnia della Vela", "Venice", "Italy", 45.429, 12.344],
  ["genoa-marina-porto-antico", "marina", "Marina Porto Antico", "Genoa", "Italy", 44.41, 8.926],
  ["sanremo-porto", "marina", "Porto di Sanremo", "Sanremo", "Italy", 43.813, 7.776],
  ["viareggio-darsena", "marina", "Darsena Viareggio", "Viareggio", "Italy", 43.863, 10.248],
  ["livorno-nautica", "marina", "Porto Mediceo", "Livorno", "Italy", 43.551, 10.302],
  ["la-spezia-porto", "marina", "Porto Lotti", "La Spezia", "Italy", 44.098, 9.86],
  ["gaeta-base", "marina", "Base Nautica Flavio Gioia", "Gaeta", "Italy", 41.209, 13.57],
  ["rome-ostia", "marina", "Porto Turistico di Roma", "Ostia", "Italy", 41.737, 12.25],
  ["palermo-marina", "marina", "Marina Villa Igiea", "Palermo", "Italy", 38.145, 13.372],
  ["syracuse-marina", "marina", "Marina di Siracusa", "Syracuse", "Italy", 37.06, 15.287],
  ["taormina-giardini", "marina", "Porto di Giardini Naxos", "Taormina", "Italy", 37.828, 15.271],
  ["bari-marina", "marina", "Marina di Bari", "Bari", "Italy", 41.138, 16.868],
  ["brindisi-marina", "marina", "Marina di Brindisi", "Brindisi", "Italy", 40.641, 17.946],
  ["ancona-marina", "marina", "Marina Dorica", "Ancona", "Italy", 43.615, 13.508],
  ["trieste-marina", "marina", "Porto San Rocco", "Muggia", "Italy", 45.603, 13.756],
  ["rimini-marina", "marina", "Marina di Rimini", "Rimini", "Italy", 44.074, 12.564],
  ["port-of-genoa", "port", "Port of Genoa", "Genoa", "Italy", 44.405, 8.928],
  ["port-of-civitavecchia", "port", "Port of Civitavecchia", "Civitavecchia", "Italy", 42.094, 11.789],
  ["port-of-livorno", "port", "Port of Livorno", "Livorno", "Italy", 43.553, 10.302],
  ["port-of-naples", "port", "Port of Naples", "Naples", "Italy", 40.84, 14.27],
  ["port-of-venice", "port", "Port of Venice", "Venice", "Italy", 45.438, 12.26],
  ["port-of-palermo", "port", "Port of Palermo", "Palermo", "Italy", 38.133, 13.37],
  ["flisvos", "marina", "Flisvos Marina", "Athens", "Greece", 37.933, 23.685],
  ["alimos-marina", "marina", "Alimos Marina", "Athens", "Greece", 37.91, 23.7],
  ["zeas-piraeus", "marina", "Zea Marina", "Piraeus", "Greece", 37.937, 23.648],
  ["mykonos-tourlos", "marina", "Tourlos Marina", "Mykonos", "Greece", 37.465, 25.324],
  ["paros-parikia", "marina", "Parikia Harbour", "Paros", "Greece", 37.085, 25.15],
  ["naxos-harbour", "marina", "Naxos Harbour", "Naxos", "Greece", 37.106, 25.373],
  ["santorini-athinios", "port", "Athinios Port", "Santorini", "Greece", 36.387, 25.431],
  ["rhodes-mandraki", "marina", "Mandraki Harbour", "Rhodes", "Greece", 36.451, 28.227],
  ["kos-marina", "marina", "Kos Marina", "Kos", "Greece", 36.89, 27.302],
  ["corfu-gouvia", "marina", "Gouvia Marina", "Corfu", "Greece", 39.648, 19.852],
  ["lefkas-marina", "marina", "Lefkas Marina", "Lefkada", "Greece", 38.83, 20.713],
  ["kefalonia-fiskardo", "marina", "Fiskardo Harbour", "Kefalonia", "Greece", 38.458, 20.577],
  ["zakynthos-port", "marina", "Zakynthos Harbour", "Zakynthos", "Greece", 37.788, 20.899],
  ["chania-marina", "marina", "Chania Venetian Harbour", "Chania", "Greece", 35.518, 24.016],
  ["heraklion-marina", "marina", "Heraklion Marina", "Heraklion", "Greece", 35.34, 25.136],
  ["port-of-piraeus", "port", "Port of Piraeus", "Piraeus", "Greece", 37.944, 23.646],
  ["port-of-thessaloniki", "port", "Port of Thessaloniki", "Thessaloniki", "Greece", 40.635, 22.935],
  ["aci-split", "marina", "ACI Marina Split", "Split", "Croatia", 43.503, 16.442],
  ["aci-trogir", "marina", "ACI Marina Trogir", "Trogir", "Croatia", 43.516, 16.25],
  ["dubrovnik-marina", "marina", "ACI Marina Dubrovnik", "Dubrovnik", "Croatia", 42.659, 18.088],
  ["hvar-harbour", "marina", "Hvar Harbour", "Hvar", "Croatia", 43.173, 16.442],
  ["korcula-harbour", "marina", "Korčula Harbour", "Korčula", "Croatia", 42.961, 17.136],
  ["zadar-marina", "marina", "Marina Zadar", "Zadar", "Croatia", 44.117, 15.227],
  ["sibenik-marina", "marina", "D-Marin Mandalina", "Šibenik", "Croatia", 43.716, 15.894],
  ["rovinj-aci", "marina", "ACI Marina Rovinj", "Rovinj", "Croatia", 45.08, 13.632],
  ["pula-aci", "marina", "ACI Marina Pula", "Pula", "Croatia", 44.873, 13.845],
  ["port-of-split", "port", "Port of Split", "Split", "Croatia", 43.504, 16.442],
  ["port-of-dubrovnik", "port", "Port of Dubrovnik", "Dubrovnik", "Croatia", 42.656, 18.087],
  ["porto-montenegro", "marina", "Porto Montenegro", "Tivat", "Montenegro", 42.435, 18.692],
  ["kotor-port", "marina", "Port of Kotor", "Kotor", "Montenegro", 42.425, 18.771],
  ["portoroz", "marina", "Marina Portorož", "Portorož", "Slovenia", 45.509, 13.595],
  ["ocean-village-gib", "marina", "Ocean Village", "Gibraltar", "Gibraltar", 36.147, -5.355],
  ["queensway-quay", "marina", "Queensway Quay Marina", "Gibraltar", "Gibraltar", 36.138, -5.353],
  ["grand-harbour-malta", "marina", "Grand Harbour Marina", "Valletta", "Malta", 35.888, 14.521],
  ["portomaso", "marina", "Portomaso Marina", "St. Julian’s", "Malta", 35.922, 14.495],
  ["mgmt-marina", "marina", "Mgarr Harbour", "Gozo", "Malta", 36.025, 14.295],
  ["cascais", "marina", "Cascais Marina", "Cascais", "Portugal", 38.693, -9.418],
  ["oeiras-marina", "marina", "Marina de Oeiras", "Oeiras", "Portugal", 38.678, -9.318],
  ["lisbon-docas", "marina", "Doca de Santo Amaro", "Lisbon", "Portugal", 38.697, -9.177],
  ["vilamoura", "marina", "Marina de Vilamoura", "Vilamoura", "Portugal", 37.072, -8.117],
  ["lagos-marina-pt", "marina", "Marina de Lagos", "Lagos", "Portugal", 37.1, -8.673],
  ["portimao-marina", "marina", "Marina de Portimão", "Portimão", "Portugal", 37.13, -8.535],
  ["porto-leixoes-marina", "marina", "Marina de Leixões", "Porto", "Portugal", 41.184, -8.705],
  ["port-of-lisbon", "port", "Port of Lisbon", "Lisbon", "Portugal", 38.713, -9.127],
  ["port-of-leixoes", "port", "Port of Leixões", "Porto", "Portugal", 41.185, -8.7],
  ["st-katharine", "marina", "St Katharine Docks", "London", "United Kingdom", 51.507, -0.072],
  ["london-limehouse", "marina", "Limehouse Basin", "London", "United Kingdom", 51.512, -0.04],
  ["cowes-yacht-haven", "marina", "Cowes Yacht Haven", "Cowes", "United Kingdom", 50.763, -1.299],
  ["yarmouth-harbour", "marina", "Yarmouth Harbour", "Yarmouth", "United Kingdom", 50.706, -1.5],
  ["ocean-village-soton", "marina", "Ocean Village Marina", "Southampton", "United Kingdom", 50.894, -1.393],
  ["plymouth-sutton", "marina", "Sutton Harbour", "Plymouth", "United Kingdom", 50.368, -4.133],
  ["dartmouth-dart", "marina", "Dart Marina", "Dartmouth", "United Kingdom", 50.351, -3.579],
  ["brighton-marina", "marina", "Brighton Marina", "Brighton", "United Kingdom", 50.813, -0.103],
  ["dover-marina", "marina", "Dover Marina", "Dover", "United Kingdom", 51.117, 1.314],
  ["ipswich-haven", "marina", "Ipswich Haven Marina", "Ipswich", "United Kingdom", 52.05, 1.16],
  ["liverpool-albert", "marina", "Liverpool Marina", "Liverpool", "United Kingdom", 53.391, -2.992],
  ["glasgow-clyde", "marina", "Rhu Marina", "Helensburgh", "United Kingdom", 56.018, -4.771],
  ["oban-harbour", "marina", "Oban Marina", "Oban", "United Kingdom", 56.412, -5.48],
  ["dublin-poolbeg", "marina", "Poolbeg Yacht Club", "Dublin", "Ireland", 53.342, -6.217],
  ["kinsale-yacht", "marina", "Kinsale Yacht Club", "Kinsale", "Ireland", 51.705, -8.518],
  ["cork-crosshaven", "marina", "Royal Cork Yacht Club", "Crosshaven", "Ireland", 51.807, -8.4],
  ["southampton-port", "port", "Port of Southampton", "Southampton", "United Kingdom", 50.896, -1.393],
  ["port-of-dover", "port", "Port of Dover", "Dover", "United Kingdom", 51.126, 1.327],
  ["port-of-london", "port", "Port of London", "London", "United Kingdom", 51.5, 0.05],
  ["port-of-liverpool", "port", "Port of Liverpool", "Liverpool", "United Kingdom", 53.466, -3.025],
  ["amsterdam-sixhaven", "marina", "Sixhaven", "Amsterdam", "Netherlands", 52.382, 4.905],
  ["amsterdam-westerdok", "marina", "Westerdoksdijk Marina", "Amsterdam", "Netherlands", 52.386, 4.89],
  ["rotterdam-veerdam", "marina", "Veerhaven", "Rotterdam", "Netherlands", 51.909, 4.482],
  ["scheveningen", "marina", "Jachthaven Scheveningen", "The Hague", "Netherlands", 52.104, 4.268],
  ["port-of-rotterdam", "port", "Port of Rotterdam", "Rotterdam", "Netherlands", 51.95, 4.141],
  ["port-of-amsterdam", "port", "Port of Amsterdam", "Amsterdam", "Netherlands", 52.41, 4.8],
  ["antwerp-yacht", "marina", "Jachthaven Antwerpen", "Antwerp", "Belgium", 51.23, 4.4],
  ["zeebrugge-marina", "marina", "Marina Zeebrugge", "Zeebrugge", "Belgium", 51.33, 3.207],
  ["ostend-yacht", "marina", "Royal North Sea Yacht Club", "Ostend", "Belgium", 51.236, 2.92],
  ["port-of-antwerp", "port", "Port of Antwerp", "Antwerp", "Belgium", 51.27, 4.37],
  ["hamburg-city-sport", "marina", "City Sporthafen Hamburg", "Hamburg", "Germany", 53.545, 9.974],
  ["kiel-hoern", "marina", "Sport- und Yachthafen Kiel", "Kiel", "Germany", 54.37, 10.156],
  ["rostock-warnemuende", "marina", "Yachthafen Hohe Düne", "Warnemünde", "Germany", 54.181, 12.09],
  ["travemuende", "marina", "Passathafen Travemünde", "Lübeck", "Germany", 53.96, 10.88],
  ["port-of-hamburg", "port", "Port of Hamburg", "Hamburg", "Germany", 53.546, 9.966],
  ["port-of-bremen", "port", "Port of Bremen / Bremerhaven", "Bremerhaven", "Germany", 53.555, 8.567],
  ["copenhagen-ofelia", "marina", "Ofelia Plads / Langelinie", "Copenhagen", "Denmark", 55.69, 12.6],
  ["copenhagen-sydhavn", "marina", "Sydhavn Marina", "Copenhagen", "Denmark", 55.647, 12.551],
  ["aarhus-marina", "marina", "Århus Havn Lystbådehavn", "Aarhus", "Denmark", 56.158, 10.226],
  ["port-of-copenhagen", "port", "Copenhagen Malmö Port", "Copenhagen", "Denmark", 55.704, 12.599],
  ["oslo-aker-brygge", "marina", "Aker Brygge Marina", "Oslo", "Norway", 59.911, 10.73],
  ["bergen-bradbenken", "marina", "Bradbenken / Vågen", "Bergen", "Norway", 60.397, 5.324],
  ["stavanger-vaagen", "marina", "Vågen Guest Harbour", "Stavanger", "Norway", 58.971, 5.733],
  ["port-of-oslo", "port", "Port of Oslo", "Oslo", "Norway", 59.904, 10.75],
  ["stockholm-wasahamnen", "marina", "Wasahamnen", "Stockholm", "Sweden", 59.327, 18.091],
  ["gothenburg-lotsholmen", "marina", "Långedrag / GKSS", "Gothenburg", "Sweden", 57.666, 11.85],
  ["malmo-limhamn", "marina", "Limhamns Småbåtshamn", "Malmö", "Sweden", 55.583, 12.935],
  ["port-of-gothenburg", "port", "Port of Gothenburg", "Gothenburg", "Sweden", 57.703, 11.932],
  ["helsinki-pohjoisranta", "marina", "Pohjoisranta Guest Harbour", "Helsinki", "Finland", 60.172, 24.965],
  ["tallinn-old-city", "marina", "Old City Marina", "Tallinn", "Estonia", 59.445, 24.76],
  ["riga-city-yacht", "marina", "City Yacht Club Riga", "Riga", "Latvia", 56.966, 24.091],
  ["gdansk-marina", "marina", "Marina Gdańsk", "Gdańsk", "Poland", 54.353, 18.658],
  ["gdynia-marina", "marina", "Marina Gdynia", "Gdynia", "Poland", 54.519, 18.553],
  ["st-petersburg-central", "marina", "Central Yacht Club", "Saint Petersburg", "Russia", 59.928, 30.243],
  ["istanbul-atakoy", "marina", "Ataköy Marina", "Istanbul", "Turkey", 40.974, 28.85],
  ["istanbul-kalamis", "marina", "Kalamış Marina", "Istanbul", "Turkey", 40.974, 29.037],
  ["bodrum-milta", "marina", "Milta Bodrum Marina", "Bodrum", "Turkey", 37.034, 27.43],
  ["gocek-dmarin", "marina", "D-Marin Göcek", "Göcek", "Turkey", 36.753, 28.944],
  ["marmaris-navyard", "marina", "Marmaris Yacht Marina", "Marmaris", "Turkey", 36.834, 28.311],
  ["fethiye-marina", "marina", "Ece Saray Marina", "Fethiye", "Turkey", 36.623, 29.102],
  ["cesme-marina", "marina", "D-Marin Çeşme", "Çeşme", "Turkey", 38.324, 26.303],
  ["antalya-setur", "marina", "Setur Antalya Marina", "Antalya", "Turkey", 36.885, 30.702],
  ["port-of-istanbul", "port", "Port of Istanbul", "Istanbul", "Turkey", 41.023, 28.985],
  ["limassol-marina", "marina", "Limassol Marina", "Limassol", "Cyprus", 34.671, 33.042],
  ["larnaca-marina", "marina", "Larnaca Marina", "Larnaca", "Cyprus", 34.917, 33.638],
  ["herzliya-marina", "marina", "Herzliya Marina", "Herzliya", "Israel", 32.164, 34.796],
  ["haifa-marina", "marina", "Haifa Marina", "Haifa", "Israel", 32.819, 34.995],
  ["ashdod-marina", "marina", "Ashdod Marina", "Ashdod", "Israel", 31.811, 34.637],
  ["port-of-haifa", "port", "Port of Haifa", "Haifa", "Israel", 32.82, 35.004],
  ["dubai-marina-yc", "marina", "Dubai Marina Yacht Club", "Dubai", "United Arab Emirates", 25.077, 55.139],
  ["dubai-creek-yacht", "marina", "Dubai Creek Yacht Club", "Dubai", "United Arab Emirates", 25.243, 55.334],
  ["yas-marina", "marina", "Yas Marina", "Abu Dhabi", "United Arab Emirates", 24.467, 54.607],
  ["abu-dhabi-intercontinental", "marina", "InterContinental Abu Dhabi Marina", "Abu Dhabi", "United Arab Emirates", 24.458, 54.325],
  ["ras-al-khaimah-al-hamra", "marina", "Al Hamra Marina", "Ras Al Khaimah", "United Arab Emirates", 25.684, 55.778],
  ["sharjah-mega", "marina", "Sharjah Marina", "Sharjah", "United Arab Emirates", 25.351, 55.385],
  ["port-rashid", "port", "Port Rashid", "Dubai", "United Arab Emirates", 25.267, 55.275],
  ["jebel-ali", "port", "Jebel Ali Port", "Dubai", "United Arab Emirates", 24.996, 55.061],
  ["port-zayed", "port", "Zayed Port", "Abu Dhabi", "United Arab Emirates", 24.531, 54.372],
  ["the-pearl-doha", "marina", "Porto Arabia / The Pearl", "Doha", "Qatar", 25.369, 51.552],
  ["lusail-marina", "marina", "Lusail Marina", "Lusail", "Qatar", 25.437, 51.501],
  ["port-of-doha", "port", "Hamad Port / Doha", "Doha", "Qatar", 25.286, 51.565],
  ["bahrain-marina", "marina", "Bahrain Yacht Club", "Manama", "Bahrain", 26.21, 50.6],
  ["mina-salman", "port", "Khalifa Bin Salman Port", "Manama", "Bahrain", 26.2, 50.615],
  ["muscat-marina", "marina", "Al Mouj Marina", "Muscat", "Oman", 23.64, 58.28],
  ["mutrah-corniche", "marina", "Mutrah Corniche", "Muscat", "Oman", 23.617, 58.563],
  ["jeddah-yacht", "marina", "Jeddah Yacht Club", "Jeddah", "Saudi Arabia", 21.485, 39.11],
  ["king-abdullah-port", "port", "King Abdullah Port", "Rabigh", "Saudi Arabia", 22.74, 39.0],
  ["tangier-city-port", "marina", "Tanger City Port", "Tangier", "Morocco", 35.789, -5.808],
  ["bouregreg-rabat", "marina", "Marina Bouregreg", "Rabat", "Morocco", 34.031, -6.822],
  ["agadir-marina", "marina", "Marina d’Agadir", "Agadir", "Morocco", 30.427, -9.615],
  ["casablanca-port", "port", "Port of Casablanca", "Casablanca", "Morocco", 33.605, -7.61],
  ["tangier-med", "port", "Tanger Med", "Tangier", "Morocco", 35.89, -5.5],
  ["sidi-bou-said", "marina", "Port de Sidi Bou Saïd", "Sidi Bou Saïd", "Tunisia", 36.868, 10.349],
  ["yasmine-hammamet", "marina", "Yasmine Hammamet", "Hammamet", "Tunisia", 36.38, 10.538],
  ["el-gouna-abu-tig", "marina", "Abu Tig Marina", "El Gouna", "Egypt", 27.387, 33.678],
  ["port-ghalib", "marina", "Port Ghalib", "Marsa Alam", "Egypt", 25.535, 34.638],
  ["alexandria-yacht", "marina", "Alexandria Yacht Club", "Alexandria", "Egypt", 31.211, 29.885],
  ["port-said", "port", "Port Said", "Port Said", "Egypt", 31.265, 32.302],
  ["port-of-alexandria", "port", "Port of Alexandria", "Alexandria", "Egypt", 31.183, 29.87],
  ["va-waterfront", "marina", "V&A Waterfront", "Cape Town", "South Africa", -33.903, 18.422],
  ["royal-cape-yc", "marina", "Royal Cape Yacht Club", "Cape Town", "South Africa", -33.921, 18.443],
  ["durban-yacht-mole", "marina", "Durban Yacht Mole", "Durban", "South Africa", -29.868, 31.046],
  ["port-elizabeth-yc", "marina", "Algoa Bay Yacht Club", "Gqeberha", "South Africa", -33.961, 25.635],
  ["port-of-cape-town", "port", "Port of Cape Town", "Cape Town", "South Africa", -33.907, 18.435],
  ["port-of-durban", "port", "Port of Durban", "Durban", "South Africa", -29.881, 31.027],
  ["walvis-bay-yacht", "marina", "Walvis Bay Yacht Club", "Walvis Bay", "Namibia", -22.957, 14.505],
  ["lagos-takwa-bay", "marina", "Lagos Yacht Club", "Lagos", "Nigeria", 6.438, 3.41],
  ["dakar-cayar", "marina", "Port de Dakar", "Dakar", "Senegal", 14.678, -17.43],
  ["mombasa-mbaraki", "marina", "Mombasa Yacht Club", "Mombasa", "Kenya", -4.07, 39.668],
  ["zanzibar-stone-town", "port", "Zanzibar Port", "Zanzibar", "Tanzania", -6.162, 39.188],
  ["victoria-seychelles", "marina", "Eden Island Marina", "Mahé", "Seychelles", -4.641, 55.47],
  ["port-louis-cau", "marina", "Le Caudan Waterfront", "Port Louis", "Mauritius", -20.161, 57.498],
  ["one15-singapore", "marina", "One°15 Marina", "Singapore", "Singapore", 1.246, 103.842],
  ["raffles-marina", "marina", "Raffles Marina", "Singapore", "Singapore", 1.342, 103.637],
  ["keppel-bay", "marina", "Keppel Bay Marina", "Singapore", "Singapore", 1.267, 103.813],
  ["port-singapore", "port", "Port of Singapore", "Singapore", "Singapore", 1.264, 103.819],
  ["rhkyc", "marina", "Royal Hong Kong Yacht Club", "Hong Kong", "Hong Kong", 22.284, 114.184],
  ["aberdeen-marina-club", "marina", "Aberdeen Marina Club", "Hong Kong", "Hong Kong", 22.247, 114.16],
  ["causeway-bay-typhoon", "marina", "Causeway Bay Typhoon Shelter", "Hong Kong", "Hong Kong", 22.283, 114.186],
  ["port-of-hong-kong", "port", "Port of Hong Kong", "Hong Kong", "Hong Kong", 22.308, 114.182],
  ["yacht-haven-phuket", "marina", "Yacht Haven Phuket", "Phuket", "Thailand", 8.109, 98.303],
  ["ao-po-grand", "marina", "Ao Po Grand Marina", "Phuket", "Thailand", 8.069, 98.365],
  ["royal-phuket-marina", "marina", "Royal Phuket Marina", "Phuket", "Thailand", 7.96, 98.4],
  ["ocean-marina-pattaya", "marina", "Ocean Marina Jomtien", "Pattaya", "Thailand", 12.87, 100.905],
  ["phuket-port", "port", "Phuket Deep Sea Port", "Phuket", "Thailand", 7.973, 98.365],
  ["langkawi-telaga", "marina", "Telaga Harbour Marina", "Langkawi", "Malaysia", 6.366, 99.681],
  ["langkawi-rebak", "marina", "Rebak Marina", "Langkawi", "Malaysia", 6.292, 99.698],
  ["port-klang", "port", "Port Klang", "Klang", "Malaysia", 3.0, 101.4],
  ["benoa-bali", "marina", "Benoa Marina", "Bali", "Indonesia", -8.743, 115.212],
  ["jakarta-ancol", "marina", "Marina Ancol", "Jakarta", "Indonesia", -6.118, 106.85],
  ["subic-bay-yacht", "marina", "Subic Bay Yacht Club", "Subic", "Philippines", 14.824, 120.283],
  ["manila-yacht-club", "marina", "Manila Yacht Club", "Manila", "Philippines", 14.558, 120.982],
  ["port-of-manila", "port", "Port of Manila", "Manila", "Philippines", 14.596, 120.954],
  ["mumbai-colaba", "marina", "Royal Bombay Yacht Club", "Mumbai", "India", 18.922, 72.834],
  ["goa-dona-paula", "marina", "Dona Paula Jetty", "Goa", "India", 15.46, 73.802],
  ["port-of-mumbai", "port", "Mumbai Port", "Mumbai", "India", 18.955, 72.845],
  ["male-marina", "marina", "Malé Hulhumalé Marina", "Malé", "Maldives", 4.21, 73.54],
  ["colombo-port-city", "marina", "Colombo Port City Yacht", "Colombo", "Sri Lanka", 6.95, 79.85],
  ["port-of-colombo", "port", "Port of Colombo", "Colombo", "Sri Lanka", 6.955, 79.844],
  ["osaka-yacht", "marina", "Nishinomiya Yacht Harbor", "Nishinomiya", "Japan", 34.717, 135.333],
  ["yokohama-marina", "marina", "Yokohama Bay Marina", "Yokohama", "Japan", 35.447, 139.646],
  ["tokyo-watts", "marina", "Wakasu Yacht Harbor", "Tokyo", "Japan", 35.62, 139.833],
  ["okinawa-naha", "marina", "Naha Port Marina", "Naha", "Japan", 26.213, 127.679],
  ["port-of-tokyo", "port", "Port of Tokyo", "Tokyo", "Japan", 35.62, 139.8],
  ["port-of-yokohama", "port", "Port of Yokohama", "Yokohama", "Japan", 35.44, 139.64],
  ["port-of-kobe", "port", "Port of Kobe", "Kobe", "Japan", 34.68, 135.2],
  ["busan-marina-club", "marina", "Busan Yacht Club", "Busan", "South Korea", 35.16, 129.16],
  ["port-of-busan", "port", "Port of Busan", "Busan", "South Korea", 35.103, 129.04],
  ["shanghai-the-bund-yacht", "marina", "Shanghai Yacht Club", "Shanghai", "China", 31.24, 121.49],
  ["sanya-serenity", "marina", "Serenity Marina", "Sanya", "China", 18.23, 109.5],
  ["shenzhen-shekou", "marina", "Shekou Yacht Club", "Shenzhen", "China", 22.479, 113.912],
  ["port-of-shanghai", "port", "Port of Shanghai", "Shanghai", "China", 31.366, 121.615],
  ["port-of-shenzhen", "port", "Port of Shenzhen", "Shenzhen", "China", 22.48, 113.9],
  ["port-of-ningbo", "port", "Port of Ningbo-Zhoushan", "Ningbo", "China", 29.87, 121.55],
  ["kaohsiung-yacht", "marina", "Kaohsiung Yacht Club", "Kaohsiung", "Taiwan", 22.615, 120.265],
  ["keelung-port", "port", "Port of Keelung", "Keelung", "Taiwan", 25.131, 121.75],
  ["sydney-superyacht", "marina", "Sydney Superyacht Marina", "Sydney", "Australia", -33.868, 151.185],
  ["d-maris-sydney", "marina", "d’Albora Marina Rushcutters", "Sydney", "Australia", -33.875, 151.228],
  ["woollahra", "marina", "Woollahra Sailing Club", "Sydney", "Australia", -33.87, 151.248],
  ["gold-coast-southport", "marina", "Southport Yacht Club", "Gold Coast", "Australia", -27.967, 153.422],
  ["brisbane-manly", "marina", "Moreton Bay Trailer Boat Club", "Manly", "Australia", -27.455, 153.193],
  ["cairns-marlin", "marina", "Cairns Marlin Marina", "Cairns", "Australia", -16.92, 145.778],
  ["whitsunday-airlie", "marina", "Abell Point Marina", "Airlie Beach", "Australia", -20.268, 148.717],
  ["perth-fremantle", "marina", "Fremantle Sailing Club", "Fremantle", "Australia", -32.065, 115.748],
  ["hobart-constitution", "marina", "Constitution Dock", "Hobart", "Australia", -42.882, 147.332],
  ["port-of-sydney", "port", "Port of Sydney", "Sydney", "Australia", -33.858, 151.201],
  ["port-of-melbourne", "port", "Port of Melbourne", "Melbourne", "Australia", -37.842, 144.932],
  ["port-of-brisbane", "port", "Port of Brisbane", "Brisbane", "Australia", -27.38, 153.17],
  ["port-of-fremantle", "port", "Port of Fremantle", "Fremantle", "Australia", -32.052, 115.745],
  ["viaduct-auckland", "marina", "Viaduct Harbour", "Auckland", "New Zealand", -36.842, 174.763],
  ["westhaven-auckland", "marina", "Westhaven Marina", "Auckland", "New Zealand", -36.84, 174.748],
  ["bay-of-islands", "marina", "Opua Marina", "Bay of Islands", "New Zealand", -35.316, 174.123],
  ["wellington-chaffers", "marina", "Chaffers Marina", "Wellington", "New Zealand", -41.29, 174.785],
  ["lyttelton-marina", "marina", "Lyttelton Marina", "Christchurch", "New Zealand", -43.605, 172.72],
  ["port-of-auckland", "port", "Port of Auckland", "Auckland", "New Zealand", -36.843, 174.78],
  ["papeete-marina", "marina", "Marina Taina", "Papeete", "French Polynesia", -17.59, -149.62],
  ["bougainville-noumea", "marina", "Port Moselle", "Nouméa", "New Caledonia", -22.276, 166.436],
  ["suva-royal-suva", "marina", "Royal Suva Yacht Club", "Suva", "Fiji", -18.148, 178.426],
  ["denarau", "marina", "Port Denarau Marina", "Nadi", "Fiji", -17.771, 177.381],
  ["port-vila", "marina", "Yachting World Marina", "Port Vila", "Vanuatu", -17.735, 168.313],
  ["apia-harbour", "port", "Apia Harbour", "Apia", "Samoa", -13.831, -171.766],
  ["pago-pago", "port", "Pago Pago Harbor", "Pago Pago", "American Samoa", -14.274, -170.69],
  ["guam-haputo", "marina", "Hap’s Reef / Agana Marina", "Hagåtña", "Guam", 13.478, 144.75],
  ["saipan-smc", "marina", "Smiling Cove Marina", "Saipan", "Northern Mariana Islands", 15.209, 145.719],
];

function blurbFor(kind: "marina" | "port", name: string, city: string, country: string) {
  if (kind === "port") {
    return {
      en: `${name} in ${city}, ${country}. Port for yacht arrivals and departures.`,
      es: `${name} en ${city}, ${country}. Puerto para llegadas y salidas en yate.`,
      fr: `${name} à ${city}, ${country}. Port pour arrivées et départs en yacht.`,
      it: `${name} a ${city}, ${country}. Porto per arrivi e partenze in yacht.`,
    };
  }
  return {
    en: `${name} in ${city}, ${country}. Marina for yacht arrivals and departures.`,
    es: `${name} en ${city}, ${country}. Marina para llegadas y salidas en yate.`,
    fr: `${name} à ${city}, ${country}. Marina pour arrivées et départs en yacht.`,
    it: `${name} a ${city}, ${country}. Marina per arrivi e partenze in yacht.`,
  };
}

export const worldHubs: Place[] = rows.map((row, index) => {
  const [id, kind, name, city, country, lat, lng] = row;
  return {
    id,
    kind,
    name,
    city,
    country,
    lat,
    lng,
    image: IMAGES[index % IMAGES.length],
    minutesByYacht: 20,
    minutesByCar: 0,
    blurb: blurbFor(kind, name, city, country),
  };
});
