import type { Localized } from "./locale";

export type YachtClass = "fast" | "small" | "luxurious";

export type Captain = {
  name: string;
  license: string;
  rating: number;
  trips: number;
  photo: string;
  verified: boolean;
};

export type YachtSource = "live" | "seed-real" | "catalog";

export type Yacht = {
  id: string;
  name: string;
  class: string;
  lengthFt: number;
  guests: number;
  hoursMin: number;
  marina: string;
  marinaId: string;
  image: string;
  lat: number;
  lng: number;
  etaMin: number;
  captain: Captain;
  blurb: Localized;
  traits: YachtClass[];
  listing?: boolean;
  photos?: string[];
  hin?: string;
  captainLanguages?: Array<"en" | "es" | "pt" | "fr">;
  captainRegion?: string;
  /** Live or seed-real inventory that can be paid with Stripe now. */
  bookable?: boolean;
  source?: YachtSource;
  kinds?: Array<"commute" | "tour" | "special">;
  priceFromUsd?: number;
};

function blurb(en: string, es: string, fr: string, it: string, pt: string): Localized {
  return { en, es, fr, it, pt };
}

export const DEFAULT_YACHT_ID = "tempest-42";

export const yachts: Yacht[] = [
  {
    id: "galeon",
    name: "Galeon",
    class: "Motor yacht",
    lengthFt: 50,
    guests: 13,
    hoursMin: 4,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/galeon.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["luxurious"],
    captain: {
      name: "Captain Elena Ruiz",
      license: "USCG Master 100 Ton",
      rating: 4.86,
      trips: 92,
      photo: "/crew/kaenz/selfie-1.jpg",
      verified: true,
    },
    blurb: blurb(
      "50 ft luxury yacht for up to 13. Skyline and Intracoastal from Miami Beach Marina.",
      "Yate de lujo de 50 ft para hasta 13. Skyline e Intracoastal desde Miami Beach Marina.",
      "Yacht de luxe de 50 ft pour 13 personnes. Skyline et Intracoastal depuis Miami Beach Marina.",
      "Yacht di lusso da 50 ft per 13 ospiti. Skyline e Intracoastal da Miami Beach Marina.",
      "Iate de luxo de 50 ft para até 13. Skyline e Intracoastal a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "tempest-42",
    name: "Tempest 42",
    class: "Express cruiser",
    lengthFt: 42,
    guests: 10,
    hoursMin: 3,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/tempest-42.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["fast"],
    captain: {
      name: "Captain Will Park",
      license: "USCG Master 50 Ton",
      rating: 4.87,
      trips: 111,
      photo: "/crew/kaenz/selfie-2.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft fast boat for up to 10. Beats the causeways from Island Gardens Miami.",
      "Bote rápido de 42 ft para hasta 10. Le gana a las calzadas desde Island Gardens Miami.",
      "Bateau rapide de 42 ft pour 10. Gagne sur les chaussées depuis Island Gardens Miami.",
      "Barca veloce da 42 ft per 10. Vince sulle calzate da Island Gardens Miami.",
      "Barco rápido de 42 ft para até 10. Ganha das calçadas a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "savvy",
    name: "SAVVY",
    class: "Day cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/savvy.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Nora Blake",
      license: "USCG Master 50 Ton",
      rating: 4.88,
      trips: 130,
      photo: "/crew/kaenz/selfie-3.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 32 ft boat for up to 8. Quick bay hops from Las Olas Marina.",
      "Bote ágil de 32 ft para hasta 8. Saltos rápidos desde Las Olas Marina.",
      "Bateau agile de 32 ft pour 8. Sauts rapides depuis Las Olas Marina.",
      "Barca agile da 32 ft per 8. Salti rapidi da Las Olas Marina.",
      "Barco ágil de 32 ft para até 8. Saltos rápidos a partir de Las Olas Marina.",
    ),
  },
  {
    id: "pink-lady",
    name: "Pink Lady",
    class: "Flybridge yacht",
    lengthFt: 50,
    guests: 12,
    hoursMin: 4,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/pink-lady.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["luxurious"],
    captain: {
      name: "Captain Marcus Cole",
      license: "USCG Master 100 Ton",
      rating: 4.89,
      trips: 149,
      photo: "/crew/kaenz/selfie-4.jpg",
      verified: true,
    },
    blurb: blurb(
      "50 ft luxury yacht for up to 12. Skyline and Intracoastal from Hollywood Marina.",
      "Yate de lujo de 50 ft para hasta 12. Skyline e Intracoastal desde Hollywood Marina.",
      "Yacht de luxe de 50 ft pour 12 personnes. Skyline et Intracoastal depuis Hollywood Marina.",
      "Yacht di lusso da 50 ft per 12 ospiti. Skyline e Intracoastal da Hollywood Marina.",
      "Iate de luxo de 50 ft para até 12. Skyline e Intracoastal a partir de Hollywood Marina.",
    ),
  },
  {
    id: "amani",
    name: "Amani",
    class: "Flybridge yacht",
    lengthFt: 46,
    guests: 12,
    hoursMin: 4,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/amani.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["luxurious"],
    captain: {
      name: "Captain Mia Chen",
      license: "USCG Master 100 Ton",
      rating: 4.9,
      trips: 168,
      photo: "/crew/kaenz/selfie-5.jpg",
      verified: true,
    },
    blurb: blurb(
      "46 ft luxury yacht for up to 12. Skyline and Intracoastal from Palm Beach Town Docks.",
      "Yate de lujo de 46 ft para hasta 12. Skyline e Intracoastal desde Palm Beach Town Docks.",
      "Yacht de luxe de 46 ft pour 12 personnes. Skyline et Intracoastal depuis Palm Beach Town Docks.",
      "Yacht di lusso da 46 ft per 12 ospiti. Skyline e Intracoastal da Palm Beach Town Docks.",
      "Iate de luxo de 46 ft para até 12. Skyline e Intracoastal a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "barolo",
    name: "Barolo",
    class: "Flybridge yacht",
    lengthFt: 45,
    guests: 12,
    hoursMin: 4,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/barolo.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["luxurious"],
    captain: {
      name: "Captain Camille Dubois",
      license: "USCG Master 100 Ton",
      rating: 4.91,
      trips: 187,
      photo: "/crew/kaenz/selfie-6.jpg",
      verified: true,
    },
    blurb: blurb(
      "45 ft luxury yacht for up to 12. Skyline and Intracoastal from Dinner Key Marina.",
      "Yate de lujo de 45 ft para hasta 12. Skyline e Intracoastal desde Dinner Key Marina.",
      "Yacht de luxe de 45 ft pour 12 personnes. Skyline et Intracoastal depuis Dinner Key Marina.",
      "Yacht di lusso da 45 ft per 12 ospiti. Skyline e Intracoastal da Dinner Key Marina.",
      "Iate de luxo de 45 ft para até 12. Skyline e Intracoastal a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "decisions",
    name: "Decisions",
    class: "Flybridge yacht",
    lengthFt: 48,
    guests: 12,
    hoursMin: 4,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/decisions.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["luxurious"],
    captain: {
      name: "Captain Luca Bianchi",
      license: "USCG Master 100 Ton",
      rating: 4.92,
      trips: 206,
      photo: "/crew/kaenz/selfie-7.jpg",
      verified: true,
    },
    blurb: blurb(
      "48 ft luxury yacht for up to 12. Skyline and Intracoastal from Haulover Park Marina.",
      "Yate de lujo de 48 ft para hasta 12. Skyline e Intracoastal desde Haulover Park Marina.",
      "Yacht de luxe de 48 ft pour 12 personnes. Skyline et Intracoastal depuis Haulover Park Marina.",
      "Yacht di lusso da 48 ft per 12 ospiti. Skyline e Intracoastal da Haulover Park Marina.",
      "Iate de luxo de 48 ft para até 12. Skyline e Intracoastal a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "knotty-lane",
    name: "Knotty Lane",
    class: "Express yacht",
    lengthFt: 48,
    guests: 12,
    hoursMin: 4,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/knotty-lane.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["luxurious"],
    captain: {
      name: "Captain Diego Santos",
      license: "USCG Master 100 Ton",
      rating: 4.93,
      trips: 225,
      photo: "/crew/kaenz/selfie-8.jpg",
      verified: true,
    },
    blurb: blurb(
      "48 ft luxury yacht for up to 12. Skyline and Intracoastal from Port Everglades.",
      "Yate de lujo de 48 ft para hasta 12. Skyline e Intracoastal desde Port Everglades.",
      "Yacht de luxe de 48 ft pour 12 personnes. Skyline et Intracoastal depuis Port Everglades.",
      "Yacht di lusso da 48 ft per 12 ospiti. Skyline e Intracoastal da Port Everglades.",
      "Iate de luxo de 48 ft para até 12. Skyline e Intracoastal a partir de Port Everglades.",
    ),
  },
  {
    id: "orion",
    name: "Orion",
    class: "Catamaran",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/orion.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["luxurious"],
    captain: {
      name: "Captain Sofia Alvarez",
      license: "USCG Master 100 Ton",
      rating: 4.94,
      trips: 244,
      photo: "/crew/kaenz/selfie-9.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from PortMiami.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde PortMiami.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis PortMiami.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da PortMiami.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de PortMiami.",
    ),
  },
  {
    id: "tequila",
    name: "Tequila",
    class: "Express yacht",
    lengthFt: 47,
    guests: 12,
    hoursMin: 4,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/tequila.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["luxurious"],
    captain: {
      name: "Captain James Okonkwo",
      license: "USCG Master 100 Ton",
      rating: 4.95,
      trips: 263,
      photo: "/crew/kaenz/selfie-10.jpg",
      verified: true,
    },
    blurb: blurb(
      "47 ft luxury yacht for up to 12. Skyline and Intracoastal from Miami Beach Marina.",
      "Yate de lujo de 47 ft para hasta 12. Skyline e Intracoastal desde Miami Beach Marina.",
      "Yacht de luxe de 47 ft pour 12 personnes. Skyline et Intracoastal depuis Miami Beach Marina.",
      "Yacht di lusso da 47 ft per 12 ospiti. Skyline e Intracoastal da Miami Beach Marina.",
      "Iate de luxo de 47 ft para até 12. Skyline e Intracoastal a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "vinya",
    name: "Vinya",
    class: "Flybridge yacht",
    lengthFt: 45,
    guests: 12,
    hoursMin: 4,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/vinya.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["luxurious"],
    captain: {
      name: "Captain Rafael Costa",
      license: "USCG Master 100 Ton",
      rating: 4.96,
      trips: 282,
      photo: "/crew/kaenz/selfie-11.jpg",
      verified: true,
    },
    blurb: blurb(
      "45 ft luxury yacht for up to 12. Skyline and Intracoastal from Island Gardens Miami.",
      "Yate de lujo de 45 ft para hasta 12. Skyline e Intracoastal desde Island Gardens Miami.",
      "Yacht de luxe de 45 ft pour 12 personnes. Skyline et Intracoastal depuis Island Gardens Miami.",
      "Yacht di lusso da 45 ft per 12 ospiti. Skyline e Intracoastal da Island Gardens Miami.",
      "Iate de luxo de 45 ft para até 12. Skyline e Intracoastal a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "quit-n-time",
    name: "Quit N Time",
    class: "Flybridge yacht",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/quit-n-time.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["luxurious"],
    captain: {
      name: "Captain Hannah Kim",
      license: "USCG Master 100 Ton",
      rating: 4.97,
      trips: 301,
      photo: "/crew/kaenz/selfie-12.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from Las Olas Marina.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde Las Olas Marina.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis Las Olas Marina.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da Las Olas Marina.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de Las Olas Marina.",
    ),
  },
  {
    id: "mamaseata",
    name: "Mamaseata",
    class: "Flybridge yacht",
    lengthFt: 38,
    guests: 10,
    hoursMin: 4,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/mamaseata.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["luxurious"],
    captain: {
      name: "Captain Emily Rossi",
      license: "USCG Master 100 Ton",
      rating: 4.98,
      trips: 320,
      photo: "/crew/kaenz/selfie-13.jpg",
      verified: true,
    },
    blurb: blurb(
      "38 ft luxury yacht for up to 10. Skyline and Intracoastal from Hollywood Marina.",
      "Yate de lujo de 38 ft para hasta 10. Skyline e Intracoastal desde Hollywood Marina.",
      "Yacht de luxe de 38 ft pour 10 personnes. Skyline et Intracoastal depuis Hollywood Marina.",
      "Yacht di lusso da 38 ft per 10 ospiti. Skyline e Intracoastal da Hollywood Marina.",
      "Iate de luxo de 38 ft para até 10. Skyline e Intracoastal a partir de Hollywood Marina.",
    ),
  },
  {
    id: "chichochu",
    name: "Chichochu",
    class: "Express cruiser",
    lengthFt: 40,
    guests: 10,
    hoursMin: 3,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/chichochu.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["fast"],
    captain: {
      name: "Captain Trent Hale",
      license: "USCG Master 50 Ton",
      rating: 4.99,
      trips: 339,
      photo: "/crew/kaenz/selfie-14.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft fast boat for up to 10. Beats the causeways from Palm Beach Town Docks.",
      "Bote rápido de 40 ft para hasta 10. Le gana a las calzadas desde Palm Beach Town Docks.",
      "Bateau rapide de 40 ft pour 10. Gagne sur les chaussées depuis Palm Beach Town Docks.",
      "Barca veloce da 40 ft per 10. Vince sulle calzate da Palm Beach Town Docks.",
      "Barco rápido de 40 ft para até 10. Ganha das calçadas a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "distraction",
    name: "Distraction",
    class: "Express cruiser",
    lengthFt: 42,
    guests: 10,
    hoursMin: 3,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/distraction-fl0592re.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["fast"],
    captain: {
      name: "Captain Ana Morales",
      license: "USCG Master 50 Ton",
      rating: 4.86,
      trips: 358,
      photo: "/crew/kaenz/selfie-15.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft fast boat for up to 10. Beats the causeways from Dinner Key Marina.",
      "Bote rápido de 42 ft para hasta 10. Le gana a las calzadas desde Dinner Key Marina.",
      "Bateau rapide de 42 ft pour 10. Gagne sur les chaussées depuis Dinner Key Marina.",
      "Barca veloce da 42 ft per 10. Vince sulle calzate da Dinner Key Marina.",
      "Barco rápido de 42 ft para até 10. Ganha das calçadas a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "dream-boat",
    name: "Dream Boat",
    class: "Express cruiser",
    lengthFt: 37,
    guests: 8,
    hoursMin: 3,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/dream-boat.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["fast"],
    captain: {
      name: "Captain Omar Haddad",
      license: "USCG Master 50 Ton",
      rating: 4.87,
      trips: 377,
      photo: "/crew/kaenz/selfie-16.jpg",
      verified: true,
    },
    blurb: blurb(
      "37 ft fast boat for up to 8. Beats the causeways from Haulover Park Marina.",
      "Bote rápido de 37 ft para hasta 8. Le gana a las calzadas desde Haulover Park Marina.",
      "Bateau rapide de 37 ft pour 8. Gagne sur les chaussées depuis Haulover Park Marina.",
      "Barca veloce da 37 ft per 8. Vince sulle calzate da Haulover Park Marina.",
      "Barco rápido de 37 ft para até 8. Ganha das calçadas a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "fantasea",
    name: "Fantasea",
    class: "Express cruiser",
    lengthFt: 40,
    guests: 10,
    hoursMin: 3,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/fantasea.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["fast"],
    captain: {
      name: "Captain Priya Nair",
      license: "USCG Master 50 Ton",
      rating: 4.88,
      trips: 396,
      photo: "/crew/kaenz/selfie-17.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft fast boat for up to 10. Beats the causeways from Port Everglades.",
      "Bote rápido de 40 ft para hasta 10. Le gana a las calzadas desde Port Everglades.",
      "Bateau rapide de 40 ft pour 10. Gagne sur les chaussées depuis Port Everglades.",
      "Barca veloce da 40 ft per 10. Vince sulle calzate da Port Everglades.",
      "Barco rápido de 40 ft para até 10. Ganha das calçadas a partir de Port Everglades.",
    ),
  },
  {
    id: "jetset",
    name: "JetSet",
    class: "Express cruiser",
    lengthFt: 40,
    guests: 10,
    hoursMin: 3,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/jetset.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["fast"],
    captain: {
      name: "Captain Jules Moreau",
      license: "USCG Master 50 Ton",
      rating: 4.89,
      trips: 415,
      photo: "/crew/kaenz/selfie-18.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft fast boat for up to 10. Beats the causeways from PortMiami.",
      "Bote rápido de 40 ft para hasta 10. Le gana a las calzadas desde PortMiami.",
      "Bateau rapide de 40 ft pour 10. Gagne sur les chaussées depuis PortMiami.",
      "Barca veloce da 40 ft per 10. Vince sulle calzate da PortMiami.",
      "Barco rápido de 40 ft para até 10. Ganha das calçadas a partir de PortMiami.",
    ),
  },
  {
    id: "josy",
    name: "Josy",
    class: "Express cruiser",
    lengthFt: 40,
    guests: 10,
    hoursMin: 3,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/josy.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["fast"],
    captain: {
      name: "Captain Mateo Vargas",
      license: "USCG Master 50 Ton",
      rating: 4.9,
      trips: 434,
      photo: "/crew/kaenz/selfie-19.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft fast boat for up to 10. Beats the causeways from Miami Beach Marina.",
      "Bote rápido de 40 ft para hasta 10. Le gana a las calzadas desde Miami Beach Marina.",
      "Bateau rapide de 40 ft pour 10. Gagne sur les chaussées depuis Miami Beach Marina.",
      "Barca veloce da 40 ft per 10. Vince sulle calzate da Miami Beach Marina.",
      "Barco rápido de 40 ft para até 10. Ganha das calçadas a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "vacilon",
    name: "Vacilón",
    class: "Express cruiser",
    lengthFt: 38,
    guests: 10,
    hoursMin: 3,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/vacilon-fl7634ln.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["fast"],
    captain: {
      name: "Captain Lina Kowalski",
      license: "USCG Master 50 Ton",
      rating: 4.91,
      trips: 453,
      photo: "/crew/kaenz/selfie-20.jpg",
      verified: true,
    },
    blurb: blurb(
      "38 ft fast boat for up to 10. Beats the causeways from Island Gardens Miami.",
      "Bote rápido de 38 ft para hasta 10. Le gana a las calzadas desde Island Gardens Miami.",
      "Bateau rapide de 38 ft pour 10. Gagne sur les chaussées depuis Island Gardens Miami.",
      "Barca veloce da 38 ft per 10. Vince sulle calzate da Island Gardens Miami.",
      "Barco rápido de 38 ft para até 10. Ganha das calçadas a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "icon",
    name: "ICON",
    class: "Day cruiser",
    lengthFt: 28,
    guests: 8,
    hoursMin: 3,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/icon-fl4916po.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Andre Baptiste",
      license: "USCG Master 50 Ton",
      rating: 4.92,
      trips: 472,
      photo: "/crew/kaenz/selfie-21.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 28 ft boat for up to 8. Quick bay hops from Las Olas Marina.",
      "Bote ágil de 28 ft para hasta 8. Saltos rápidos desde Las Olas Marina.",
      "Bateau agile de 28 ft pour 8. Sauts rapides depuis Las Olas Marina.",
      "Barca agile da 28 ft per 8. Salti rapidi da Las Olas Marina.",
      "Barco ágil de 28 ft para até 8. Saltos rápidos a partir de Las Olas Marina.",
    ),
  },
  {
    id: "monterey",
    name: "Monterey",
    class: "Bowrider",
    lengthFt: 22,
    guests: 6,
    hoursMin: 2,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/monterey-fl6833st.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["small"],
    captain: {
      name: "Captain Yara Mendes",
      license: "USCG OUPV Six-Pack",
      rating: 4.93,
      trips: 491,
      photo: "/crew/kaenz/selfie-22.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 22 ft boat for up to 6. Short hops from Hollywood Marina.",
      "Bote compacto de 22 ft para hasta 6. Saltos cortos desde Hollywood Marina.",
      "Bateau compact de 22 ft pour 6. Courts sauts depuis Hollywood Marina.",
      "Barca compatta da 22 ft per 6. Salti brevi da Hollywood Marina.",
      "Barco compacto de 22 ft para até 6. Saltos curtos a partir de Hollywood Marina.",
    ),
  },
  {
    id: "problem-solved",
    name: "Problem Solved",
    class: "Center console",
    lengthFt: 24,
    guests: 8,
    hoursMin: 2,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/problem-solved.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["small"],
    captain: {
      name: "Captain Theo Lang",
      license: "USCG OUPV Six-Pack",
      rating: 4.94,
      trips: 510,
      photo: "/crew/kaenz/selfie-23.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 24 ft boat for up to 8. Short hops from Palm Beach Town Docks.",
      "Bote compacto de 24 ft para hasta 8. Saltos cortos desde Palm Beach Town Docks.",
      "Bateau compact de 24 ft pour 8. Courts sauts depuis Palm Beach Town Docks.",
      "Barca compatta da 24 ft per 8. Salti brevi da Palm Beach Town Docks.",
      "Barco compacto de 24 ft para até 8. Saltos curtos a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "fl-0338-rc",
    name: "Blue Current",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/fl0338rc.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["fast"],
    captain: {
      name: "Captain Isla Navarro",
      license: "USCG Master 50 Ton",
      rating: 4.95,
      trips: 529,
      photo: "/crew/kaenz/selfie-24.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Dinner Key Marina.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Dinner Key Marina.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Dinner Key Marina.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Dinner Key Marina.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "fl-11234362",
    name: "Silver Saxdor",
    class: "Day cruiser",
    lengthFt: 40,
    guests: 10,
    hoursMin: 3,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/fl11234362.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["fast"],
    captain: {
      name: "Captain Kenji Watanabe",
      license: "USCG Master 50 Ton",
      rating: 4.96,
      trips: 548,
      photo: "/crew/kaenz/selfie-25.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft fast boat for up to 10. Beats the causeways from Haulover Park Marina.",
      "Bote rápido de 40 ft para hasta 10. Le gana a las calzadas desde Haulover Park Marina.",
      "Bateau rapide de 40 ft pour 10. Gagne sur les chaussées depuis Haulover Park Marina.",
      "Barca veloce da 40 ft per 10. Vince sulle calzate da Haulover Park Marina.",
      "Barco rápido de 40 ft para até 10. Ganha das calçadas a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "fl-1268-me",
    name: "Eight Up",
    class: "Deck boat",
    lengthFt: 26,
    guests: 8,
    hoursMin: 2,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/fl1268me.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["small"],
    captain: {
      name: "Captain Rosa Delgado",
      license: "USCG OUPV Six-Pack",
      rating: 4.97,
      trips: 567,
      photo: "/crew/kaenz/selfie-26.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 26 ft boat for up to 8. Short hops from Port Everglades.",
      "Bote compacto de 26 ft para hasta 8. Saltos cortos desde Port Everglades.",
      "Bateau compact de 26 ft pour 8. Courts sauts depuis Port Everglades.",
      "Barca compatta da 26 ft per 8. Salti brevi da Port Everglades.",
      "Barco compacto de 26 ft para até 8. Saltos curtos a partir de Port Everglades.",
    ),
  },
  {
    id: "fl-1511-nd",
    name: "Pad Day",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/fl1511nd.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["fast"],
    captain: {
      name: "Captain Malik Thompson",
      license: "USCG Master 50 Ton",
      rating: 4.98,
      trips: 586,
      photo: "/crew/kaenz/selfie-27.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from PortMiami.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde PortMiami.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis PortMiami.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da PortMiami.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de PortMiami.",
    ),
  },
  {
    id: "fl-1636-sn",
    name: "Bimini Day",
    class: "Bowrider",
    lengthFt: 22,
    guests: 6,
    hoursMin: 2,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/fl1636sn.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["small"],
    captain: {
      name: "Captain Chiara Greco",
      license: "USCG OUPV Six-Pack",
      rating: 4.99,
      trips: 605,
      photo: "/crew/kaenz/selfie-28.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 22 ft boat for up to 6. Short hops from Miami Beach Marina.",
      "Bote compacto de 22 ft para hasta 6. Saltos cortos desde Miami Beach Marina.",
      "Bateau compact de 22 ft pour 6. Courts sauts depuis Miami Beach Marina.",
      "Barca compatta da 22 ft per 6. Salti brevi da Miami Beach Marina.",
      "Barco compacto de 22 ft para até 6. Saltos curtos a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "fl-2336-al",
    name: "Century Blue",
    class: "Center console",
    lengthFt: 26,
    guests: 8,
    hoursMin: 3,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/fl2336al.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Hugo Silva",
      license: "USCG Master 50 Ton",
      rating: 4.86,
      trips: 624,
      photo: "/crew/kaenz/selfie-29.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 26 ft boat for up to 8. Quick bay hops from Island Gardens Miami.",
      "Bote ágil de 26 ft para hasta 8. Saltos rápidos desde Island Gardens Miami.",
      "Bateau agile de 26 ft pour 8. Sauts rapides depuis Island Gardens Miami.",
      "Barca agile da 26 ft per 8. Salti rapidi da Island Gardens Miami.",
      "Barco ágil de 26 ft para até 8. Saltos rápidos a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "fl-2514-ts",
    name: "Cabin Line",
    class: "Day cruiser",
    lengthFt: 37,
    guests: 10,
    hoursMin: 4,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/fl2514ts.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["fast", "luxurious"],
    captain: {
      name: "Captain Amira Hassan",
      license: "USCG Master 100 Ton",
      rating: 4.87,
      trips: 95,
      photo: "/crew/kaenz/selfie-30.jpg",
      verified: true,
    },
    blurb: blurb(
      "37 ft luxury yacht with pace. Up to 10 from Las Olas Marina.",
      "Yate de lujo de 37 ft, con ritmo. Hasta 10 desde Las Olas Marina.",
      "Yacht de luxe de 37 ft, avec allure. Jusqu’à 10 depuis Las Olas Marina.",
      "Yacht di lusso da 37 ft, con ritmo. Fino a 10 da Las Olas Marina.",
      "Iate de luxo de 37 ft, com ritmo. Até 10 a partir de Las Olas Marina.",
    ),
  },
  {
    id: "fl-2540-rh",
    name: "Ferris Bow",
    class: "Bowrider",
    lengthFt: 20,
    guests: 6,
    hoursMin: 2,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/fl2540rh.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["small"],
    captain: {
      name: "Captain Nico Berg",
      license: "USCG OUPV Six-Pack",
      rating: 4.88,
      trips: 114,
      photo: "/crew/kaenz/selfie-31.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 20 ft boat for up to 6. Short hops from Hollywood Marina.",
      "Bote compacto de 20 ft para hasta 6. Saltos cortos desde Hollywood Marina.",
      "Bateau compact de 20 ft pour 6. Courts sauts depuis Hollywood Marina.",
      "Barca compatta da 20 ft per 6. Salti brevi da Hollywood Marina.",
      "Barco compacto de 20 ft para até 6. Saltos curtos a partir de Hollywood Marina.",
    ),
  },
  {
    id: "fl-3014-rr",
    name: "Tahoe Run",
    class: "Bowrider",
    lengthFt: 20,
    guests: 6,
    hoursMin: 2,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/fl3014rr.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["small"],
    captain: {
      name: "Captain Valentina Ortiz",
      license: "USCG OUPV Six-Pack",
      rating: 4.89,
      trips: 133,
      photo: "/crew/kaenz/selfie-32.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 20 ft boat for up to 6. Short hops from Palm Beach Town Docks.",
      "Bote compacto de 20 ft para hasta 6. Saltos cortos desde Palm Beach Town Docks.",
      "Bateau compact de 20 ft pour 6. Courts sauts depuis Palm Beach Town Docks.",
      "Barca compatta da 20 ft per 6. Salti brevi da Palm Beach Town Docks.",
      "Barco compacto de 20 ft para até 6. Saltos curtos a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "fl-3697-sn",
    name: "Magenta",
    class: "Day cruiser",
    lengthFt: 37,
    guests: 10,
    hoursMin: 3,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/fl3697sn.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["fast"],
    captain: {
      name: "Captain Sean Gallagher",
      license: "USCG Master 50 Ton",
      rating: 4.9,
      trips: 152,
      photo: "/crew/kaenz/selfie-33.jpg",
      verified: true,
    },
    blurb: blurb(
      "37 ft fast boat for up to 10. Beats the causeways from Dinner Key Marina.",
      "Bote rápido de 37 ft para hasta 10. Le gana a las calzadas desde Dinner Key Marina.",
      "Bateau rapide de 37 ft pour 10. Gagne sur les chaussées depuis Dinner Key Marina.",
      "Barca veloce da 37 ft per 10. Vince sulle calzate da Dinner Key Marina.",
      "Barco rápido de 37 ft para até 10. Ganha das calçadas a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "fl-4229-sr",
    name: "Express SR",
    class: "Express cruiser",
    lengthFt: 40,
    guests: 10,
    hoursMin: 3,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/fl4229sr.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["fast"],
    captain: {
      name: "Captain Ines Carvalho",
      license: "USCG Master 50 Ton",
      rating: 4.91,
      trips: 171,
      photo: "/crew/kaenz/selfie-34.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft fast boat for up to 10. Beats the causeways from Haulover Park Marina.",
      "Bote rápido de 40 ft para hasta 10. Le gana a las calzadas desde Haulover Park Marina.",
      "Bateau rapide de 40 ft pour 10. Gagne sur les chaussées depuis Haulover Park Marina.",
      "Barca veloce da 40 ft per 10. Vince sulle calzate da Haulover Park Marina.",
      "Barco rápido de 40 ft para até 10. Ganha das calçadas a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "fl-4621-ms",
    name: "White Sundancer",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/fl4621ms.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["fast"],
    captain: {
      name: "Captain David Okoye",
      license: "USCG Master 50 Ton",
      rating: 4.92,
      trips: 190,
      photo: "/crew/kaenz/selfie-35.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Port Everglades.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Port Everglades.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Port Everglades.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Port Everglades.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Port Everglades.",
    ),
  },
  {
    id: "fl-5579-pj",
    name: "Cruisers Cream",
    class: "Express cruiser",
    lengthFt: 34,
    guests: 8,
    hoursMin: 3,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/fl5579pj.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["fast"],
    captain: {
      name: "Captain Freya Lind",
      license: "USCG Master 50 Ton",
      rating: 4.93,
      trips: 209,
      photo: "/crew/kaenz/selfie-36.jpg",
      verified: true,
    },
    blurb: blurb(
      "34 ft fast boat for up to 8. Beats the causeways from PortMiami.",
      "Bote rápido de 34 ft para hasta 8. Le gana a las calzadas desde PortMiami.",
      "Bateau rapide de 34 ft pour 8. Gagne sur les chaussées depuis PortMiami.",
      "Barca veloce da 34 ft per 8. Vince sulle calzate da PortMiami.",
      "Barco rápido de 34 ft para até 8. Ganha das calçadas a partir de PortMiami.",
    ),
  },
  {
    id: "fl-5732-rw",
    name: "Larson Black",
    class: "Express cruiser",
    lengthFt: 30,
    guests: 8,
    hoursMin: 3,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/fl5732rw.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["fast"],
    captain: {
      name: "Captain Pablo Herrera",
      license: "USCG Master 50 Ton",
      rating: 4.94,
      trips: 228,
      photo: "/crew/kaenz/selfie-37.jpg",
      verified: true,
    },
    blurb: blurb(
      "30 ft fast boat for up to 8. Beats the causeways from Miami Beach Marina.",
      "Bote rápido de 30 ft para hasta 8. Le gana a las calzadas desde Miami Beach Marina.",
      "Bateau rapide de 30 ft pour 8. Gagne sur les chaussées depuis Miami Beach Marina.",
      "Barca veloce da 30 ft per 8. Vince sulle calzate da Miami Beach Marina.",
      "Barco rápido de 30 ft para até 8. Ganha das calçadas a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "fl-5818-tl",
    name: "Bravo",
    class: "Center console",
    lengthFt: 26,
    guests: 8,
    hoursMin: 3,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/fl5818tl.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Mei Zhang",
      license: "USCG Master 50 Ton",
      rating: 4.95,
      trips: 247,
      photo: "/crew/kaenz/selfie-38.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 26 ft boat for up to 8. Quick bay hops from Island Gardens Miami.",
      "Bote ágil de 26 ft para hasta 8. Saltos rápidos desde Island Gardens Miami.",
      "Bateau agile de 26 ft pour 8. Sauts rapides depuis Island Gardens Miami.",
      "Barca agile da 26 ft per 8. Salti rapidi da Island Gardens Miami.",
      "Barco ágil de 26 ft para até 8. Saltos rápidos a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "fl-6032-mx",
    name: "Navy Sundancer",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/fl6032mx.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["fast"],
    captain: {
      name: "Captain Owen Fitzgerald",
      license: "USCG Master 50 Ton",
      rating: 4.96,
      trips: 266,
      photo: "/crew/kaenz/selfie-39.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Las Olas Marina.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Las Olas Marina.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Las Olas Marina.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Las Olas Marina.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Las Olas Marina.",
    ),
  },
  {
    id: "fl-6565-sj",
    name: "Picnic Deck",
    class: "Deck boat",
    lengthFt: 24,
    guests: 8,
    hoursMin: 2,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/fl6565sj.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["small"],
    captain: {
      name: "Captain Carmen Paredes",
      license: "USCG OUPV Six-Pack",
      rating: 4.97,
      trips: 285,
      photo: "/crew/kaenz/selfie-40.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 24 ft boat for up to 8. Short hops from Hollywood Marina.",
      "Bote compacto de 24 ft para hasta 8. Saltos cortos desde Hollywood Marina.",
      "Bateau compact de 24 ft pour 8. Courts sauts depuis Hollywood Marina.",
      "Barca compatta da 24 ft per 8. Salti brevi da Hollywood Marina.",
      "Barco compacto de 24 ft para até 8. Saltos curtos a partir de Hollywood Marina.",
    ),
  },
  {
    id: "fl-6607-pz",
    name: "Canal Gold",
    class: "Bowrider",
    lengthFt: 24,
    guests: 6,
    hoursMin: 2,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/fl6607pz.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["small"],
    captain: {
      name: "Captain Leo Kovacs",
      license: "USCG OUPV Six-Pack",
      rating: 4.98,
      trips: 304,
      photo: "/crew/kaenz/selfie-41.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 24 ft boat for up to 6. Short hops from Palm Beach Town Docks.",
      "Bote compacto de 24 ft para hasta 6. Saltos cortos desde Palm Beach Town Docks.",
      "Bateau compact de 24 ft pour 6. Courts sauts depuis Palm Beach Town Docks.",
      "Barca compatta da 24 ft per 6. Salti brevi da Palm Beach Town Docks.",
      "Barco compacto de 24 ft para até 6. Saltos curtos a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "fl-8555-rn",
    name: "Brickell Sea Ray",
    class: "Day cruiser",
    lengthFt: 26,
    guests: 8,
    hoursMin: 2,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/fl8555rn.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["small"],
    captain: {
      name: "Captain Nadine Faure",
      license: "USCG OUPV Six-Pack",
      rating: 4.99,
      trips: 323,
      photo: "/crew/kaenz/selfie-42.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 26 ft boat for up to 8. Short hops from Dinner Key Marina.",
      "Bote compacto de 26 ft para hasta 8. Saltos cortos desde Dinner Key Marina.",
      "Bateau compact de 26 ft pour 8. Courts sauts depuis Dinner Key Marina.",
      "Barca compatta da 26 ft per 8. Salti brevi da Dinner Key Marina.",
      "Barco compacto de 26 ft para até 8. Saltos curtos a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "fl-9127-tg",
    name: "Regal Bridge",
    class: "Flybridge yacht",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/fl9127tg.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["luxurious"],
    captain: {
      name: "Captain Bruno Almeida",
      license: "USCG Master 100 Ton",
      rating: 4.86,
      trips: 342,
      photo: "/crew/kaenz/selfie-43.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from Haulover Park Marina.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde Haulover Park Marina.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis Haulover Park Marina.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da Haulover Park Marina.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "fl-9344-rd",
    name: "Ladder Light",
    class: "Day cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/fl9344rd.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["fast", "small"],
    captain: {
      name: "Captain Aisha Rahman",
      license: "USCG Master 50 Ton",
      rating: 4.87,
      trips: 361,
      photo: "/crew/kaenz/selfie-44.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 32 ft boat for up to 8. Quick bay hops from Port Everglades.",
      "Bote ágil de 32 ft para hasta 8. Saltos rápidos desde Port Everglades.",
      "Bateau agile de 32 ft pour 8. Sauts rapides depuis Port Everglades.",
      "Barca agile da 32 ft per 8. Salti rapidi da Port Everglades.",
      "Barco ágil de 32 ft para até 8. Saltos rápidos a partir de Port Everglades.",
    ),
  },
  {
    id: "fl-9372-pz",
    name: "Open Deck",
    class: "Deck boat",
    lengthFt: 24,
    guests: 8,
    hoursMin: 2,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/fl9372pz.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["small"],
    captain: {
      name: "Captain Victor Pena",
      license: "USCG OUPV Six-Pack",
      rating: 4.88,
      trips: 380,
      photo: "/crew/kaenz/selfie-45.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 24 ft boat for up to 8. Short hops from PortMiami.",
      "Bote compacto de 24 ft para hasta 8. Saltos cortos desde PortMiami.",
      "Bateau compact de 24 ft pour 8. Courts sauts depuis PortMiami.",
      "Barca compatta da 24 ft per 8. Salti brevi da PortMiami.",
      "Barco compacto de 24 ft para até 8. Saltos curtos a partir de PortMiami.",
    ),
  },
  {
    id: "fl-9452-tj",
    name: "Rinker Run",
    class: "Bowrider",
    lengthFt: 22,
    guests: 6,
    hoursMin: 2,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/fl9452tj.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["small"],
    captain: {
      name: "Captain Sienna Walsh",
      license: "USCG OUPV Six-Pack",
      rating: 4.89,
      trips: 399,
      photo: "/crew/kaenz/selfie-46.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 22 ft boat for up to 6. Short hops from Miami Beach Marina.",
      "Bote compacto de 22 ft para hasta 6. Saltos cortos desde Miami Beach Marina.",
      "Bateau compact de 22 ft pour 6. Courts sauts depuis Miami Beach Marina.",
      "Barca compatta da 22 ft per 6. Salti brevi da Miami Beach Marina.",
      "Barco compacto de 22 ft para até 6. Saltos curtos a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "fl-9730-rr",
    name: "Element XR7",
    class: "Deck boat",
    lengthFt: 18,
    guests: 6,
    hoursMin: 2,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/fl9730rr.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["small"],
    captain: {
      name: "Captain Ravi Patel",
      license: "USCG OUPV Six-Pack",
      rating: 4.9,
      trips: 418,
      photo: "/crew/kaenz/selfie-47.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 18 ft boat for up to 6. Short hops from Island Gardens Miami.",
      "Bote compacto de 18 ft para hasta 6. Saltos cortos desde Island Gardens Miami.",
      "Bateau compact de 18 ft pour 6. Courts sauts depuis Island Gardens Miami.",
      "Barca compatta da 18 ft per 6. Salti brevi da Island Gardens Miami.",
      "Barco compacto de 18 ft para até 6. Saltos curtos a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "fl-9748-ly",
    name: "Harbor White",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/fl9748ly.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["fast"],
    captain: {
      name: "Captain Gabriela Soto",
      license: "USCG Master 50 Ton",
      rating: 4.91,
      trips: 437,
      photo: "/crew/kaenz/selfie-48.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Las Olas Marina.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Las Olas Marina.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Las Olas Marina.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Las Olas Marina.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Las Olas Marina.",
    ),
  },
  {
    id: "fl-9786-ps",
    name: "Hurricane Float",
    class: "Deck boat",
    lengthFt: 24,
    guests: 8,
    hoursMin: 2,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/fl9786ps.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["small"],
    captain: {
      name: "Captain Erik Nilsen",
      license: "USCG OUPV Six-Pack",
      rating: 4.92,
      trips: 456,
      photo: "/crew/kaenz/selfie-49.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 24 ft boat for up to 8. Short hops from Hollywood Marina.",
      "Bote compacto de 24 ft para hasta 8. Saltos cortos desde Hollywood Marina.",
      "Bateau compact de 24 ft pour 8. Courts sauts depuis Hollywood Marina.",
      "Barca compatta da 24 ft per 8. Salti brevi da Hollywood Marina.",
      "Barco compacto de 24 ft para até 8. Saltos curtos a partir de Hollywood Marina.",
    ),
  },
  {
    id: "fl-9912-ne",
    name: "Sundown",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/fl9912ne.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["fast"],
    captain: {
      name: "Captain Noor El-Sayed",
      license: "USCG Master 50 Ton",
      rating: 4.93,
      trips: 475,
      photo: "/crew/kaenz/selfie-50.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Palm Beach Town Docks.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Palm Beach Town Docks.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Palm Beach Town Docks.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Palm Beach Town Docks.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "tide-runner",
    name: "Tide Runner",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/1.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Tomasz Nowak",
      license: "USCG Master 50 Ton",
      rating: 4.94,
      trips: 494,
      photo: "/crew/kaenz/selfie-51.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 32 ft boat for up to 8. Quick bay hops from Dinner Key Marina.",
      "Bote ágil de 32 ft para hasta 8. Saltos rápidos desde Dinner Key Marina.",
      "Bateau agile de 32 ft pour 8. Sauts rapides depuis Dinner Key Marina.",
      "Barca agile da 32 ft per 8. Salti rapidi da Dinner Key Marina.",
      "Barco ágil de 32 ft para até 8. Saltos rápidos a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "bay-whisper",
    name: "Bay Whisper",
    class: "Express cruiser",
    lengthFt: 30,
    guests: 8,
    hoursMin: 3,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/2.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Camila Ferreira",
      license: "USCG Master 50 Ton",
      rating: 4.95,
      trips: 513,
      photo: "/crew/kaenz/selfie-52.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 30 ft boat for up to 8. Quick bay hops from Haulover Park Marina.",
      "Bote ágil de 30 ft para hasta 8. Saltos rápidos desde Haulover Park Marina.",
      "Bateau agile de 30 ft pour 8. Sauts rapides depuis Haulover Park Marina.",
      "Barca agile da 30 ft per 8. Salti rapidi da Haulover Park Marina.",
      "Barco ágil de 30 ft para até 8. Saltos rápidos a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "night-current",
    name: "Night Current",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/3.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["fast"],
    captain: {
      name: "Captain Jonah Brooks",
      license: "USCG Master 50 Ton",
      rating: 4.96,
      trips: 532,
      photo: "/crew/kaenz/selfie-53.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Port Everglades.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Port Everglades.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Port Everglades.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Port Everglades.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Port Everglades.",
    ),
  },
  {
    id: "pocket-element",
    name: "Pocket Element",
    class: "Bowrider",
    lengthFt: 18,
    guests: 5,
    hoursMin: 2,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/4.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["small"],
    captain: {
      name: "Captain Helena Costa",
      license: "USCG OUPV Six-Pack",
      rating: 4.97,
      trips: 551,
      photo: "/crew/kaenz/selfie-54.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 18 ft boat for up to 5. Short hops from PortMiami.",
      "Bote compacto de 18 ft para hasta 5. Saltos cortos desde PortMiami.",
      "Bateau compact de 18 ft pour 5. Courts sauts depuis PortMiami.",
      "Barca compatta da 18 ft per 5. Salti brevi da PortMiami.",
      "Barco compacto de 18 ft para até 5. Saltos curtos a partir de PortMiami.",
    ),
  },
  {
    id: "coconut-cruiser",
    name: "Coconut Cruiser",
    class: "Day cruiser",
    lengthFt: 28,
    guests: 6,
    hoursMin: 2,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/5.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["small"],
    captain: {
      name: "Captain Adrian Popescu",
      license: "USCG OUPV Six-Pack",
      rating: 4.98,
      trips: 570,
      photo: "/crew/kaenz/selfie-55.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 28 ft boat for up to 6. Short hops from Miami Beach Marina.",
      "Bote compacto de 28 ft para hasta 6. Saltos cortos desde Miami Beach Marina.",
      "Bateau compact de 28 ft pour 6. Courts sauts depuis Miami Beach Marina.",
      "Barca compatta da 28 ft per 6. Salti brevi da Miami Beach Marina.",
      "Barco compacto de 28 ft para até 6. Saltos curtos a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "dusk-patrol",
    name: "Dusk Patrol",
    class: "Center console",
    lengthFt: 24,
    guests: 6,
    hoursMin: 2,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/6.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["small"],
    captain: {
      name: "Captain Layla Bennett",
      license: "USCG OUPV Six-Pack",
      rating: 4.99,
      trips: 589,
      photo: "/crew/kaenz/selfie-56.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 24 ft boat for up to 6. Short hops from Island Gardens Miami.",
      "Bote compacto de 24 ft para hasta 6. Saltos cortos desde Island Gardens Miami.",
      "Bateau compact de 24 ft pour 6. Courts sauts depuis Island Gardens Miami.",
      "Barca compatta da 24 ft per 6. Salti brevi da Island Gardens Miami.",
      "Barco compacto de 24 ft para até 6. Saltos curtos a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "aqua-scout",
    name: "Aqua Scout",
    class: "Center console",
    lengthFt: 26,
    guests: 6,
    hoursMin: 2,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/7.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["small"],
    captain: {
      name: "Captain Enzo Ricci",
      license: "USCG OUPV Six-Pack",
      rating: 4.86,
      trips: 608,
      photo: "/crew/kaenz/selfie-57.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 26 ft boat for up to 6. Short hops from Las Olas Marina.",
      "Bote compacto de 26 ft para hasta 6. Saltos cortos desde Las Olas Marina.",
      "Bateau compact de 26 ft pour 6. Courts sauts depuis Las Olas Marina.",
      "Barca compatta da 26 ft per 6. Salti brevi da Las Olas Marina.",
      "Barco compacto de 26 ft para até 6. Saltos curtos a partir de Las Olas Marina.",
    ),
  },
  {
    id: "mini-element",
    name: "Mini Element",
    class: "Bowrider",
    lengthFt: 18,
    guests: 5,
    hoursMin: 2,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/8.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["small"],
    captain: {
      name: "Captain Maya Singh",
      license: "USCG OUPV Six-Pack",
      rating: 4.87,
      trips: 627,
      photo: "/crew/kaenz/selfie-58.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 18 ft boat for up to 5. Short hops from Hollywood Marina.",
      "Bote compacto de 18 ft para hasta 5. Saltos cortos desde Hollywood Marina.",
      "Bateau compact de 18 ft pour 5. Courts sauts depuis Hollywood Marina.",
      "Barca compatta da 18 ft per 5. Salti brevi da Hollywood Marina.",
      "Barco compacto de 18 ft para até 5. Saltos curtos a partir de Hollywood Marina.",
    ),
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    class: "Day cruiser",
    lengthFt: 28,
    guests: 8,
    hoursMin: 3,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/9.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Felipe Rojas",
      license: "USCG Master 50 Ton",
      rating: 4.88,
      trips: 98,
      photo: "/crew/kaenz/selfie-59.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 28 ft boat for up to 8. Quick bay hops from Palm Beach Town Docks.",
      "Bote ágil de 28 ft para hasta 8. Saltos rápidos desde Palm Beach Town Docks.",
      "Bateau agile de 28 ft pour 8. Sauts rapides depuis Palm Beach Town Docks.",
      "Barca agile da 28 ft per 8. Salti rapidi da Palm Beach Town Docks.",
      "Barco ágil de 28 ft para até 8. Saltos rápidos a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "sailfish",
    name: "Sailfish",
    class: "Walkaround",
    lengthFt: 28,
    guests: 6,
    hoursMin: 3,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/10.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Celine Marchand",
      license: "USCG Master 50 Ton",
      rating: 4.89,
      trips: 117,
      photo: "/crew/kaenz/selfie-60.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 28 ft boat for up to 6. Quick bay hops from Dinner Key Marina.",
      "Bote ágil de 28 ft para hasta 6. Saltos rápidos desde Dinner Key Marina.",
      "Bateau agile de 28 ft pour 6. Sauts rapides depuis Dinner Key Marina.",
      "Barca agile da 28 ft per 6. Salti rapidi da Dinner Key Marina.",
      "Barco ágil de 28 ft para até 6. Saltos rápidos a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "blue-sundancer",
    name: "Blue Sundancer",
    class: "Express cruiser",
    lengthFt: 40,
    guests: 10,
    hoursMin: 4,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/11.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["fast", "luxurious"],
    captain: {
      name: "Captain Kwame Asante",
      license: "USCG Master 100 Ton",
      rating: 4.9,
      trips: 136,
      photo: "/crew/kaenz/selfie-61.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft luxury yacht with pace. Up to 10 from Haulover Park Marina.",
      "Yate de lujo de 40 ft, con ritmo. Hasta 10 desde Haulover Park Marina.",
      "Yacht de luxe de 40 ft, avec allure. Jusqu’à 10 depuis Haulover Park Marina.",
      "Yacht di lusso da 40 ft, con ritmo. Fino a 10 da Haulover Park Marina.",
      "Iate de luxo de 40 ft, com ritmo. Até 10 a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "palacio",
    name: "Palacio",
    class: "Motor yacht",
    lengthFt: 90,
    guests: 13,
    hoursMin: 4,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/12.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["luxurious"],
    captain: {
      name: "Captain Olivia Hart",
      license: "USCG Master 100 Ton",
      rating: 4.91,
      trips: 155,
      photo: "/crew/kaenz/selfie-62.jpg",
      verified: true,
    },
    blurb: blurb(
      "90 ft luxury yacht for up to 13. Skyline and Intracoastal from Port Everglades.",
      "Yate de lujo de 90 ft para hasta 13. Skyline e Intracoastal desde Port Everglades.",
      "Yacht de luxe de 90 ft pour 13 personnes. Skyline et Intracoastal depuis Port Everglades.",
      "Yacht di lusso da 90 ft per 13 ospiti. Skyline e Intracoastal da Port Everglades.",
      "Iate de luxo de 90 ft para até 13. Skyline e Intracoastal a partir de Port Everglades.",
    ),
  },
  {
    id: "navy-sedan",
    name: "Navy Sedan",
    class: "Flybridge yacht",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/13.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["luxurious"],
    captain: {
      name: "Captain Santiago Leon",
      license: "USCG Master 100 Ton",
      rating: 4.92,
      trips: 174,
      photo: "/crew/kaenz/selfie-63.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from PortMiami.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde PortMiami.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis PortMiami.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da PortMiami.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de PortMiami.",
    ),
  },
  {
    id: "princess-crown",
    name: "Princess Crown",
    class: "Flybridge yacht",
    lengthFt: 55,
    guests: 13,
    hoursMin: 4,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/14.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["luxurious"],
    captain: {
      name: "Captain Ingrid Solberg",
      license: "USCG Master 100 Ton",
      rating: 4.93,
      trips: 193,
      photo: "/crew/kaenz/selfie-64.jpg",
      verified: true,
    },
    blurb: blurb(
      "55 ft luxury yacht for up to 13. Skyline and Intracoastal from Miami Beach Marina.",
      "Yate de lujo de 55 ft para hasta 13. Skyline e Intracoastal desde Miami Beach Marina.",
      "Yacht de luxe de 55 ft pour 13 personnes. Skyline et Intracoastal depuis Miami Beach Marina.",
      "Yacht di lusso da 55 ft per 13 ospiti. Skyline e Intracoastal da Miami Beach Marina.",
      "Iate de luxo de 55 ft para até 13. Skyline e Intracoastal a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "midnight-predator",
    name: "Midnight Predator",
    class: "Express yacht",
    lengthFt: 52,
    guests: 12,
    hoursMin: 4,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/15.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["luxurious", "fast"],
    captain: {
      name: "Captain Marco Teixeira",
      license: "USCG Master 100 Ton",
      rating: 4.94,
      trips: 212,
      photo: "/crew/kaenz/selfie-65.jpg",
      verified: true,
    },
    blurb: blurb(
      "52 ft luxury yacht with pace. Up to 12 from Island Gardens Miami.",
      "Yate de lujo de 52 ft, con ritmo. Hasta 12 desde Island Gardens Miami.",
      "Yacht de luxe de 52 ft, avec allure. Jusqu’à 12 depuis Island Gardens Miami.",
      "Yacht di lusso da 52 ft, con ritmo. Fino a 12 da Island Gardens Miami.",
      "Iate de luxo de 52 ft, com ritmo. Até 12 a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "sandbar-sundeck",
    name: "Sandbar Sundeck",
    class: "Day cruiser",
    lengthFt: 28,
    guests: 8,
    hoursMin: 3,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/16.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Amina Diallo",
      license: "USCG Master 50 Ton",
      rating: 4.95,
      trips: 231,
      photo: "/crew/kaenz/selfie-66.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 28 ft boat for up to 8. Quick bay hops from Las Olas Marina.",
      "Bote ágil de 28 ft para hasta 8. Saltos rápidos desde Las Olas Marina.",
      "Bateau agile de 28 ft pour 8. Sauts rapides depuis Las Olas Marina.",
      "Barca agile da 28 ft per 8. Salti rapidi da Las Olas Marina.",
      "Barco ágil de 28 ft para até 8. Saltos rápidos a partir de Las Olas Marina.",
    ),
  },
  {
    id: "ocean-eighty",
    name: "Ocean Eighty",
    class: "Motor yacht",
    lengthFt: 80,
    guests: 13,
    hoursMin: 4,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/17.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["luxurious"],
    captain: {
      name: "Captain Patrick Oneill",
      license: "USCG Master 100 Ton",
      rating: 4.96,
      trips: 250,
      photo: "/crew/kaenz/selfie-67.jpg",
      verified: true,
    },
    blurb: blurb(
      "80 ft luxury yacht for up to 13. Skyline and Intracoastal from Hollywood Marina.",
      "Yate de lujo de 80 ft para hasta 13. Skyline e Intracoastal desde Hollywood Marina.",
      "Yacht de luxe de 80 ft pour 13 personnes. Skyline et Intracoastal depuis Hollywood Marina.",
      "Yacht di lusso da 80 ft per 13 ospiti. Skyline e Intracoastal da Hollywood Marina.",
      "Iate de luxo de 80 ft para até 13. Skyline e Intracoastal a partir de Hollywood Marina.",
    ),
  },
  {
    id: "azimut-62",
    name: "Azimut 62",
    class: "Flybridge yacht",
    lengthFt: 62,
    guests: 13,
    hoursMin: 4,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/18.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["luxurious"],
    captain: {
      name: "Captain Lucia Benedetti",
      license: "USCG Master 100 Ton",
      rating: 4.97,
      trips: 269,
      photo: "/crew/kaenz/selfie-68.jpg",
      verified: true,
    },
    blurb: blurb(
      "62 ft luxury yacht for up to 13. Skyline and Intracoastal from Palm Beach Town Docks.",
      "Yate de lujo de 62 ft para hasta 13. Skyline e Intracoastal desde Palm Beach Town Docks.",
      "Yacht de luxe de 62 ft pour 13 personnes. Skyline et Intracoastal depuis Palm Beach Town Docks.",
      "Yacht di lusso da 62 ft per 13 ospiti. Skyline e Intracoastal da Palm Beach Town Docks.",
      "Iate de luxo de 62 ft para até 13. Skyline e Intracoastal a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "farside",
    name: "Farside",
    class: "Center console",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/19.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["fast"],
    captain: {
      name: "Captain Hassan Alami",
      license: "USCG Master 50 Ton",
      rating: 4.98,
      trips: 288,
      photo: "/crew/kaenz/selfie-69.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Dinner Key Marina.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Dinner Key Marina.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Dinner Key Marina.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Dinner Key Marina.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "brickell-fly",
    name: "Brickell Fly",
    class: "Flybridge yacht",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/20.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["luxurious"],
    captain: {
      name: "Captain Brooke Tanner",
      license: "USCG Master 100 Ton",
      rating: 4.99,
      trips: 307,
      photo: "/crew/kaenz/selfie-70.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from Haulover Park Marina.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde Haulover Park Marina.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis Haulover Park Marina.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da Haulover Park Marina.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "navy-azimut",
    name: "Navy Azimut",
    class: "Flybridge yacht",
    lengthFt: 55,
    guests: 13,
    hoursMin: 4,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/21.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["luxurious"],
    captain: {
      name: "Captain Iker Molina",
      license: "USCG Master 100 Ton",
      rating: 4.86,
      trips: 326,
      photo: "/crew/kaenz/selfie-71.jpg",
      verified: true,
    },
    blurb: blurb(
      "55 ft luxury yacht for up to 13. Skyline and Intracoastal from Port Everglades.",
      "Yate de lujo de 55 ft para hasta 13. Skyline e Intracoastal desde Port Everglades.",
      "Yacht de luxe de 55 ft pour 13 personnes. Skyline et Intracoastal depuis Port Everglades.",
      "Yacht di lusso da 55 ft per 13 ospiti. Skyline e Intracoastal da Port Everglades.",
      "Iate de luxo de 55 ft para até 13. Skyline e Intracoastal a partir de Port Everglades.",
    ),
  },
  {
    id: "canal-sprite",
    name: "Canal Sprite",
    class: "Bowrider",
    lengthFt: 20,
    guests: 6,
    hoursMin: 2,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/22.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["small"],
    captain: {
      name: "Captain Sophie Laurent",
      license: "USCG OUPV Six-Pack",
      rating: 4.87,
      trips: 345,
      photo: "/crew/kaenz/selfie-72.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 20 ft boat for up to 6. Short hops from PortMiami.",
      "Bote compacto de 20 ft para hasta 6. Saltos cortos desde PortMiami.",
      "Bateau compact de 20 ft pour 6. Courts sauts depuis PortMiami.",
      "Barca compatta da 20 ft per 6. Salti brevi da PortMiami.",
      "Barco compacto de 20 ft para até 6. Saltos curtos a partir de PortMiami.",
    ),
  },
  {
    id: "indigo-wake",
    name: "Indigo Wake",
    class: "Flybridge yacht",
    lengthFt: 48,
    guests: 12,
    hoursMin: 4,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/23.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["luxurious"],
    captain: {
      name: "Captain Daniel Kim",
      license: "USCG Master 100 Ton",
      rating: 4.88,
      trips: 364,
      photo: "/crew/kaenz/selfie-73.jpg",
      verified: true,
    },
    blurb: blurb(
      "48 ft luxury yacht for up to 12. Skyline and Intracoastal from Miami Beach Marina.",
      "Yate de lujo de 48 ft para hasta 12. Skyline e Intracoastal desde Miami Beach Marina.",
      "Yacht de luxe de 48 ft pour 12 personnes. Skyline et Intracoastal depuis Miami Beach Marina.",
      "Yacht di lusso da 48 ft per 12 ospiti. Skyline e Intracoastal da Miami Beach Marina.",
      "Iate de luxo de 48 ft para até 12. Skyline e Intracoastal a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "sedan-navy",
    name: "Sedan Navy",
    class: "Flybridge yacht",
    lengthFt: 48,
    guests: 12,
    hoursMin: 4,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/24.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["luxurious"],
    captain: {
      name: "Captain Paloma Reyes",
      license: "USCG Master 100 Ton",
      rating: 4.89,
      trips: 383,
      photo: "/crew/kaenz/selfie-74.jpg",
      verified: true,
    },
    blurb: blurb(
      "48 ft luxury yacht for up to 12. Skyline and Intracoastal from Island Gardens Miami.",
      "Yate de lujo de 48 ft para hasta 12. Skyline e Intracoastal desde Island Gardens Miami.",
      "Yacht de luxe de 48 ft pour 12 personnes. Skyline et Intracoastal depuis Island Gardens Miami.",
      "Yacht di lusso da 48 ft per 12 ospiti. Skyline e Intracoastal da Island Gardens Miami.",
      "Iate de luxo de 48 ft para até 12. Skyline e Intracoastal a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "regal-outboard",
    name: "Regal Outboard",
    class: "Day cruiser",
    lengthFt: 26,
    guests: 8,
    hoursMin: 2,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/25.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["small"],
    captain: {
      name: "Captain Nathan Price",
      license: "USCG OUPV Six-Pack",
      rating: 4.9,
      trips: 402,
      photo: "/crew/kaenz/selfie-75.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 26 ft boat for up to 8. Short hops from Las Olas Marina.",
      "Bote compacto de 26 ft para hasta 8. Saltos cortos desde Las Olas Marina.",
      "Bateau compact de 26 ft pour 8. Courts sauts depuis Las Olas Marina.",
      "Barca compatta da 26 ft per 8. Salti brevi da Las Olas Marina.",
      "Barco compacto de 26 ft para até 8. Saltos curtos a partir de Las Olas Marina.",
    ),
  },
  {
    id: "brickell-prestige",
    name: "Brickell Prestige",
    class: "Flybridge yacht",
    lengthFt: 50,
    guests: 13,
    hoursMin: 4,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/26.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["luxurious"],
    captain: {
      name: "Captain Fatima Zahra",
      license: "USCG Master 100 Ton",
      rating: 4.91,
      trips: 421,
      photo: "/crew/kaenz/selfie-76.jpg",
      verified: true,
    },
    blurb: blurb(
      "50 ft luxury yacht for up to 13. Skyline and Intracoastal from Hollywood Marina.",
      "Yate de lujo de 50 ft para hasta 13. Skyline e Intracoastal desde Hollywood Marina.",
      "Yacht de luxe de 50 ft pour 13 personnes. Skyline et Intracoastal depuis Hollywood Marina.",
      "Yacht di lusso da 50 ft per 13 ospiti. Skyline e Intracoastal da Hollywood Marina.",
      "Iate de luxo de 50 ft para até 13. Skyline e Intracoastal a partir de Hollywood Marina.",
    ),
  },
  {
    id: "twilight-bridge",
    name: "Twilight Bridge",
    class: "Flybridge yacht",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/27.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["luxurious"],
    captain: {
      name: "Captain Alessandro Conte",
      license: "USCG Master 100 Ton",
      rating: 4.92,
      trips: 440,
      photo: "/crew/kaenz/selfie-77.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from Palm Beach Town Docks.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde Palm Beach Town Docks.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis Palm Beach Town Docks.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da Palm Beach Town Docks.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "whitewater-express",
    name: "Whitewater Express",
    class: "Express cruiser",
    lengthFt: 34,
    guests: 8,
    hoursMin: 3,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/28.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["fast"],
    captain: {
      name: "Captain Jun Park",
      license: "USCG Master 50 Ton",
      rating: 4.93,
      trips: 459,
      photo: "/crew/kaenz/selfie-78.jpg",
      verified: true,
    },
    blurb: blurb(
      "34 ft fast boat for up to 8. Beats the causeways from Dinner Key Marina.",
      "Bote rápido de 34 ft para hasta 8. Le gana a las calzadas desde Dinner Key Marina.",
      "Bateau rapide de 34 ft pour 8. Gagne sur les chaussées depuis Dinner Key Marina.",
      "Barca veloce da 34 ft per 8. Vince sulle calzate da Dinner Key Marina.",
      "Barco rápido de 34 ft para até 8. Ganha das calçadas a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "golden-fly",
    name: "Golden Fly",
    class: "Flybridge yacht",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/29.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["luxurious"],
    captain: {
      name: "Captain Beatriz Campos",
      license: "USCG Master 100 Ton",
      rating: 4.94,
      trips: 478,
      photo: "/crew/kaenz/selfie-79.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from Haulover Park Marina.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde Haulover Park Marina.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis Haulover Park Marina.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da Haulover Park Marina.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "haulover-sportfish",
    name: "Haulover Sportfish",
    class: "Sportfish",
    lengthFt: 35,
    guests: 8,
    hoursMin: 3,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/30.jpg",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["fast"],
    captain: {
      name: "Captain Liam Donovan",
      license: "USCG Master 50 Ton",
      rating: 4.95,
      trips: 497,
      photo: "/crew/kaenz/selfie-80.jpg",
      verified: true,
    },
    blurb: blurb(
      "35 ft fast boat for up to 8. Beats the causeways from Port Everglades.",
      "Bote rápido de 35 ft para hasta 8. Le gana a las calzadas desde Port Everglades.",
      "Bateau rapide de 35 ft pour 8. Gagne sur les chaussées depuis Port Everglades.",
      "Barca veloce da 35 ft per 8. Vince sulle calzate da Port Everglades.",
      "Barco rápido de 35 ft para até 8. Ganha das calçadas a partir de Port Everglades.",
    ),
  },
  {
    id: "schaefer-slide",
    name: "Schaefer Slide",
    class: "Express cruiser",
    lengthFt: 38,
    guests: 10,
    hoursMin: 4,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/31.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["fast", "luxurious"],
    captain: {
      name: "Captain Yasmin Farouk",
      license: "USCG Master 100 Ton",
      rating: 4.96,
      trips: 516,
      photo: "/crew/kaenz/selfie-81.jpg",
      verified: true,
    },
    blurb: blurb(
      "38 ft luxury yacht with pace. Up to 10 from PortMiami.",
      "Yate de lujo de 38 ft, con ritmo. Hasta 10 desde PortMiami.",
      "Yacht de luxe de 38 ft, avec allure. Jusqu’à 10 depuis PortMiami.",
      "Yacht di lusso da 38 ft, con ritmo. Fino a 10 da PortMiami.",
      "Iate de luxo de 38 ft, com ritmo. Até 10 a partir de PortMiami.",
    ),
  },
  {
    id: "island-prestige",
    name: "Island Prestige",
    class: "Flybridge yacht",
    lengthFt: 45,
    guests: 12,
    hoursMin: 4,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/32.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["luxurious"],
    captain: {
      name: "Captain Roberto Nunez",
      license: "USCG Master 100 Ton",
      rating: 4.97,
      trips: 535,
      photo: "/crew/kaenz/selfie-82.jpg",
      verified: true,
    },
    blurb: blurb(
      "45 ft luxury yacht for up to 12. Skyline and Intracoastal from Miami Beach Marina.",
      "Yate de lujo de 45 ft para hasta 12. Skyline e Intracoastal desde Miami Beach Marina.",
      "Yacht de luxe de 45 ft pour 12 personnes. Skyline et Intracoastal depuis Miami Beach Marina.",
      "Yacht di lusso da 45 ft per 12 ospiti. Skyline e Intracoastal da Miami Beach Marina.",
      "Iate de luxo de 45 ft para até 12. Skyline e Intracoastal a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "onkor",
    name: "Onkor",
    class: "Express yacht",
    lengthFt: 40,
    guests: 10,
    hoursMin: 4,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/33.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["fast", "luxurious"],
    captain: {
      name: "Captain Claire Beaumont",
      license: "USCG Master 100 Ton",
      rating: 4.98,
      trips: 554,
      photo: "/crew/kaenz/selfie-83.jpg",
      verified: true,
    },
    blurb: blurb(
      "40 ft luxury yacht with pace. Up to 10 from Island Gardens Miami.",
      "Yate de lujo de 40 ft, con ritmo. Hasta 10 desde Island Gardens Miami.",
      "Yacht de luxe de 40 ft, avec allure. Jusqu’à 10 depuis Island Gardens Miami.",
      "Yacht di lusso da 40 ft, con ritmo. Fino a 10 da Island Gardens Miami.",
      "Iate de luxo de 40 ft, com ritmo. Até 10 a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    class: "Day cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/34.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["fast", "small"],
    captain: {
      name: "Captain Thiago Barbosa",
      license: "USCG Master 50 Ton",
      rating: 4.99,
      trips: 573,
      photo: "/crew/kaenz/selfie-84.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 32 ft boat for up to 8. Quick bay hops from Las Olas Marina.",
      "Bote ágil de 32 ft para hasta 8. Saltos rápidos desde Las Olas Marina.",
      "Bateau agile de 32 ft pour 8. Sauts rapides depuis Las Olas Marina.",
      "Barca agile da 32 ft per 8. Salti rapidi da Las Olas Marina.",
      "Barco ágil de 32 ft para até 8. Saltos rápidos a partir de Las Olas Marina.",
    ),
  },
  {
    id: "bayside-searay",
    name: "Bayside Sea Ray",
    class: "Express yacht",
    lengthFt: 46,
    guests: 12,
    hoursMin: 4,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/35.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["luxurious"],
    captain: {
      name: "Captain Harper Quinn",
      license: "USCG Master 100 Ton",
      rating: 4.86,
      trips: 592,
      photo: "/crew/kaenz/selfie-85.jpg",
      verified: true,
    },
    blurb: blurb(
      "46 ft luxury yacht for up to 12. Skyline and Intracoastal from Hollywood Marina.",
      "Yate de lujo de 46 ft para hasta 12. Skyline e Intracoastal desde Hollywood Marina.",
      "Yacht de luxe de 46 ft pour 12 personnes. Skyline et Intracoastal depuis Hollywood Marina.",
      "Yacht di lusso da 46 ft per 12 ospiti. Skyline e Intracoastal da Hollywood Marina.",
      "Iate de luxo de 46 ft para até 12. Skyline e Intracoastal a partir de Hollywood Marina.",
    ),
  },
  {
    id: "greyhound",
    name: "Greyhound",
    class: "Motor yacht",
    lengthFt: 75,
    guests: 13,
    hoursMin: 4,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/36.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["luxurious", "fast"],
    captain: {
      name: "Captain Imani Johnson",
      license: "USCG Master 100 Ton",
      rating: 4.87,
      trips: 611,
      photo: "/crew/kaenz/selfie-86.jpg",
      verified: true,
    },
    blurb: blurb(
      "75 ft luxury yacht with pace. Up to 13 from Palm Beach Town Docks.",
      "Yate de lujo de 75 ft, con ritmo. Hasta 13 desde Palm Beach Town Docks.",
      "Yacht de luxe de 75 ft, avec allure. Jusqu’à 13 depuis Palm Beach Town Docks.",
      "Yacht di lusso da 75 ft, con ritmo. Fino a 13 da Palm Beach Town Docks.",
      "Iate de luxo de 75 ft, com ritmo. Até 13 a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "white-pearl",
    name: "White Pearl",
    class: "Express yacht",
    lengthFt: 50,
    guests: 12,
    hoursMin: 4,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/37.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["luxurious"],
    captain: {
      name: "Captain Stefan Petrov",
      license: "USCG Master 100 Ton",
      rating: 4.88,
      trips: 630,
      photo: "/crew/kaenz/selfie-87.jpg",
      verified: true,
    },
    blurb: blurb(
      "50 ft luxury yacht for up to 12. Skyline and Intracoastal from Dinner Key Marina.",
      "Yate de lujo de 50 ft para hasta 12. Skyline e Intracoastal desde Dinner Key Marina.",
      "Yacht de luxe de 50 ft pour 12 personnes. Skyline et Intracoastal depuis Dinner Key Marina.",
      "Yacht di lusso da 50 ft per 12 ospiti. Skyline e Intracoastal da Dinner Key Marina.",
      "Iate de luxo de 50 ft para até 12. Skyline e Intracoastal a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "silver-streak",
    name: "Silver Streak",
    class: "Express yacht",
    lengthFt: 48,
    guests: 12,
    hoursMin: 4,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/38.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["luxurious", "fast"],
    captain: {
      name: "Captain Catalina Vega",
      license: "USCG Master 100 Ton",
      rating: 4.89,
      trips: 101,
      photo: "/crew/kaenz/selfie-88.jpg",
      verified: true,
    },
    blurb: blurb(
      "48 ft luxury yacht with pace. Up to 12 from Haulover Park Marina.",
      "Yate de lujo de 48 ft, con ritmo. Hasta 12 desde Haulover Park Marina.",
      "Yacht de luxe de 48 ft, avec allure. Jusqu’à 12 depuis Haulover Park Marina.",
      "Yacht di lusso da 48 ft, con ritmo. Fino a 12 da Haulover Park Marina.",
      "Iate de luxo de 48 ft, com ritmo. Até 12 a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "wake-maker",
    name: "Wake Maker",
    class: "Flybridge yacht",
    lengthFt: 50,
    guests: 12,
    hoursMin: 4,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/39.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["luxurious", "fast"],
    captain: {
      name: "Captain Miles Harrington",
      license: "USCG Master 100 Ton",
      rating: 4.9,
      trips: 120,
      photo: "/crew/kaenz/selfie-89.jpg",
      verified: true,
    },
    blurb: blurb(
      "50 ft luxury yacht with pace. Up to 12 from Port Everglades.",
      "Yate de lujo de 50 ft, con ritmo. Hasta 12 desde Port Everglades.",
      "Yacht de luxe de 50 ft, avec allure. Jusqu’à 12 depuis Port Everglades.",
      "Yacht di lusso da 50 ft, con ritmo. Fino a 12 da Port Everglades.",
      "Iate de luxo de 50 ft, com ritmo. Até 12 a partir de Port Everglades.",
    ),
  },
  {
    id: "sandbar-grady",
    name: "Sandbar Grady",
    class: "Walkaround",
    lengthFt: 30,
    guests: 8,
    hoursMin: 3,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/40.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["small", "fast"],
    captain: {
      name: "Captain Leila Bouazizi",
      license: "USCG Master 50 Ton",
      rating: 4.91,
      trips: 139,
      photo: "/crew/kaenz/selfie-90.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 30 ft boat for up to 8. Quick bay hops from PortMiami.",
      "Bote ágil de 30 ft para hasta 8. Saltos rápidos desde PortMiami.",
      "Bateau agile de 30 ft pour 8. Sauts rapides depuis PortMiami.",
      "Barca agile da 30 ft per 8. Salti rapidi da PortMiami.",
      "Barco ágil de 30 ft para até 8. Saltos rápidos a partir de PortMiami.",
    ),
  },
  {
    id: "palm-aquasport",
    name: "Palm Aquasport",
    class: "Walkaround",
    lengthFt: 26,
    guests: 6,
    hoursMin: 2,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/41.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["small"],
    captain: {
      name: "Captain Giovanni Russo",
      license: "USCG OUPV Six-Pack",
      rating: 4.92,
      trips: 158,
      photo: "/crew/kaenz/selfie-91.jpg",
      verified: true,
    },
    blurb: blurb(
      "Compact 26 ft boat for up to 6. Short hops from Miami Beach Marina.",
      "Bote compacto de 26 ft para hasta 6. Saltos cortos desde Miami Beach Marina.",
      "Bateau compact de 26 ft pour 6. Courts sauts depuis Miami Beach Marina.",
      "Barca compatta da 26 ft per 6. Salti brevi da Miami Beach Marina.",
      "Barco compacto de 26 ft para até 6. Saltos curtos a partir de Miami Beach Marina.",
    ),
  },
  {
    id: "blue-water",
    name: "Blue Water",
    class: "Center console",
    lengthFt: 35,
    guests: 10,
    hoursMin: 3,
    marina: "Island Gardens Miami",
    marinaId: "island-gardens",
    image: "/fleet/kaenz/42.webp",
    lat: 25.7851,
    lng: -80.1774,
    etaMin: 6,
    traits: ["fast"],
    captain: {
      name: "Captain Anika Sharma",
      license: "USCG Master 50 Ton",
      rating: 4.93,
      trips: 177,
      photo: "/crew/kaenz/selfie-92.jpg",
      verified: true,
    },
    blurb: blurb(
      "35 ft fast boat for up to 10. Beats the causeways from Island Gardens Miami.",
      "Bote rápido de 35 ft para hasta 10. Le gana a las calzadas desde Island Gardens Miami.",
      "Bateau rapide de 35 ft pour 10. Gagne sur les chaussées depuis Island Gardens Miami.",
      "Barca veloce da 35 ft per 10. Vince sulle calzate da Island Gardens Miami.",
      "Barco rápido de 35 ft para até 10. Ganha das calçadas a partir de Island Gardens Miami.",
    ),
  },
  {
    id: "aerial-prestige",
    name: "Aerial Prestige",
    class: "Flybridge yacht",
    lengthFt: 42,
    guests: 12,
    hoursMin: 4,
    marina: "Las Olas Marina",
    marinaId: "las-olas-marina",
    image: "/fleet/kaenz/43.webp",
    lat: 26.1192,
    lng: -80.108,
    etaMin: 14,
    traits: ["luxurious"],
    captain: {
      name: "Captain Oscar Lindstrom",
      license: "USCG Master 100 Ton",
      rating: 4.94,
      trips: 196,
      photo: "/crew/kaenz/selfie-93.jpg",
      verified: true,
    },
    blurb: blurb(
      "42 ft luxury yacht for up to 12. Skyline and Intracoastal from Las Olas Marina.",
      "Yate de lujo de 42 ft para hasta 12. Skyline e Intracoastal desde Las Olas Marina.",
      "Yacht de luxe de 42 ft pour 12 personnes. Skyline et Intracoastal depuis Las Olas Marina.",
      "Yacht di lusso da 42 ft per 12 ospiti. Skyline e Intracoastal da Las Olas Marina.",
      "Iate de luxo de 42 ft para até 12. Skyline e Intracoastal a partir de Las Olas Marina.",
    ),
  },
  {
    id: "tangerine",
    name: "Tangerine",
    class: "Express yacht",
    lengthFt: 43,
    guests: 10,
    hoursMin: 4,
    marina: "Hollywood Marina",
    marinaId: "hollywood-marina",
    image: "/fleet/kaenz/44.webp",
    lat: 26.0114,
    lng: -80.1238,
    etaMin: 12,
    traits: ["luxurious", "fast"],
    captain: {
      name: "Captain Daniela Ibarra",
      license: "USCG Master 100 Ton",
      rating: 4.95,
      trips: 215,
      photo: "/crew/kaenz/selfie-94.jpg",
      verified: true,
    },
    blurb: blurb(
      "43 ft luxury yacht with pace. Up to 10 from Hollywood Marina.",
      "Yate de lujo de 43 ft, con ritmo. Hasta 10 desde Hollywood Marina.",
      "Yacht de luxe de 43 ft, avec allure. Jusqu’à 10 depuis Hollywood Marina.",
      "Yacht di lusso da 43 ft, con ritmo. Fino a 10 da Hollywood Marina.",
      "Iate de luxo de 43 ft, com ritmo. Até 10 a partir de Hollywood Marina.",
    ),
  },
  {
    id: "azimut-fifty",
    name: "Azimut Fifty",
    class: "Flybridge yacht",
    lengthFt: 50,
    guests: 13,
    hoursMin: 4,
    marina: "Palm Beach Town Docks",
    marinaId: "palm-beach-docks",
    image: "/fleet/kaenz/45.webp",
    lat: 26.7056,
    lng: -80.0364,
    etaMin: 18,
    traits: ["luxurious"],
    captain: {
      name: "Captain Felix Morel",
      license: "USCG Master 100 Ton",
      rating: 4.96,
      trips: 234,
      photo: "/crew/kaenz/selfie-95.jpg",
      verified: true,
    },
    blurb: blurb(
      "50 ft luxury yacht for up to 13. Skyline and Intracoastal from Palm Beach Town Docks.",
      "Yate de lujo de 50 ft para hasta 13. Skyline e Intracoastal desde Palm Beach Town Docks.",
      "Yacht de luxe de 50 ft pour 13 personnes. Skyline et Intracoastal depuis Palm Beach Town Docks.",
      "Yacht di lusso da 50 ft per 13 ospiti. Skyline e Intracoastal da Palm Beach Town Docks.",
      "Iate de luxo de 50 ft para até 13. Skyline e Intracoastal a partir de Palm Beach Town Docks.",
    ),
  },
  {
    id: "black-thunder",
    name: "Black Thunder",
    class: "Express yacht",
    lengthFt: 50,
    guests: 12,
    hoursMin: 4,
    marina: "Dinner Key Marina",
    marinaId: "dinner-key",
    image: "/fleet/kaenz/46.webp",
    lat: 25.7274,
    lng: -80.2347,
    etaMin: 10,
    traits: ["luxurious", "fast"],
    captain: {
      name: "Captain Zara Ahmed",
      license: "USCG Master 100 Ton",
      rating: 4.97,
      trips: 253,
      photo: "/crew/kaenz/selfie-96.jpg",
      verified: true,
    },
    blurb: blurb(
      "50 ft luxury yacht with pace. Up to 12 from Dinner Key Marina.",
      "Yate de lujo de 50 ft, con ritmo. Hasta 12 desde Dinner Key Marina.",
      "Yacht de luxe de 50 ft, avec allure. Jusqu’à 12 depuis Dinner Key Marina.",
      "Yacht di lusso da 50 ft, con ritmo. Fino a 12 da Dinner Key Marina.",
      "Iate de luxo de 50 ft, com ritmo. Até 12 a partir de Dinner Key Marina.",
    ),
  },
  {
    id: "quad-force",
    name: "Quad Force",
    class: "Center console",
    lengthFt: 38,
    guests: 10,
    hoursMin: 3,
    marina: "Haulover Park Marina",
    marinaId: "haulover",
    image: "/fleet/kaenz/47.webp",
    lat: 25.9029,
    lng: -80.1231,
    etaMin: 9,
    traits: ["fast"],
    captain: {
      name: "Captain Henrique Lopes",
      license: "USCG Master 50 Ton",
      rating: 4.98,
      trips: 272,
      photo: "/crew/kaenz/selfie-97.jpg",
      verified: true,
    },
    blurb: blurb(
      "38 ft fast boat for up to 10. Beats the causeways from Haulover Park Marina.",
      "Bote rápido de 38 ft para hasta 10. Le gana a las calzadas desde Haulover Park Marina.",
      "Bateau rapide de 38 ft pour 10. Gagne sur les chaussées depuis Haulover Park Marina.",
      "Barca veloce da 38 ft per 10. Vince sulle calzate da Haulover Park Marina.",
      "Barco rápido de 38 ft para até 10. Ganha das calçadas a partir de Haulover Park Marina.",
    ),
  },
  {
    id: "monterey-gold",
    name: "Monterey Gold",
    class: "Express cruiser",
    lengthFt: 32,
    guests: 8,
    hoursMin: 3,
    marina: "Port Everglades",
    marinaId: "port-everglades",
    image: "/fleet/kaenz/48.webp",
    lat: 26.094,
    lng: -80.115,
    etaMin: 11,
    traits: ["fast"],
    captain: {
      name: "Captain Naomi Brooks",
      license: "USCG Master 50 Ton",
      rating: 4.99,
      trips: 291,
      photo: "/crew/kaenz/selfie-98.jpg",
      verified: true,
    },
    blurb: blurb(
      "32 ft fast boat for up to 8. Beats the causeways from Port Everglades.",
      "Bote rápido de 32 ft para hasta 8. Le gana a las calzadas desde Port Everglades.",
      "Bateau rapide de 32 ft pour 8. Gagne sur les chaussées depuis Port Everglades.",
      "Barca veloce da 32 ft per 8. Vince sulle calzate da Port Everglades.",
      "Barco rápido de 32 ft para até 8. Ganha das calçadas a partir de Port Everglades.",
    ),
  },
  {
    id: "silver-line",
    name: "Silver Line",
    class: "Motor yacht",
    lengthFt: 80,
    guests: 13,
    hoursMin: 4,
    marina: "PortMiami",
    marinaId: "port-miami",
    image: "/fleet/kaenz/49.webp",
    lat: 25.778,
    lng: -80.177,
    etaMin: 6,
    traits: ["luxurious", "fast"],
    captain: {
      name: "Captain Andres Castillo",
      license: "USCG Master 100 Ton",
      rating: 4.86,
      trips: 310,
      photo: "/crew/kaenz/selfie-99.jpg",
      verified: true,
    },
    blurb: blurb(
      "80 ft luxury yacht with pace. Up to 13 from PortMiami.",
      "Yate de lujo de 80 ft, con ritmo. Hasta 13 desde PortMiami.",
      "Yacht de luxe de 80 ft, avec allure. Jusqu’à 13 depuis PortMiami.",
      "Yacht di lusso da 80 ft, con ritmo. Fino a 13 da PortMiami.",
      "Iate de luxo de 80 ft, com ritmo. Até 13 a partir de PortMiami.",
    ),
  },
  {
    id: "axopar-dusk",
    name: "Axopar Dusk",
    class: "Day cruiser",
    lengthFt: 37,
    guests: 8,
    hoursMin: 3,
    marina: "Miami Beach Marina",
    marinaId: "miami-beach-marina",
    image: "/fleet/kaenz/50.webp",
    lat: 25.7785,
    lng: -80.1452,
    etaMin: 8,
    traits: ["fast", "small"],
    captain: {
      name: "Captain Elise Moreau",
      license: "USCG Master 50 Ton",
      rating: 4.87,
      trips: 329,
      photo: "/crew/kaenz/selfie-100.jpg",
      verified: true,
    },
    blurb: blurb(
      "Agile 37 ft boat for up to 8. Quick bay hops from Miami Beach Marina.",
      "Bote ágil de 37 ft para hasta 8. Saltos rápidos desde Miami Beach Marina.",
      "Bateau agile de 37 ft pour 8. Sauts rapides depuis Miami Beach Marina.",
      "Barca agile da 37 ft per 8. Salti rapidi da Miami Beach Marina.",
      "Barco ágil de 37 ft para até 8. Saltos rápidos a partir de Miami Beach Marina.",
    ),
  },
];

export const marinas = [
  "Miami Beach Marina",
  "Island Gardens Miami",
  "Las Olas Marina",
  "Hollywood Marina",
  "Palm Beach Town Docks",
  "Dinner Key Marina",
  "Haulover Park Marina",
  "Port Everglades",
  "PortMiami",
];

export const destinations = [
  "Brickell",
  "Miami Beach",
  "Hollywood Beach sandbar",
  "Fort Lauderdale",
  "Palm Beach",
  "Biscayne Bay cruise",
  "Sunset Intracoastal",
];

export function yachtById(id: string) {
  return yachts.find((y) => y.id === id);
}

export function formatUsd(n: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);
}
